### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by uriva** [SergeyPirogov/webdriver_manager#102]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/lib/python3.8/site-packages/scraping/web.py", line 563, in done_callback
>     knowledge_slice, further = future.result()
>   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
>     raise self._exception
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.8/site-packages/scraping/web.py", line 481, in _do_order_group
>     driver = scraping_util.make_driver(implicit_wait_time, headless=headless)
>   File "/usr/local/lib/python3.8/site-packages/scraping/scraping_util.py", line 16, in make_driver
>     executable_path=chrome.ChromeDriverManager().install(), chrome_options=option
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/chrome.py", line 27, in install
>     driver_path = self.download_driver(self.driver)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/manager.py", line 39, in download_driver
>     path = self.__download_and_save_driver_to_cache(driver, driver_version)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/manager.py", line 28, in __download_and_save_driver_to_cache
>     return self.driver_cache.save_driver_to_cache(response, driver.get_name(), driver_version,
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/driver_cache.py", line 64, in save_driver_to_cache
>     files = self.__unpack(file_path)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/driver_cache.py", line 113, in __unpack
>     return extract_zip(path, to_directory)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/archive.py", line 6, in extract_zip
>     archive = zipfile.ZipFile(zip_file)
>   File "/usr/local/lib/python3.8/zipfile.py", line 1269, in __init__
>     self._RealGetContents()
>   File "/usr/local/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file
>

**Comment by SergeyPirogov** [comment]
@uriva could you please add more details? Driver, version, system etc

**Comment by uriva** [comment]
yes sorry:
python 3.8.2, linux

code:

`chrome.ChromeDriverManager().install()`

And it seems to work despite the exception (?).

Also some logs indicate the chrome version:

> Trying to download new driver from http://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip
> Trying to download new driver from http://chromedriver.storage.googleapis.com/81.0.4044.138/chromedriver_linux64.zip
> Unpack archive /root/.wdm/drivers/chromedriver/81.0.4044.138/linux64/chromedriver.zip
> [] [06-05-2020:11:08:21,285] [ERROR   ] [_base.py:330] exception calling callback for <Future at 0x7fd4da7608e0 state=finished raised BadZipFile>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
>     callback(self)
>   File "/usr/local/lib/python3.8/site-packages/scraping/web.py", line 563, in done_callback
>     knowledge_slice, further = future.result()
>   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
>     raise self._exception
>   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.8/site-packages/scraping/web.py", line 481, in _do_order_group
>     driver = scraping_util.make_driver(implicit_wait_time, headless=headless)
>   File "/usr/local/lib/python3.8/site-packages/scraping/scraping_util.py", line 16, in make_driver
>     executable_path=chrome.ChromeDriverManager().install(), chrome_options=option
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/chrome.py", line 27, in install
>     driver_path = self.download_driver(self.driver)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/manager.py", line 39, in download_driver
>     path = self.__download_and_save_driver_to_cache(driver, driver_version)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/manager.py", line 28, in __download_and_save_driver_to_cache
>     return self.driver_cache.save_driver_to_cache(response, driver.get_name(), driver_version,
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/driver_cache.py", line 64, in save_driver_to_cache
>     files = self.__unpack(file_path)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/driver_cache.py", line 113, in __unpack
>     return extract_zip(path, to_directory)
>   File "/usr/local/lib/python3.8/site-packages/webdriver_manager/archive.py", line 6, in extract_zip
>     archive = zipfile.ZipFile(zip_file)
>   File "/usr/local/lib/python3.8/zipfile.py", line 1269, in __init__
>     self._RealGetContents()
>   File "/usr/local/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file
> Unpack archive /root/.wdm/drivers/chromedriver/81.0.4044.138/linux64/chromedriver.zip
>

**Comment by uriva** [comment]
I think this is a threading issue, writing and reading to file might be non thread safe.

**Comment by SergeyPirogov** [comment]
Yes, exactly
