### ISSUE TITLE
version 2.5.0 = New Logger brakes dynamic printed logs

### ISSUE THREAD

**Issue by asket888** [SergeyPirogov/webdriver_manager#110]
Hi, I use webdriver_manager for A/B testing semi-automation tool. One performs some preconditions on the tested environment and makes screenshots. 
Since this tool is used browser headless mode and runs on the local machine (not CI) it is important to have dynamic logs to show what is going on at the moment.
![Screenshot 2020-05-15 at 13 03 15](https://user-images.githubusercontent.com/25345124/82043847-8d74ba00-96ac-11ea-9566-3167225db93f.png)

After '==2.5.0' version was realized, new log wrapper incapsulate all internal logs and prints them statically only after full execution. So this is not the same as what I would like to achieve.

Have you got any workaround, how to totally remove webdriver_manager logs like it was before (not just hide them by os.environ['WDM_LOG_LEVEL'] = '0')? Version '==2.4.0' was awesome. 

IMO webdriver_manager is not the one that should handle all automated testing logs

**Comment by SergeyPirogov** [comment]
Need to fix this.

**Comment by SergeyPirogov** [comment]
@asket888 I've published 2.5.1 with fixes #111. Could you test it?

**Comment by asket888** [comment]
Hi Sergey, new logger is still wrapping internal logs.

v.2.4.0 (expected behavior):
![82221983-fa908580-9920-11ea-9b6f-4bbaa9613650](https://user-images.githubusercontent.com/25345124/82226693-1bf47000-9927-11ea-8d3b-1d6dce847c61.gif)

v.2.5.1 (actual behavior)
![82222048-109e4600-9921-11ea-9943-5c36e87b786e](https://user-images.githubusercontent.com/25345124/82226777-3595b780-9927-11ea-9848-9ca31035b6a8.gif)

**Comment by SergeyPirogov** [comment]
To be honest, I don't have capacity to fix this quickly.

**Comment by SergeyPirogov** [comment]
@asket888 please try v2.5.2

**Comment by asket888** [comment]
I have run the test against v2.5.2, but it still wraps all internal logs.

I could suggest that the real reason is that for my internal logs I'm not using Logger() but print(). print() is better to display console output of a command-line program even according to logging documentation (https://docs.python.org/3/howto/logging.html).

Could it be the reason?

**Comment by asket888** [comment]
I'll add the code example I have for the console output:
![Screenshot 2020-05-22 at 11 23 54](https://user-images.githubusercontent.com/25345124/82652993-d681bc80-9c1e-11ea-8561-fb7f7f0eed0f.png)

**Comment by SergeyPirogov** [comment]
Well, ok. Lets try this one. Later today will deploy 2.5.3

**Comment by SergeyPirogov** [comment]
@asket888 Can you try this one 

```
pip install git+https://github.com/SergeyPirogov/webdriver_manager/tree/logger-alternative
```

**Comment by asket888** [comment]
Just for History. To install the library from the specific branch via pipenv:

`pipenv install -e git+https://github.com/SergeyPirogov/webdriver_manager@{branch_name}#egg={package_name}
`

`pipenv install -e git+https://github.com/SergeyPirogov/webdriver_manager@logger-alternative#egg=webdriver-manager
`

**Comment by SergeyPirogov** [comment]
@asket888 So, is it working as expected now?

**Comment by asket888** [comment]
Nope. It still wraps internal logs
![May-22-2020 14-39-20](https://user-images.githubusercontent.com/25345124/82668493-23bf5780-9c3a-11ea-97b5-dbe6d8753199.gif)

**Comment by SergeyPirogov** [comment]
You are doing something wrong. Di you use -v key for pytest?

**Comment by asket888** [comment]
I don't use pytest for my tool

**Comment by asket888** [comment]
Only python, selenium, webdriver_manager

**Comment by SergeyPirogov** [comment]
So what do you use? In the new version, wd uses just print.

**Comment by SergeyPirogov** [comment]
@asket888 Show me your test

**Comment by asket888** [comment]
No pytest, behave or any other test runner. It is not a testing tool

![Screenshot 2020-05-22 at 14 47 22](https://user-images.githubusercontent.com/25345124/82669144-2c645d80-9c3b-11ea-8081-4cd260ef2290.png)

**Comment by SergeyPirogov** [comment]
So, it some a special case. I don't know how we can fix this

**Comment by asket888** [comment]
Ok, I'll use version 2.4.0. It wors really well
