### ISSUE TITLE
Supressing logs is not working

### ISSUE THREAD

**Issue by jedi2610** [SergeyPirogov/webdriver_manager#114]
`driver=webdriver.Chrome(ChromeDriverManager(log_level=0).install(), options=chromeOptions)`
and
`os.environ['WDM_LOG_LEVEL'] = '0'`
does not seem work. It still logs messages like:
```
[WDM] - Looking for [chromedriver 2.26 win32] driver in cache
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/2.26/chromedriver_win32.zip
```

**Comment by jedi2610** [comment]
I even tried 
`driver=webdriver.Chrome(ChromeDriverManager(log_level=logging.CRITICAL).install())`
to suppress all the INFO logs but that doesn't work too.

**Comment by jedi2610** [comment]
Do you need more details on this? @SergeyPirogov

**Comment by SergeyPirogov** [comment]
No, it's clear. Thank you

**Comment by SergeyPirogov** [comment]
@aleksandr-kotlyar can you help?

**Comment by jedi2610** [comment]
Please try changing the method name in this [file](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/logger.py#L19) to something else as the logging module has a method with the same name.
I might be wrong but i think this causes the problem.

**Comment by jedi2610** [comment]
nvm, i was actually wrong.

**Comment by jedi2610** [comment]
I actually found the cause of this problem. Have a look at this [comment](https://stackoverflow.com/questions/47542493/how-to-turn-off-command-line-logging-in-selenium-using-chrome-in-python#comment82136467_47542493) from a stackoverflow post. windows is printing both stdout and stderr at the same time. i ran my program by redirecting the stderr output to nul (by using 2> nul while running the program) and then it worked. ik this is out of the scope of this issue but can you help me with this in any means?

**Comment by narkocam** [comment]
import os
os.environ["WDM_LOG_LEVEL"] = str(logging.WARNING)

**Comment by nottrif** [comment]
hi this is notjedi's friend two years later randomly opening this blog while streaming this to notjedi imagine the coincidence
