### ISSUE TITLE
Getting Permission error 13 for chromedriver

### ISSUE THREAD

**Issue by MrudulaGithub** [SergeyPirogov/webdriver_manager#121]
Hi, 
I recently installed webdriver-manager 2.5.2 to work with chromedriver for selenium python in PyCharm. It was working fine for sometime, but now suddenly i am getting the below error- PermissionError: [Errno 13] Permission denied: 'C:\Users\mrudu\.wdm\drivers\chromedriver\83.0.4103.39\win32\chromedriver.exe'
I tried running Pycharm as administrator too, dint work.

**Comment by SergeyPirogov** [comment]
Have you tried to remove that file?

**Comment by MrudulaGithub** [comment]
Remove what file? the chromedriver.exe? No, no changes made

**Comment by SergeyPirogov** [comment]
Try to remove that file C:\Users\mrudu.wdm\drivers\chromedriver\83.0.4103.39\win32\chromedriver.exe

**Comment by SergeyPirogov** [comment]
Also I see some mistake in path. Can you please send me console logs?

**Comment by MrudulaGithub** [comment]
C:\Users\mrudu\PycharmProjects\BDD2\venv\Scripts\python.exe "C:/Users/mrudu/PycharmProjects/BDD2/Selenium try.py"
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip
[WDM] - Unpack archive C:\Users\mrudu\.wdm\drivers\chromedriver\83.0.4103.39\win32\chromedriver.zip
Traceback (most recent call last):
  File "C:/Users/mrudu/PycharmProjects/BDD2/Selenium try.py", line 5, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\mrudu\PycharmProjects\BDD2\venv\lib\site-packages\webdriver_manager\chrome.py", line 29, in install
    driver_path = self.download_driver(self.driver)
  File "C:\Users\mrudu\PycharmProjects\BDD2\venv\lib\site-packages\webdriver_manager\manager.py", line 44, in download_driver
    path = self.__download_and_save_driver_to_cache(driver, driver_version)
  File "C:\Users\mrudu\PycharmProjects\BDD2\venv\lib\site-packages\webdriver_manager\manager.py", line 34, in __download_and_save_driver_to_cache
    driver.get_os_type())
  File "C:\Users\mrudu\PycharmProjects\BDD2\venv\lib\site-packages\webdriver_manager\driver_cache.py", line 63, in save_driver_to_cache
    files = self.__unpack(file_path)
  File "C:\Users\mrudu\PycharmProjects\BDD2\venv\lib\site-packages\webdriver_manager\driver_cache.py", line 114, in __unpack
    return extract_zip(path, to_directory)
  File "C:\Users\mrudu\PycharmProjects\BDD2\venv\lib\site-packages\webdriver_manager\archive.py", line 7, in extract_zip
    archive.extractall(to_directory)
  File "C:\Users\mrudu\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1636, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\mrudu\AppData\Local\Programs\Python\Python37\lib\zipfile.py", line 1690, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\mrudu\\.wdm\\drivers\\chromedriver\\83.0.4103.39\\win32\\chromedriver.exe'

Process finished with exit code 1

> Also I see some mistake in path. Can you please send me console logs?

![WhatsApp Image 2020-05-29 at 8 02 31 AM](https://user-images.githubusercontent.com/63667005/83257654-d0419200-a182-11ea-9007-e9db1d9b9291.jpeg)

**Comment by SergeyPirogov** [comment]
Ok, can you go to this folder 

```
C:\\Users\\mrudu\\.wdm\\drivers\\chromedriver\\83.0.4103.39\\win32\\
```
and show me what files do you have?

**Comment by MrudulaGithub** [comment]
> Try to remove that file C:\Users\mrudu.wdm\drivers\chromedriver\83.0.4103.39\win32\chromedriver.exe

<img width="680" alt="Capture1" src="https://user-images.githubusercontent.com/63667005/83258948-33ccbf00-a185-11ea-9f38-f3861a627cb2.PNG">

**Comment by MrudulaGithub** [comment]
> Ok, can you go to this folder
> 
> ```
> C:\\Users\\mrudu\\.wdm\\drivers\\chromedriver\\83.0.4103.39\\win32\\
> ```
> 
> and show me what files do you have?

<img width="675" alt="Capture2" src="https://user-images.githubusercontent.com/63667005/83259145-86a67680-a185-11ea-8640-efd2d76c0906.PNG">

**Comment by SergeyPirogov** [comment]
So, you have some process that is holding this driver. Close all Chrome drivers, and try to find all processes with name chromedriver.exe

**Comment by MrudulaGithub** [comment]
It worked! Thank you so much.
I am new to coding so learning the basics still

> So, you have some process that is holding this driver. Close all Chrome drivers, and try to find all processes with name chromedriver.exe

**Comment by MrudulaGithub** [comment]
@SergeyPirogov ,Thanks for your immediate replies and help in fixing the issue
