### ISSUE TITLE
DriverCache example

### ISSUE THREAD

**Issue by jacarrasco** [SergeyPirogov/webdriver_manager#124]
Hello,

Thank you for this excellent module. I am using it in my code, but due my constant creation of the selenium driver i am always getting the API rate limit exception. 
So, what i would like is that before downloading the new webdriver, it could find if it already exists locally. If it exists don't do anything, not even query for new version.

Looking into the code I saw the DriverCache option but i don't understand how it works and it is not documented anywhere. Should I use that for the case I mentioned?
https://github.com/SergeyPirogov/webdriver_manager/blob/master/tests/test_driver_cache.py

Do you have any other example on how to use it?

Thank you for this work!

Best Regards,

**Comment by SergeyPirogov** [comment]
Please look at the configuration options in README. https://github.com/SergeyPirogov/webdriver_manager#configuration
You have to pass GH_TOKEN to solve the issue

**Comment by jacarrasco** [comment]
Hi, I thought i mentioned but i didn't. I was using already the GH_TOKEN, but still it has some limits.
So, to my question about : 
"I would like is that before downloading the new webdriver, it could find if it already exists locally. If it exists don't do anything, not even query for new version"
Is it something that DriverCache can do? If so, is there any example?

Thank you,

Best regards

**Comment by SergeyPirogov** [comment]
Which version of the wd manager do you use? Try to update to the latest one, it use driver cache and keeps it valid for 1 day

**Comment by jacarrasco** [comment]
I was using previous version. With latest version it works. Thank you!
