### ISSUE TITLE
Unable to silent WDM log.

### ISSUE THREAD

**Issue by codeinwill** [SergeyPirogov/webdriver_manager#129]
**Attempt: followed the instructions**
`import os
os.environ['WDM_LOG_LEVEL'] = '0'

or via constructor:

ChromeDriverManager("2.26", log_level=0).install()`

**Result: WDM log is still showing when script is executed**:
`[WDM] - Cache is valid for [08/06/2020]
[WDM] - Looking for [chromedriver 83.0.4103.39 win32] driver in cache
[WDM] - Driver found in cache [C:\Users\W\.wdm\drivers\chromedriver\83.0.4103.39\win32\chromedriver.exe]

DevTools listening on ws://127.0.0.1:64762/devtools/browser/1669914b-0411-4abd-82b7-44cdf488a091`

**Comment by SergeyPirogov** [comment]
Fixed by #128
