### ISSUE TITLE
Bad zip error

### ISSUE THREAD

**Issue by d02d33pak** [SergeyPirogov/webdriver_manager#134]
I get the following error while using webdriver manager

[WDM] - Current google-chrome version is 83.0.4103
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - There is no [win32] chromedriver for browser 83.0.4103 in cache
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip
driver loading error
<class 'zipfile.BadZipFile'>
File is not a zip file

**Comment by SergeyPirogov** [comment]
Which version do you use?

**Comment by d02d33pak** [comment]
when I run pip list, this is what I see webdriver-manager 2.5.2
EDIT: if I run pip install webdriver_manager, its installing version 2.5.2 by default
just updated to 3.2.1, will check if the issue persist

**Comment by d02d33pak** [comment]
turns out I'm still getting the error

**Comment by SergeyPirogov** [comment]
Please delete folder $USER_HOME/.wdm and try again

**Comment by d02d33pak** [comment]
I did just that yesterday, and it solved the problem. Thank you. :+1:
