### ISSUE TITLE
JSON Decoder Error

### ISSUE THREAD

**Issue by d02d33pak** [SergeyPirogov/webdriver_manager#135]
Another error that I got - 

[WDM] - Current google-chrome version is 83.0.4103
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - There is no [win32] chromedriver for browser 83.0.4103 in cache
[WDM] - Get LATEST driver version for 83.0.4103
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_win32.zip
driver loading error
<class 'json.decoder.JSONDecodeError'>
Expecting value: line 1 column 1 (char 0)

**Comment by SergeyPirogov** [comment]
Version?

**Comment by d02d33pak** [comment]
when I run `pip list`, this is what I see `webdriver-manager 2.5.2`

**Comment by SergeyPirogov** [comment]
Please delete folder $USER_HOME/.wdm and try again

**Comment by d02d33pak** [comment]
Did exactly that. Not seeing error, any more.
