### ISSUE TITLE
[ValueError]invalid literal for int() with base 10 : INFO

### ISSUE THREAD

**Issue by HrishiKulk** [SergeyPirogov/webdriver_manager#136]
For all the browsers we are getting the error while the webdriver is trying to install the package

Python used - 3.7.4
Webdriver manager used - 3.2.1
chrome version used - Version 83.0.4103.106
edge - Version 83.0.478.54
firefox - 77.0.1

![image](https://user-images.githubusercontent.com/67309368/85372181-19e98680-b54f-11ea-9722-270b77e74d71.png)
![image](https://user-images.githubusercontent.com/67309368/85372247-2ec61a00-b54f-11ea-8f63-3675459652a9.png)
![image](https://user-images.githubusercontent.com/67309368/85372292-41d8ea00-b54f-11ea-971f-746a868ebee4.png)

I think the issue lies in the install method as we are able to get the things as usual without it and its more to do with the INFO log we share in the logger

PFB screenshot which shows the usual EdgeChromiumDriverManager() evaluation in pycharm
![image](https://user-images.githubusercontent.com/67309368/85372507-94b2a180-b54f-11ea-96c6-fe737f71c387.png)

**Comment by SergeyPirogov** [comment]
Don't understand the exact problem.  Could you show an error message or exception?

**Comment by HrishiKulk** [comment]
when the webdriver manager is trying to install the drivers for browsers we are getting exceptions as stated
![image](https://user-images.githubusercontent.com/67309368/85373528-02130200-b551-11ea-9a0b-1847aef97e17.png)

this was working in the previous webdriver_manager releases

**Comment by HrishiKulk** [comment]
while executing the below line of code
![image](https://user-images.githubusercontent.com/67309368/85373645-325aa080-b551-11ea-9b08-db60ea8c04aa.png)

**Comment by SergeyPirogov** [comment]
It's strange because all tests are green

**Comment by SergeyPirogov** [comment]
Please show stack trace

**Comment by HrishiKulk** [comment]
File "C:\Users\Hrishikesh\.virtualenvs\PythonFramework_08_11-9JbOJrql\lib\site-packages\webdriver_manager\logger.py", line 12, in log
    level = int(log_level)
ValueError: invalid literal for int() with base 10: 'INFO'


![image](https://user-images.githubusercontent.com/67309368/85374780-e9a3e700-b552-11ea-91e2-0acdbedab884.png)

**Comment by SergeyPirogov** [comment]
Ok, show me how you set WDM_LOG_LEVEL env var

**Comment by HrishiKulk** [comment]
![image](https://user-images.githubusercontent.com/67309368/85375356-cded1080-b553-11ea-8342-6c43320ce16e.png)

![image](https://user-images.githubusercontent.com/67309368/85375425-ea894880-b553-11ea-8d66-e23ab8d7dc2e.png)

**Comment by SergeyPirogov** [comment]
Ok, is it working without this env var?

**Comment by SergeyPirogov** [comment]
I have a test for this and it's green https://github.com/SergeyPirogov/webdriver_manager/blob/master/tests/test_silent_global_logs.py

**Comment by HrishiKulk** [comment]
this is really strange; i removed the webdriver manager package and reinstalled it again - it worked.
the root cause appears to be the virtual environment for the pip; as it had both 3.1.0 and 3.2.1 present in site packages.

**Comment by HrishiKulk** [comment]
closing the issue - Thanks for the time and attention; cheers
