### ISSUE TITLE
Firefox Developer Edition Error when using webdriver_manager

### ISSUE THREAD

**Issue by theVidVid** [SergeyPirogov/webdriver_manager#137]
**I followed the instructions as if it were Firefox:**
`from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager

driver=webdriver.Chrome(executable_path=GeckoDriverManager().install())
type(driver)
driver.get("https://inventwithpython.com")`

**Received the following error:**

`File "/home/thevidvid/python_work/ATBS_with_Python/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
`

**Comment by SergeyPirogov** [comment]
You have to use ChromeDriverManager for Chrome, Firefox for Firefox
