### ISSUE TITLE
Error when attempting to install chromedriver from within a GitHub Action

### ISSUE THREAD

**Issue by benr-calam** [SergeyPirogov/webdriver_manager#138]
# Problem
In a CI GitHub Action that runs django selenium tests, I am getting this error:

`ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version`.

And this was printed out as well

`ERROR: The system was unable to find the specified registry key or value.`

The job runs on `windows-latest`, uses python 3.8, and fails on this block

```python
    ...
    try:
        from webdriver_manager.chrome import ChromeDriverManager
        executable_path = ChromeDriverManager().install()  # <---
    except ModuleNotFoundError:
        executable_path = 'chromedriver'

    driver = webdriver.Chrome(executable_path)
    ...
```

The tests were not failing previously when I was using webdriver-manager in the same way, and tests run fine on my local machine. Is there something that I am missing? Should I tweak the configuration of `ChromeDriverManager` to install somewhere else? Any help is greatly appreciated.

## pip freeze (tests also fail with versions 3.2.0 and 3.2.1)

```
asana==0.10.0
asgiref==3.2.10
Babel==2.8.0
beautifulsoup4==4.9.1
bleach==3.1.5
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.3
configparser==5.0.0
coverage==5.1
crayons==0.3.1
defusedxml==0.6.0
diff-match-patch==20181111
Django==3.0.7
django-classy-tags==1.0.0
django-debug-toolbar==1.11
django-import-export==2.1.0
django-js-asset==1.2.2
django-mptt==0.11.0
django-nyt==1.1.5
django-phonenumber-field==4.0.0
django-sekizai==1.1.0
et-xmlfile==1.0.1
flake8==3.8.3
idna==2.10
jdcal==1.4.1
keyboard==0.13.5
ldap3==2.7
lxml==4.5.1
Markdown==3.2.2
MarkupPy==1.14
mccabe==0.6.1
numpy==1.19.0
oauthlib==3.1.0
odfpy==1.4.1
openpyxl==3.0.4
packaging==20.4
pandas==1.0.5
phonenumbers==8.12.6
Pillow==7.2.0
psycopg2==2.8.5
pyasn1==0.4.8
pycodestyle==2.6.0
pyflakes==2.2.0
pyparsing==2.4.7
PyPDF2==1.26.0
python-dateutil==2.8.1
python-docx==0.8.10
pytz==2020.1
pywin32==228
PyYAML==5.3.1
regex==2020.6.8
requests==2.24.0
requests-oauthlib==1.3.0
selenium==3.141.0
six==1.15.0
sorl-thumbnail==12.6.3
soupsieve==2.0.1
sqlparse==0.3.1
tablib==2.0.0
urllib3==1.25.9
webdriver-manager==3.1.0
webencodings==0.5.1
wfastcgi==3.0.0
wiki==0.6
xlrd==1.2.0
xlwt==1.3.0
```

**Comment by SergeyPirogov** [comment]
Well, it try to determine browser version, but there is no such reg key. You can either pass version that is required or look to actions setup that is used for driver manager testing

**Comment by benr-calam** [comment]
Apparently the `windows-latest` image in GitHub Actions already comes with chromedriver installed as per [this](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md). So, I just re-worked my code to search for the chromedriver executable first then fall back to `webdriver_manager.chrome.ChromeDriverManager().install()`. I'm still not sure what caused the error I wrote before, but the issue can be closed as far as I'm concerned.

**Comment by SergeyPirogov** [comment]
Ok, good
