### ISSUE TITLE
Github API Rate limit exceeded if get_latest_release_version requested more than 60 times per hour

### ISSUE THREAD

**Issue by StephaneColson** [SergeyPirogov/webdriver_manager#139]
I have 78 tests that work fine with `Chrome` but not with `Firefox` with `webdriver_manager` version 3.2.1. 

The problem is that requesting the latest version with this [url](https://api.github.com/repos/mozilla/geckodriver/releases/latest) is blocked if done more than 60 times in less than 1 hour: see [this github page](https://developer.github.com/v3/#rate-limiting).

You can simulate this by requesting `curl -i https://api.github.com/users/octocat` more than 60 times with the same IP and check `X-Ratelimit-Limit` and `X-Ratelimit-Remaining`.

The detailed error returned by `webdriver_manager` since test n°60 is the following

```
../../.env/lib/python3.7/site-packages/webdriver_manager/firefox.py:28: in install
    return self._get_driver_path(self.driver)
../../.env/lib/python3.7/site-packages/webdriver_manager/manager.py:22: in _get_driver_path
    driver_version = driver.get_version()
../../.env/lib/python3.7/site-packages/webdriver_manager/driver.py:40: in get_version
    return self.get_latest_release_version()
../../.env/lib/python3.7/site-packages/webdriver_manager/driver.py:89: in get_latest_release_version
    validate_response(resp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

resp = <Response [403]>

    def validate_response(resp):
        if resp.status_code == 404:
            raise ValueError("There is no such driver by url {}".format(resp.url))
        elif resp.status_code != 200:
>           raise ValueError(resp.json())
E           ValueError: {'message': "API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}

../../.env/lib/python3.7/site-packages/webdriver_manager/utils.py:81: ValueError
```

Thanks for your help!

**Comment by SergeyPirogov** [comment]
@StephaneColson Ok, it's expected. It's on the side of GitHub. How we can fix this?
How do you run your tests? I guess you spin fresh env every time (e.g Github actions?)

**Comment by StephaneColson** [comment]
Thanks @SergeyPirogov for the answer. I need to check how I'm using Pylenium and how this one is using webdriver_manager. I don't know yet what could be wrong and how to fix this because yes, each test launched is using a fresh clean environment!
