### ISSUE TITLE
Cannot install Chrome driver

### ISSUE THREAD

**Issue by kaggrwal** [SergeyPirogov/webdriver_manager#141]
I'm getting the following exception:

raised unexpected: ValueError('Could not get version for Chrome with this command: google-chrome --version')

**Comment by SergeyPirogov** [comment]
Which system do you use?

сб, 18 июл. 2020 г., 14:31 Kumar Aggarrwal <notifications@github.com>:

**Comment by kaggrwal** [comment]
It is Ubuntu 20.04.

**Comment by SergeyPirogov** [comment]
Do you have google chrome installed?
