### ISSUE TITLE
does a standalone server updater make sense?

### ISSUE THREAD

**Issue by zaphodikus** [SergeyPirogov/webdriver_manager#147]
Does it make sense to also add an updater class for the java standalone selenium server jar? I mean does it make architectural sense to add it into this module? I'd like to give it a smash if it is realistic to and maybe drop some cash into your "jar", I assume you accept once-off anonymous donations.

Thanks.

**Comment by SergeyPirogov** [comment]
It’s a python module! We don’t have any jars

**Comment by zaphodikus** [comment]
Um, that is totally not what I meant at any point. I'm taking that as a no though. 

1. I'm trying to automate the remote selenium server problem domain. I plan to fork and add a "driver" called "seleniumserver" which will download the latest selenium server exe or jar and drop it into the driver cache folders. This looks like it's as simple as cloning one of the "drivers" and instead of pointing to the zip or binary for that browser engine, point to the selenium download archives. This would let me just install python on any computer, and let the module bootstrap the selenium 3 remote server (java for MAC-OS or the binary for Windows) into the cache and let me start the remote server up using Python remoting and then just connect to it, knowing that the server is always the latest release.

2. You have a Patreon subscription, but I really wanted to provide a once-off paypal or koffi type donation. Which is what I was meaning when I said drop cash into a jar.

**Comment by SergeyPirogov** [comment]
I have donate system https://donatesystem.io/donate/automation_remarks
