### ISSUE TITLE
Option to disable first line print

### ISSUE THREAD

**Issue by kjgoodrick** [SergeyPirogov/webdriver_manager#148]
It would be nice if there were an option to disable the first line print in the log function. It is currently possible to disable logging by setting the level, but disabling the print statement is impossible (or rather, requires redefining the log function when importing).

I'd be happy to submit a pull request to fix this, but I wanted to check and see if you had a preference on how it is done before getting started.

**Comment by SergeyPirogov** [comment]
Hello, feel free to open a PR for this
