### ISSUE TITLE
WebDriverException: Message: 'msedgedriver' executable may have wrong permissions

### ISSUE THREAD

**Issue by rmeyer1** [SergeyPirogov/webdriver_manager#149]
Hello - 

Currently, I am using webdriver_manager to deploy my different browser variants (it has been great) but recently I have run into a strange issue in which I'm hoping someone could give me some input.   When I use webdriver_manager to download edge chromium I get a hook error stating  'msedgedriver' executable may have the wrong permissions.  In doing some further research the issue appeared to be that I needed to add msedgedriver to my python path.  I did this by using a symbolic link from the executable directory location to my /usr/local/bin directory.  This did not solve my problem.  Has anyone else experienced this?  How did you solve it?  I have not experienced this problem with any other drivers... 

def get_driver(driver_type):

        def which driver to select
        :param locator_type: str set by def which implement on SeleniumDriver class
        :return: tag type or False

    driver_type = driver_type.lower()
    if driver_type == 'chrome':
        abs_path = get_project_root()
        downloads_path = os.path.join(abs_path, 'downloads')

        options = Options()
        options.add_argument("--no-sandbox")
        options.add_argument("--disable-dev-shm-usage")
        prefs = {"download.default_directory": downloads_path}
        options.add_experimental_option("prefs", prefs)

        if 'headless' in os.environ and os.environ['headless'] == '1':
            options.headless = True
            options.add_argument("--window-size=1920,1080")

        return webdriver.Chrome(ChromeDriverManager().install(), chrome_options=options)
    elif driver_type == 'firefox':
        cap = DesiredCapabilities().FIREFOX
        cap["marionette"] = True

        firefox_options = FOptions()
        if 'headless' in os.environ and os.environ['headless'] == '1':
            firefox_options.headless = True
            os.environ['MOZ_HEADLESS_WIDTH'] = '1920'
            os.environ['MOZ_HEADLESS_HEIGHT'] = '1080'

        return webdriver.Firefox(capabilities=cap, executable_path=GeckoDriverManager().install(), firefox_options=firefox_options)
    elif driver_type == 'edge':
        # if 'headless' in os.environ and os.environ['headless'] == '1':
        #     pass

        return webdriver.Edge(EdgeChromiumDriverManager().install())
    else:
        print("Locator type" + driver_type + " not correct/supported")
    return False`

`def before_scenario(context, scenario):
    logging.info("RUNNING: " + scenario.name)
    print("Browser Test starting.\n")
    print("Setting driver version and options.  ")

    context.driver = get_driver(os.environ.get('driver'))

    if os.environ.get('driver') == 'chrome':
        print("Currently using Chromedriver Version " + context.driver.capabilities['chrome']['chromedriverVersion'])

    context.driver.maximize_window()`

**Setting driver version and options.  
[WDM] - Looking for [edgedriver 85.0.564.44 mac64] driver in cache 
[WDM] - File found in cache by path [/Users/robmeyer/.wdm/drivers/edgedriver/85.0.564.44/mac64/msedgedriver]
[WDM] - Looking for [edgedriver 85.0.564.44 mac64] driver in cache 
[WDM] - File found in cache by path [/Users/robmeyer/.wdm/drivers/edgedriver/85.0.564.44/mac64/msedgedriver]
HOOK-ERROR in before_scenario: WebDriverException: Message: 'msedgedriver' executable may have wrong permissions. Please download from http://go.microsoft.com/fwlink/?LinkId=619687**

**Comment by SergeyPirogov** [comment]
Can't reproduce
