### ISSUE TITLE
Trying to get wrong edge driver

### ISSUE THREAD

**Issue by Jediguy** [SergeyPirogov/webdriver_manager#151]
Ran into an annoying bug while trying to get the edge driver. Might be easy to resolve. If I get the chance I might try to resolve it. The error is: 
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/85.0.564.60/edgedriver_win64.zip

The current windows build of edge is 85.0.564.51. The driver it's trying to grab is .60 which is mac only. Maybe it's not worth resolving as this could be a one-time problem since normally the versions are the same across os's. Thought it was worth bringing up just in case. 

edit: current drivers can be found here and you can see that .60 only has a mac version
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by dasshark** [comment]
This appears to be related to a change in hosting location for the driver files.

https://msedgedriver.azureedge.net/85.0.564.60/edgedriver_win64.zip  
should be
https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/85.0.564.60/edgedriver_mac64.zip

I'm not sure why the module isn't grabbing the <url> from the page though, it is correctly updated

**Comment by SergeyPirogov** [comment]
Can't reporoduce
