### ISSUE TITLE
GeckoDriver installation error

### ISSUE THREAD

**Issue by mal-mel** [SergeyPirogov/webdriver_manager#152]
`ValueError: {'message': "API rate limit exceeded for ... (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}`

API rate limit for installation GeckoDriver.

`self.__driver_manager = GeckoDriverManager(path=settings.MANAGER_DRIVER_PATH,
                                                       log_level=logging.CRITICAL)`
 `driver_executable_path = self.__driver_manager.install()`

**Comment by wblondel** [comment]
https://github.com/SergeyPirogov/webdriver_manager#configuration
