### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by janscas** [SergeyPirogov/webdriver_manager#154]
The docs specify this:

`pip install webdriver_manager`

But I found that in pypi the package is called "webdriver-manager"

So it should be:

`pip install webdriver-manager`

**Comment by SergeyPirogov** [comment]
Did you try both variants?

**Comment by janscas** [comment]
I didn't try the command line but using pycharm UI it didn't find `webdriver-manager` but it did find `webdriver-manager`.

![image](https://user-images.githubusercontent.com/7224106/95979863-95cc4f00-0e1c-11eb-99c7-1f5d3cedc0f6.png)
![image](https://user-images.githubusercontent.com/7224106/95979919-ada3d300-0e1c-11eb-8b8a-3e7322096725.png)

**Comment by lynchdean** [comment]
I had the same problem, using 'pip install webdriver_manager' doesn't work (Both using cli and via Pycharm's manager), but 'pip install webdriver-manager' did. I still have to import with webdriver_manager in the python file itself.

**Comment by SergeyPirogov** [comment]
Fixed
