### ISSUE TITLE
Support Brave

### ISSUE THREAD

**Issue by MangoScango** [SergeyPirogov/webdriver_manager#155]
Work's IT has decided Chrome is old hat, and Brave is the new hotness, and has begun uninstalling Chrome in favor of it. Brave works just fine with Chromedriver, but webdriver_manager doesn't seem to support support detecting the installed version of Brave. Can this be added?

**Comment by SergeyPirogov** [comment]
What is Brave?

**Comment by MangoScango** [comment]
A privacy focused fork of Chromium:

https://brave.com/

**Comment by SergeyPirogov** [comment]
Not going to support this

**Comment by MangoScango** [comment]
In the event that anyone else has the need for this functionality in Brave, and ends up here, this is what I ended up doing to achieve similar functionality:

https://gist.github.com/MangoScango/48a92cc989c888347fcf7e0aff2f5cd1

Just looks up the currently installed version of Brave, and downloads the latest chromedriver for that major version of Chromium, if one does not already exist in a prespecified directory. Chromedriver only cares if the major version matches, so it should be fine.

**Comment by SergeyPirogov** [comment]
Feel free to provide a PR for this

**Comment by MangoScango** [comment]
My implementation is a little too rudimentary for that right now, but I'll consider reworking it to match this module in the future.
