### ISSUE TITLE
Setting "os.environ['WDM_LOCAL'] = '1'" does not override default binaries location

### ISSUE THREAD

**Issue by noopurmath3** [SergeyPirogov/webdriver_manager#157]
I am not able to update the location where the driver binaries are saved. I tried doing a "os.environ['WDM_LOCAL'] = '1'" as per the README. That does set the value as expected in os.environ, but, looks like the value of WDM_LOCAL  is not being considered.
When I execute the tests the driver is again installed at home/<user>/.wdm/<driver_path>. It should be installed at <project_root>/wdm/<driverpath> instead

**Comment by SergeyPirogov** [comment]
Hello, could you please provide a snippet of code that proves this?

**Comment by SergeyPirogov** [comment]
Fixed in v3.3.0
