### ISSUE TITLE
Unable to launch browser after adding chrome option

### ISSUE THREAD

**Issue by hubofjon** [SergeyPirogov/webdriver_manager#159]
Thanks for the package.  I tried to use
" driver = webdriver.Chrome(ChromeDriverManager().install(), options=options) but unable to launch browser. (working if without options)

below options working fine with specified location:
from selenium.webdriver.chrome.options import Options
options=Options()
options.add_argument("--start-maximized")  #full screen
options.headless = True
driver=webdriver.Chrome(executable_path= path_driver, options=options)

thanks

**Comment by SergeyPirogov** [comment]
driver=webdriver.Chrome(executable_path= ChromeDriverManager().install(), options=options)
