### ISSUE TITLE
EdgeChromium URL is not right

### ISSUE THREAD

**Issue by fakeid30** [SergeyPirogov/webdriver_manager#162]
In Linux, when using Microsoft Edge I am getting this : 

`
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/87.0.664.47/edgedriver_linux64.zip`

I think the URL needs to be updated.

**Comment by SergeyPirogov** [comment]
Can't reproduce

**Comment by rsavu98** [comment]
Hi @fakeid30, did you find a workaround for that? I'm facing the same issue.

**Comment by fakeid30** [comment]
@rsavu98 the solution is not to use the software. we re-architectured our product so that we don't need it.

**Comment by aleksandr-kotlyar** [comment]
EdgeDriver `87.0.664.47` was not shipped for linux by Microsoft. And that's not webdriver_manager's fault.

But you can solve your problem with webdriver_manager by manually tell it what the link to use to download webdriver from.
For example: `87.0.664.47` version of Edge Browser may be compatible with one of these existing EdgeDrivers for linux:
```
https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/87.0.664.8/edgedriver_linux64.zip
https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/88.0.673.0/edgedriver_linux64.zip
```
Code example:
```python3
def test_edge_manager_with_selenium():
    driver_path = EdgeChromiumDriverManager(
        os_type='linux',
        latest_release_url='https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver/87.0.664.8/edgedriver_linux64.zip'
    ).install()
    driver = webdriver.Edge(executable_path=driver_path)
    driver.get("http://automation-remarks.com")
    driver.quit()
```
By the way

I think we can make webdriver_manager better to find webdrivers even in this situation. Here are my suggested solutions:

Solution # 1
- use the major version of Edge Browser `"87".0.664.47` and search for the maximum/latest full version of EdgeDriver for os_type

Solution # 2
- use the version of browser except minor version after last dot  `"87.0.664".47` and find edge driver with higher minor version

@rsavu98 @fakeid30  fyi
