### ISSUE TITLE
Using the Webdriver Manager in DEVOPS

### ISSUE THREAD

**Issue by AnithaSyed** [SergeyPirogov/webdriver_manager#164]
Hi,
I like this library and it helping me so much so that I can share y project to others and they can use this irresespective of the brower version.

Now I am trying to use my project in Jenkins as a Build jobs to use it automatically at periods. But this library not working there. Please look into this and help me.

Error in Jenkins COnsole Output
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "Gen_Cov_down.py", line 42, in <module>
  File "webdriver_manager\chrome.py", line 23, in __init__
  File "webdriver_manager\driver.py", line 54, in __init__
  File "webdriver_manager\utils.py", line 142, in chrome_version
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
[2192] Failed to execute script Gen_Cov_down

wait while information is gathering

**Comment by SergeyPirogov** [comment]
Please check that chrome is installed

**Comment by AnithaSyed** [comment]
Are you asking about the browser?
If it is browser is already there
