### ISSUE TITLE
ModuleNotFoundError: No module named 'webdriver_manager' error even after installing webdrivermanager

### ISSUE THREAD

**Issue by mobassir94** [SergeyPirogov/webdriver_manager#165]
i am using anaconda in windows 10 and facing this problem today : https://stackoverflow.com/questions/63421086/modulenotfounderror-no-module-named-webdriver-manager-error-even-after-instal

i tried this command "pip install webdriver_manager"

it installs webdriver properly, but when i do : **from webdriver_manager.chrome import ChromeDriverManager**

i face this error : 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-b2306374a619> in <module>()
      1 from selenium import webdriver
----> 2 from webdriver_manager.chrome import ChromeDriverManager

ModuleNotFoundError: No module named 'webdriver_manager'
```

**Comment by SergeyPirogov** [comment]
Try pip install webdriver-manager

**Comment by mobassir94** [comment]
yeah,tried that too,same error,also tried to install previous versions but same error

**Comment by mobassir94** [comment]
installed it from anaconda (didn't work)
installed it from cmd and it works now
