### ISSUE TITLE
Add raise exception for GeckoDriverManager().install() when there is no Firefox installed.

### ISSUE THREAD

**Issue by KeirLoire** [SergeyPirogov/webdriver_manager#166]
This is more like a feature request than an issue.

We would like to have a raise exception for `GeckoDriverManager().install()` when there is no Firefox installed. Just like in `ChromeDriverManager().install()`

We're using this to automate browser detection for selenium tests in robotframework like this:
```python
class AutodetectBrowser(object):
    def __init__(self):
        self.browser = None
        self.driver = None

    def detect_browser(self):
        self.__detect_googlechrome()
        self.__detect_firefox()

        if self.browser:
            driver_path = os.path.dirname(self.driver)
            os.environ['PATH'] += f';{driver_path}'
            BuiltIn().set_global_variable('${BROWSER}', self.browser)
        else:
            BuiltIn().fail('No supported browser found.')

    def __detect_googlechrome(self):
        if not self.browser:
            try:
                self.driver = ChromeDriverManager().install()
            except:
                pass
            if self.driver:
                self.browser = 'googlechrome'

    def __detect_firefox(self):
        if not self.browser:
            try:
                self.driver = GeckoDriverManager().install()
            except:
                pass
            if self.driver:
                self.browser = 'firefox'
```
For now, we are using `os.path.exists()` to detect specific browser.

Same for `OperaDriverManager().install()` and `IEDriverManager().install()`

**Comment by aleksandr-kotlyar** [comment]
Hi @KeirLoire! I just saw your issue, seems I have already done this in [PR 184](https://github.com/SergeyPirogov/webdriver_manager/pull/184) which was merged yesterday. But after read your feature request i have noticed a typo in raising message and fixed it in [PR 186](https://github.com/SergeyPirogov/webdriver_manager/pull/186). 

I think that soon will come the new version with firefox logs and exception if browser was not found.
