### ISSUE TITLE
Error while using the Webdriver manager in Jenkins

### ISSUE THREAD

**Issue by AnithaSyed** [SergeyPirogov/webdriver_manager#168]
Hi,
I like this library and it helping me so much so that I can share y project to others and they can use this irresespective of the brower version.

Now I am trying to use my project in Jenkins as a Build jobs to use it automatically at periods. But this library not working there. Please look into this and help me.

Error in Jenkins COnsole Output
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
File "Gen_Cov_down.py", line 42, in
File "webdriver_manager\chrome.py", line 23, in init
File "webdriver_manager\driver.py", line 54, in init
File "webdriver_manager\utils.py", line 142, in chrome_version
ValueError: Could not get version for Chrome with this command: reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version
[2192] Failed to execute script Gen_Cov_down

wait while information is gathering

And I have the chrome browser and the code worked while I tried in the traditionaal way when I placed the same chrome version driver in folder

**Comment by kacperkonicki** [comment]
Same issue here.
I will try to create a fork for that with following command instead:
`(Get-Item "C:\Program Files\Google\Chrome\Application\chrome.exe").VersionInfo`

**Comment by mslezaksii** [comment]
@SergeyPirogov  I have the same issue in TeamCity. Do you know why?

**Comment by SergeyPirogov** [comment]
Have no idea
