### ISSUE TITLE
Unable to run in Docker container: ValueError: Could not get version for Chrome

### ISSUE THREAD

**Issue by lukapril** [SergeyPirogov/webdriver_manager#173]
I'm able to use this and run my pytest locally on my machine (tried both macOS and Windows with fresh pull from repo and install from requirements.txt file), however when I try to run this in a Docker container, it failed to get the Chrome version. My docker container is a simple image of Python3 and I've confirmed that I have webdriver-manager 3.3.0 and selenium 3.141.0 installed in the container.

I'm pretty new to pytest and docker, any idea or pointers on why it works fine on a local machine and not in the docker container? 

**My test.py:**
```
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.utils import ChromeType

class TestDriver:
    def test_simple_driver(self):
        driver = webdriver.Chrome(ChromeDriverManager(chrome_type=ChromeType.GOOGLE).install())
        driver.get('http://www.google.com')
```

**My requirements.txt**
```
attrs==20.3.0
certifi==2020.12.5
chardet==4.0.0
colorama==0.4.4
configparser==5.0.2
crayons==0.4.0
idna==2.10
iniconfig==1.1.1
packaging==20.9
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
pytest==6.2.3
requests==2.25.1
selenium==3.141.0
toml==0.10.2
urllib3==1.26.4
webdriver-manager==3.3.0
```

**Error when run in the docker container:**
/usr/local/lib/python3.9/site-packages/webdriver_manager/chrome.py:25: in __init__
    self.driver = ChromeDriver(name=name,
/usr/local/lib/python3.9/site-packages/webdriver_manager/driver.py:54: in __init__
    self.browser_version = chrome_version(chrome_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

browser_type = 'google-chrome'

    def chrome_version(browser_type=ChromeType.GOOGLE):
        pattern = r'\d+\.\d+\.\d+'

        cmd_mapping = {
            ChromeType.GOOGLE: {
                OSType.LINUX: 'google-chrome --version || google-chrome-stable --version',
                OSType.MAC: r'/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version',
                OSType.WIN: r'reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version'
            },
            ChromeType.CHROMIUM: {
                OSType.LINUX: 'chromium --version || chromium-browser --version',
                OSType.MAC: r'/Applications/Chromium.app/Contents/MacOS/Chromium --version',
                OSType.WIN: r'reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version'
            },
            ChromeType.MSEDGE: {
                OSType.MAC: r'/Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge --version',
                OSType.WIN: r'reg query "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge\BLBeacon" /v version',
            }
        }

        cmd = cmd_mapping[browser_type][os_name()]
        stdout = os.popen(cmd).read()
        version = re.search(pattern, stdout)
        if not version:
>           raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
E           ValueError: Could not get version for Chrome with this command: google-chrome --version || google-chrome-stable --version

/usr/local/lib/python3.9/site-packages/webdriver_manager/utils.py:142: ValueError

**Comment by scousens** [comment]
@lukapril is chrome installed in your python3 container?
We start with an ubuntu container and install chrome and python among other things to build our image.

**Comment by SergeyPirogov** [comment]
Install chrome first

**Comment by lukapril** [comment]
Thanks @scousens and @SergeyPirogov I installed Chrome to my container and it's working fine now.
