### ISSUE TITLE
geckodriver supported on M1 chip

### ISSUE THREAD

**Issue by dhoanglong91** [SergeyPirogov/webdriver_manager#174]
Starting from version 0.29.1, geckodriver supported M1 chip so there will be 2 versions of geckodriver on MacOS. If a Mac running Intel chip, M1 geckodriver is downloaded and make the test fail with below error:
**[Errno 86] Bad CPU type in executable**

**Comment by SergeyPirogov** [comment]
@dhoanglong91 Thank you, will be happy to see a PR for this

**Comment by jhawgs** [comment]
Hey, @dhoanglong91, try the fix at #178. It worked for me.

**Comment by SergeyPirogov** [comment]
fixed in 3.4.0
