### ISSUE TITLE
Mute linux sh cmd errors

### ISSUE THREAD

**Issue by Quron** [SergeyPirogov/webdriver_manager#182]
Hello!

I suggest to mute errors for Linux, e.g,
`OSType.LINUX: 'chromium --version || chromium-browser --version'`
change to
` OSType.LINUX: 'chromium --version 2>/dev/null || chromium-browser --version 2>/dev/null'`

**Comment by SergeyPirogov** [comment]
@Quron but how to get info? we are receiving browser version this way

**Comment by Quron** [comment]
@SergeyPirogov I check this, `2>/dev/null` hide only this msgs

```
/bin/sh: 1: google-chrome: not found
/bin/sh: 1: google-chrome-stable: not found
/bin/sh: 1: chromium: not found
```

stdout messages like this `Current chromium version is 90.0.4430` show normally.

**Comment by SergeyPirogov** [comment]
Ok, please create a PR for this

**Comment by Quron** [comment]
@SergeyPirogov Hi, pr is done #190
