### ISSUE TITLE
Some issue with the webdriver manager in some browsers

### ISSUE THREAD

**Issue by anjari** [SergeyPirogov/webdriver_manager#189]
I found some issue with the Webdriver Manager in some browsers.

I'm using OS Windows 7 64 bit.

1) Chrome Driver

```
driver = webdriver.Chrome(ChromeDriverManager().install())
```

When run, the message that's shown in console:

```
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_win32.zip
```

I'm using bitdefender antivirus, sometimes it will report the driver file link as malware: "Infected web resource http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_win32.zip". I'm not sure if it's false positive or not.

2) Firefox Driver

```
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())
```

I have firefox installed along with palemoon and waterfox classic browsers in my machine. The waterfox classic is the default browser.

When I run the code, it launches palemoon browser instead. At the code below there is code `driver.get(<some url>)`. But the palemoon browser just starts with blank adddress and doesn't execute the url from the `driver.get()`. Eventually TimeoutException will occur:

```
selenium.common.exceptions.TimeoutException: Message: No connection could be made because the target machine actively refused it. (os error 10061)
```

I'm not sure what happened here, maybe the webdriver mistook the palemoon binary as firefox? Perhaps this issue can be solved by specifying the firefox binary folder location manually in webdriver? If so, how to do this?

3) Edge Driver

```
driver = webdriver.Edge(EdgeChromiumDriverManager().install())
```

No issue on running the code above, but when the Edge browser launches, it will automatically add Edge browser shortcut in the taskbar which is pretty annoying that I have to remove it everytime I run the code.

I wonder if there is a way to add browser launch option to disable the creation of taskbar shortcut?

**Comment by SergeyPirogov** [comment]
@anjari those questions should be addressed to Selenium, wd manager is not responsible for this
