### ISSUE TITLE
Updating geckodriver under Windows fails

### ISSUE THREAD

**Issue by janringas** [SergeyPirogov/webdriver_manager#191]
Today I noticed that updating my geckodriver was failing, when running the following commands in python:
`from webdriver_manager.firefox import GeckoDriverManager`
`geckodriver = GeckoDriverManager().install()`

**Output was:**
> ====== WebDriver manager ======
> ".'(Default)').VersionInfo.ProductVersion" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python38\lib\site-packages\webdriver_manager\firefox.py", line 22, in __init__
>     self.driver = GeckoDriver(version=version,
>   File "C:\Python38\lib\site-packages\webdriver_manager\driver.py", line 83, in __init__
>     self.browser_version = firefox_version()
>   File "C:\Python38\lib\site-packages\webdriver_manager\utils.py", line 165, in firefox_version
>     raise ValueError(f'Could not get version for Firefox with this command: {cmd}')
> ValueError: Could not get version for Firefox with this command: (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion

The first line, saying that part of the statement (coming from utils.py) couldn't be parsed syntactically, led me to experimenting a bit and I managed to get the same by running `(Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion` inside of a native Windows cmd.exe - but not, if run in a powershell.exe.

**Workaround/fix:**
I then was able to use the above python code again after changing line #155 in utils.py 
**...from:**
`        OSType.WIN: r"(Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion"`

**...to:** 
`        OSType.WIN: r"Powershell (Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion"`

Is this something you might incorporate in one of the coming releases? As of now I need to maintain my own copy of utils.py containing the fix and copy it into my Python installation folder each time I've run `pip install -U webdriver-manager`.

**Comment by SergeyPirogov** [comment]
Open a pr for this

**Comment by janringas** [comment]
> Open a pr for this

Done (see https://github.com/SergeyPirogov/webdriver_manager/pull/192 - I hope I did this correctly?)

**Comment by Chrrxs** [comment]
Experienced the same issue, the workaround provided here worked for me aswell.

**Comment by AmirYa412** [comment]
@SergeyPirogov This is an awesome and I just want to thank you for sharing this.
I can confirm I get the same error when trying to run
`geckodriver = GeckoDriverManager().install()`

**Comment by SergeyPirogov** [comment]
The fix was merged. See #192

**Comment by aleksandr-kotlyar** [comment]
Latest release was on 17 may 3.4.2 after the merge. Should be fixed already.
Can be closed?
