### ISSUE TITLE
Silent install process

### ISSUE THREAD

**Issue by DukeNgn** [SergeyPirogov/webdriver_manager#196]
When calling `install()`, the following message is printed to the terminal:

```
====== WebDriver manager ======
Current google-chrome version is 88.0.4324
Get LATEST driver version for 88.0.4324
```

I want to silent this kind of log.

I tried `chrome_driver = ChromeDriverManager(log_level=0).install()`, but it doesn't work, what should I do? 

Thanks!

OS: MacOS Catalina

**Comment by jiaulislam** [comment]
you can use the below Options Class argument ...

options.add_argument("--log-level=3")
os.environ['WDM_LOG_LEVEL'] = '0' 
```
def chrome_driver():
        options = Options()
        options.add_argument("--log-level=3")  # disable Info/Error/Warning in Chrome Driver
        os.environ['WDM_LOG_LEVEL'] = '0'  # Disable the logging of ChromeDriverManager()
        return browser: WebDriver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
```

**Comment by jiaulislam** [comment]
> When calling `install()`, the following message is printed to the terminal:
> 
> ```
> ====== WebDriver manager ======
> Current google-chrome version is 88.0.4324
> Get LATEST driver version for 88.0.4324
> ```
> 
> I want to silent this kind of log.
> 
> I tried `chrome_driver = ChromeDriverManager(log_level=0).install()`, but it doesn't work, what should I do?
> 
> Thanks!
> 
> OS: MacOS Catalina

you can use the below Options Class argument ...

options.add_argument("--log-level=3")
os.environ['WDM_LOG_LEVEL'] = '0'
```
def chrome_driver():
        options = Options()
        options.add_argument("--log-level=3")  # disable Info/Error/Warning in Chrome Driver
        os.environ['WDM_LOG_LEVEL'] = '0'  # Disable the logging of ChromeDriverManager()
        return browser: WebDriver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
```

**Comment by DukeNgn** [comment]
> os.environ['WDM_LOG_LEVEL'] = '0'

@jiaulislam Thanks! This solves the issue
