### ISSUE TITLE
Unable to download the drivers on a network behind Proxy

### ISSUE THREAD

**Issue by sathish804** [SergeyPirogov/webdriver_manager#197]
Dear Developer,

Good day!!

My work network uses a proxy to handle the requests. When I am trying to download the drivers using driver manager I am getting connection error. I tried to configure proxy in my PyCharm setup but it didnt helped.

Could you please advise me how can I setup proxy for the webdriver manager to download the firefox and chrome drivers.

> Current firefox version is 88.0
Get LATEST driver version for 88.0
Traceback (most recent call last):
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CFE70372E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CFE70372E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sathish\PycharmProjects\PyAutoFramework\main.py", line 16, in <module>
    gdd.install()
  File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\firefox.py", line 31, in install
    return self._get_driver_path(self.driver)
  File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
  File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 43, in get_version
    return self.get_latest_release_version()
  File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 91, in get_latest_release_version
    resp = requests.get(url=self.latest_release_url,
  File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CFE70372E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

Process finished with exit code 1

Thanks and Regards,
Sathish.

**Comment by jiaulislam** [comment]
> Dear Developer,
> 
> Good day!!
> 
> My work network uses a proxy to handle the requests. When I am trying to download the drivers using driver manager I am getting connection error. I tried to configure proxy in my PyCharm setup but it didnt helped.
> 
> Could you please advise me how can I setup proxy for the webdriver manager to download the firefox and chrome drivers.
> 
> > Current firefox version is 88.0
> > Get LATEST driver version for 88.0
> > Traceback (most recent call last):
> > File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
> > conn = connection.create_connection(
> > File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
> > raise err
> > File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
> > sock.connect(sa)
> > TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
> httplib_response = self._make_request(
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
> self._validate_conn(conn)
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
> conn.connect()
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connection.py", line 353, in connect
> conn = self._new_conn()
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
> raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001CFE70372E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
> resp = conn.urlopen(
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
> retries = retries.increment(
> File "C:\Users\sathish\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CFE70372E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:\Users\sathish\PycharmProjects\PyAutoFramework\main.py", line 16, in
> gdd.install()
> File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\firefox.py", line 31, in install
> return self._get_driver_path(self.driver)
> File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
> driver_version = driver.get_version()
> File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 43, in get_version
> return self.get_latest_release_version()
> File "C:\Users\sathish\Python\Python39\lib\site-packages\webdriver_manager\driver.py", line 91, in get_latest_release_version
> resp = requests.get(url=self.latest_release_url,
> File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
> return request('get', url, params=params, **kwargs)
> File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
> return session.request(method=method, url=url, **kwargs)
> File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "C:\Users\sathish\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/mozilla/geckodriver/releases/latest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CFE70372E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
> 
> Process finished with exit code 1
> 
> Thanks and Regards,
> Sathish.

Hi @sathish804 , I believe it's not related to webdriver_manager because in the exception it's saying `Failed to establish a new connection` which means your proxy is blocking the website to download. Are you sure you are able to download manually webdriver while you are on proxy ?

**Comment by SergeyPirogov** [comment]
We use requests to download driver binaries. It can use proxy. Try to google python requests proxy. Thank you
