### ISSUE TITLE
geckodriver for ARM64 linux

### ISSUE THREAD

**Issue by deadly-platypus** [SergeyPirogov/webdriver_manager#200]
On a Raspberry Pi 4, running the Python function `GeckoDriverManager().install()` retrieves the x86_64 geckodriver binary. But what is needed is an ARM64 binary.  Looking at the geckodriver release page, there isn't a specific ARM64 release, but it looks like Ubuntu has one in the `firefox-geckodriver` package.

**Comment by aleksandr-kotlyar** [comment]
@deadly-platypus ty for such a detailed report!
`webdriver-manager` currently downloads geckodriver from official releases on github https://github.com/mozilla/geckodriver/releases 

If you know the repo where we can select respectively latest geckodriver for ARM64 Raspberry Pi4 - please show the source with links,
I currently think that it's just enthusiasts who built firefox-geckodriver for ARM64 in ubuntu repo.

**Comment by aleksandr-kotlyar** [comment]
May be webdriver-manager needs a functional to build geckodriver for ARM from sources - just few commands. May be.

**Comment by aleksandr-kotlyar** [comment]
@deadly-platypus For now geckodriver for ARM is self-serving build which can't be implemented into webdriver-manager
https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html
When official releases for ARM64 will become available - we can return to this issue.

**Comment by deadly-platypus** [comment]
That's unfortunate, but I understand.  I looked into the AUR and nothing immediately came to mind.

**Comment by aleksandr-kotlyar** [comment]
Let's rename issue to 'geckodriver for ARM64 linux'

**Comment by aleksandr-kotlyar** [comment]
For now you should build your own geckodriver by this instruction for ARM64: https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html
