### ISSUE TITLE
Supress console outputs

### ISSUE THREAD

**Issue by drldavis** [SergeyPirogov/webdriver_manager#201]
There needs to be a way to suppress these messages:

`====== WebDriver manager ======
Current google-chrome version is 91.0.4472
Get LATEST driver version for 91.0.4472
Driver [/Users/dallin/.wdm/drivers/chromedriver/mac64/91.0.4472.19/chromedriver] found in cache`

**Comment by leao-nardo** [comment]
the 3 first lines yeah ,can go .
but the 4 is actualy useful for debug

**Comment by dariopnc** [comment]
This should be fixed by #170, merged to the master branch. At least it should give you a way to completely disable the logging by controlling directly the logger. This version hasn't yet been tagged to relaease and published to pip
