### ISSUE TITLE
optimization -very simple , i tested

### ISSUE THREAD

**Issue by leao-nardo** [SergeyPirogov/webdriver_manager#202]
im running this lib to test and comparing the running time using it. i know i may be putting to much unedited data here but well

data i generated in my tests , measuring only this "driver = webd... " line measured many and many more times consistently , the hit in performance by using the webdriver_manager , may look small 1sec but its a hit every time its run and in less powerful pcs and slower net those times can be way greater and the mod i found after many attemps is way better it takes no hit in perf. 

```

# driver = webdriver.Firefox(options=options, executable_path=GeckoDriverManager().install()) #headless
# Finished 'func' in 5.352 secs
# Finished 'func' in 5.425 secs
# puttnig the exe path - not using it #headless
# Finished 'func' in 4.598 secs  ,
# Finished 'func' in 4.614 secs

# driver = webdriver.Chrome(options=options, executable_path=ChromeDriverManager().install())
# There is no [win32] chromedriver for browser 91.0.4472 in cache

# Finished 'func' in 2.851 secs installing , 2.9
#  after install
# Finished 'func' in 1.481 secs
# Finished 'func' in 1.5040676 secs
# Finished 'func' in 1.517 secs+
# Finished 'func' in 1.022 secs not using it
# Finished 'func' in 1.012 secs

```
so in chrome is 500 ms ~~ 50% more time from 1s . 

after my mod
Finished 'cond' in 1.011678 secs # stays around that level only ad about 6ms more
Finished 'croAut' in 0.005558 secs
Finished 'exfile' in 2.6e-05 secs
Finished 'cond' in 1.011678 secs

i explain. the code check chrome version and then cromedriver version
check chrome version - is your code i use in this croAut funtion , very good ~~6ms
 cromedriver version~- this is where your code wastes time , your checking a url requests this takes at least 200ms 

my change is i check the cromedriver version looking is the file exist locally , just that . you save the exe in such folders so , just put the path to check , ?: if present> put the path : not > download . 99% of the time we already have the file locally because the first time run we get than dont need to check request hundred times again until weeks for the next version arrive

i just put in the executable_path=

if os.path.isfile("C:\\Users\"user"\.wdm\drivers\chromedriver\win32\\" + crome version var + "\chromedriver.exe"): ~the path ;  else:  ChromeDriverManager().install()

you can make this behaviour default. check the file not request.  so this lib would be just perfect . 

if i have time soon i can look better in your code to understand better and try to edit and make a pull of it. but im quite newbie too.

**Comment by leao-nardo** [comment]
and theres another problem in the way it works now ,that is getting the latest version of ChromeDriver from the net by request .
the problem is that it downloads and try to use the newer always , even if the version of chrome installed is not the newer ,and because of that it actually breaks the code ,the code stop working until we close the browser stoping everything were doing in it and then update chrome , if we do not update our chrome in our system to the last one , it breaks selenium because he tries to use lastest crome driver  with previous chrome browser .

**Comment by leao-nardo** [comment]
and theres a thing , in your code you dont get the last digits of the version in the   funtion
ChromeDriverManager().driver.browser_version

but there another lib that i used befor your and that one get all the digits so this is the function that i used in my implementation to check if folder exist. se i will copy here for you and his funcition is even quite faster .


@timer
def croversion(): #webdrivermanager
    version = None
    with subprocess.Popen(
        ['reg', 'query', 'HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon', '/v', 'version'],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL
    ) as stream:
        stdout = stream.communicate()[0].decode()
        version = re.search(r'\d+\.\d+\.\d+', stdout)
    return version

print(croversion())

@timer
def croAut(): #chromedriver_autoinstaller
    process = subprocess.Popen(
        ['reg', 'query', 'HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon', '/v', 'version'],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL
    )
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
    return version

print(croAut())

# Finished 'croAut' in 0.00619 secs
# Finished 'croversion' in 0.01236 secs

# Finished 'croAut' in 0.00609 secs
# 91.0.4472.77
# Finished 'croversion' in 0.005927 secs
# <re.Match object; span=(78, 87), match='91.0.4472'>

Finished 'croversion' in 0.006459 secs
<re.Match object; span=(78, 87), match='91.0.4472'>
Finished 'croAut' in 0.005574 secs
Finished 'croAut' in 0.005742 secs
91.0.4472.77

Process finished with exit code 0

**Comment by aleksandr-kotlyar** [comment]
@leao-nardo I got your idea. Please format your messages with code blocks and other markdown language features to make it more readable for others.

**Comment by leao-nardo** [comment]
```
def importar(*modules):
    import os
    for i in (modules): exec('try:\n\timport ' + i + '\n\tprint(''"suceed"'') \nexcept:\n\tprint("fail import")\n\tos.system("pip install ' + i + '")')
importar( 'selenium', 'webdriver_manager')

def chromeAut():  #mod to run ChromeDriverManager only if needed
    import subprocess ,os
    from selenium import webdriver
    from webdriver_manager.chrome import ChromeDriverManager
    options = webdriver.ChromeOptions()

    process = subprocess.Popen(
        ['reg', 'query', 'HKEY_CURRENT_USER\\Software\\Google\\Chrome\\BLBeacon', '/v', 'version'],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL
    )
    version = process.communicate()[0].decode('UTF-8').strip().split()[-1]
    global driver
    try:
        path1 = os.environ['userprofile'] + "\.wdm\drivers\chromedriver\win32\\" + version + "\chromedriver.exe"
        print(path1)
        driver = webdriver.Chrome(options=options, executable_path=path1 )
    except:
        print('not found')
        driver = webdriver.Chrome(options=options, executable_path=ChromeDriverManager().install()  )

chromeAut()
#  test
driver.get('https://www.python-course.eu/python3_global_vs_local_variables.php')



```

**Comment by leao-nardo** [comment]
> @leao-nardo I got your idea. Please format your messages with code blocks and other markdown language features to make it more readable for others.

this chromeAut() is a funtion that i made to use it

**Comment by aleksandr-kotlyar** [comment]
@leao-nardo thank you. I guess you can make a pull request.

**Comment by aleksandr-kotlyar** [comment]
@leao-nardo I dug deeper into the source code of webdriver_manager. You don't need to worry because `webdriver_manager` has already `driver_cache` functional like you describe here. It's caches webdrivers for 1 day by default for each webdriver version+os you use. When cache date expires (`current_date - cache_date > 1 day diff`) then webdriver_manager downloads webdriver only once, and renews cache_date, so webdriver will be taken from cache for 1 more day.

As you can see - It's already optimized.

But if you still want to cache for more days and update webdriver cache once per X days - just set up the variable `cache_valid_range=30` for 30 days (as example). But be careful because minor version of browser and minor version of webdriver could change in these 30 days and cached webdriver could not work with newer higher minor version of browser if browser has been updated in these 30 days without checking new version of webdriver.

Example of code to update webdrivers in cache once per 30 days:
```python
from webdriver_manager.chrome import ChromeDriverManager

driver = ChromeDriverManager(cache_valid_range=30).install()
```

Let me know if this post was helpful or helpless for you ;-)
