### ISSUE TITLE
TypeError: install() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by maxisbrocca** [SergeyPirogov/webdriver_manager#203]
Hello,

I'm trying to use latest version of webdriver_manager in my project. When I try to execute following line:

`b = webdriver.Chrome(ChromeDriverManager.install())`

I'm getting:

_TypeError: install() missing 1 required positional argument: 'self'_

This sames is happening with webdriver.Firefox(GeckoDriverManager.install()).

Probably I'm missing a configuration step.

Just in case there are a compatibility issue with any other lib in my project, this is the complete libs list:

atomicwrites==1.4.0
attrs==21.2.0
Babel==2.9.1
certifi==2021.5.30
chardet==4.0.0
colorama==0.4.4
configparser==5.0.2
crayons==0.4.0
glob2==0.7
idna==2.10
iniconfig==1.1.1
Mako==1.1.4
MarkupSafe==2.0.1
more-itertools==8.8.0
packaging==20.9
parse==1.19.0
parse-type==0.5.2
Pillow==8.2.0
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
pytest==6.2.4
pytest-bdd==4.0.2
pytest-html==3.1.1
pytest-html-reporter==0.2.6
pytest-metadata==1.11.0
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
selenium==3.141.0
six==1.16.0
toml==0.10.2
urllib3==1.26.5
wcwidth==0.2.5
webdriver-manager==3.4.2
zipp==1.2.0

Hope you can help me. 
Thanks in advance.

**Comment by maxisbrocca** [comment]
I forgot to mention, probably is important, that I'm using Ubuntu 18.04 as OS

**Comment by SergeyPirogov** [comment]
@maxisbrocca look at the example more attentively. I've forgotten () it should be  

b = webdriver.Chrome(ChromeDriverManager**()**.install())

**Comment by maxisbrocca** [comment]
:facepalm: Sorry for that! Thanks a lot @SergeyPirogov !!!!

**Comment by akhil067george** [comment]
Thanks @SergeyPirogov  for helping me out as well!
