### ISSUE TITLE
Print the Chrome console logs to the Python console

### ISSUE THREAD

**Issue by pravato** [SergeyPirogov/webdriver_manager#207]
I need to print the Chrome Console log while running my test. How do I do this using Webdriver Manager?

**Comment by aleksandr-kotlyar** [comment]
I think it's should not be webdriver_manager feature. Wdm is only for downloading webdriver for your browser.
@SergeyPirogov correct me if i'm wrong.

**Comment by SergeyPirogov** [comment]
Yes, not for webdriver manager
