### ISSUE TITLE
return the path of driver

### ISSUE THREAD

**Issue by reinaldorossetti** [SergeyPirogov/webdriver_manager#21]
Very good api, I think it should set the driver path in window, I have not seen. I think need create a function to return the path, not install function, type executable_path = GeckoDriverManager().path(), this is very good function.

**Comment by SergeyPirogov** [comment]
Actually install function already does this

```
def install(self):
--
  | # type: () -> str
  | return self._file_manager.download_driver(self.driver).path
```

**Comment by reinaldorossetti** [comment]
All in one function is confusing, but thanks for answering my question, It is not install again only return this string/path.
