### ISSUE TITLE
Could there be a way to only check local cache existence without latest version check?

### ISSUE THREAD

**Issue by hongmocai** [SergeyPirogov/webdriver_manager#218]
It may not be necessary that local cached drivers must be the latest version. If there is one usable, that might be enough.

**Comment by aleksandr-kotlyar** [comment]
@hongmocai how do you suppose webdriver_manager should check that cached version is suitable?

For example:
- webdriver version 93
- browser version installed 94
By chance previous version of webdriver works with newer version of browser
Should it be the case you mean in this issue?

Please provide cases of the logic you mean.

**Comment by aleksandr-kotlyar** [comment]
@hongmocai you can set variable `cache_valid_range` as long as you need to enable this kind of logic.
Example is in README https://github.com/SergeyPirogov/webdriver_manager#cache_valid_range
