### ISSUE TITLE
Add test support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [SergeyPirogov/webdriver_manager#223]
Hi Team, 

I tried testing **webdriver_manager** package on Arm64 architectures but it is generating `31 errors with 19 Passed` for the `pipenv run py.test -sv --cov-config .coveragerc --cov-report xml --cov-report term:skip-covered --cov=webdriver_manager --tb=short tests`/ test command with the error related to these [mentioned browsers](https://github.com/SergeyPirogov/webdriver_manager#webdriver-manager-for-python). 

So, tried installing each one by one but didn’t get installed as they are not supported for arm64. Used `apt-get install firefox` and it helped in solving in some of the above errors and now getting `27 Passed and 23 Failed.` 

**GHA-logs:** https://github.com/bhumikapaharia/webdriver_manager/actions/runs/1245409175 

I checked the opera support as taken for Amd64 architecture in [.github/workflows/test.ym](https://github.com/SergeyPirogov/webdriver_manager/blob/master/.github/workflows/test.yml)l, it seems to be not available for Arm64 refer [this](https://deb.opera.com/opera-stable/dists/stable/non-free/). 

Could you please share your feedback regarding this and suggest what can be done to test this over ARM64 server? 

Thanks in advance.

**Comment by aleksandr-kotlyar** [comment]
ARM64 ubuntu:

There is no Opera browser for ARM64 for now.
There is no geckodriver for ARM64 for now, (you should [build it by yourself](https://firefox-source-docs.mozilla.org/testing/geckodriver/ARM.html)).
There is no Google Chrome for ARM64 (only chromium available with [electron releases](https://github.com/electron/electron/releases/))

Only MSEdge has support for ARM64.

@odidev this is my feedback. You can add tests for Chromium and MSEdge into arm64 suite and custom job for it, like "`tests-negative`" suite in `~/tests_negative/` path.
