### ISSUE TITLE
#Question - Safari webdriver?

### ISSUE THREAD

**Issue by alltheoptions** [SergeyPirogov/webdriver_manager#23]
Do you have any idea how to add Safari into manager?

**Comment by SergeyPirogov** [comment]
@alltheoptions I think it's possible, but I don't know where we can download safari driver

**Comment by alltheoptions** [comment]
@SergeyPirogov safaridriver is built in into Safari version 10+ 

https://webkit.org/blog/6900/webdriver-support-in-safari-10/

**Comment by SergeyPirogov** [comment]
feel free to submit a pull request 

_Sent from my Samsung SM-A300H using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
