### ISSUE TITLE
Rename GITHUB_TOKEN in CI scripts

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [SergeyPirogov/webdriver_manager#234]
### What
Seems that GitHub has updated the policy of naming secret variables in Project.Settings.Secrets, they can no longer to have name start from GITHUB, as you can see on the screenshot:

![image](https://user-images.githubusercontent.com/17043964/136355303-d0ad4912-889f-424a-8c7d-ac4125532eef.png)

### Proposal solution
In this case - we should rename GITHUB_TOKEN in webdriver_manager github-actions and recreate new token in webdriver_manager settings of the main project and across all forks in case to continue to contribute here.
- [ ] rename GITHUB_TOKEN in github-action ymls to GH_TOKEN
- [ ] recreate SECRET in main project by @SergeyPirogov 

I can make a PR soon.

**Comment by SergeyPirogov** [comment]
Ok, lets rename

**Comment by aleksandr-kotlyar** [comment]
The commit is already in PR #240
@SergeyPirogov You need to rename secret in your project. Please tell me when you done. I will push an empty commit to trigger job with new variable name, and we will see tests passing.
