### ISSUE TITLE
Bad CPU type Error when geckodriver, and solution

### ISSUE THREAD

**Issue by nogayama** [SergeyPirogov/webdriver_manager#258]
- Current version
    ```
    pip list
    webdriver-manager   3.5.1
    ```

- Error message
    ```
    OSError: [Errno 86] Bad CPU type in executable: '/Users/username/.wdm/drivers/geckodriver/macos/v0.30.0/geckodriver'
    ```

- Solution
    ```sh
    $ cd ~/.wdm/drivers/geckodriver/macos/v0.30.0
    $ curl -Lsk -O https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos.tar.gz
    $ ls 
    geckodriver
    geckodriver-v0.30.0-macos-aarch64.tar.gz
    geckodriver-v0.30.0-macos.tar.gz
    $ rm geckodriver
    $ tar zxvf geckodriver-v0.30.0-macos.tar.gz 
    ```

**Comment by aleksandr-kotlyar** [comment]
What machine do you use? Mac M1?

**Comment by aleksandr-kotlyar** [comment]
You use Firefox for M1 or emulated for i386? If emulated - your advice is correct. 
But webdriver-manager is adopted for aarch64 Firefox and geckodriver. 
I have tested and i see that the code works properly for m1 - chooses macos-aarch64 geckodriver. And just macos geckodriver for i386 (32-64) processors.

**Comment by aleksandr-kotlyar** [comment]
@nogayama Thank you for report! if issue is still reproducible - please add a scenario with details to reproduce (see the questions and comments above). And fill free to reopen the issue.
