### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by rimikt** [SergeyPirogov/webdriver_manager#26]
Section for PhantomJS has an typo
----

`driver = webdriver.PhantomJS(PhantomJsDriverDriverManager().install())`

should be

`driver = webdriver.PhantomJS(PhantomJsDriverManager().install())`

**Comment by SergeyPirogov** [comment]
Actually, as I know PhantomJS is deprecated for Selenium, so this code becomes invalid

**Comment by SergeyPirogov** [comment]
fixed
