### ISSUE TITLE
Getting SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by robertdeocampojr** [SergeyPirogov/webdriver_manager#271]
We are getting the error below when we call 'ChromeDriverManager().install()'. any idea to resolve this? Thank you in advance.

`<html>
<body>

Setup failed: SSLError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /LATEST_RELEASE_95.0.4638 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
--

</body>
</html>`

**Comment by aleksandr-kotlyar** [comment]
Try 3.5.2 version with 
```python
import os
os.environ['WDM_SSL_VERIFY'] = '0'
ChromeDriverManager().install()
```
