### ISSUE TITLE
JSONDecodeError for installation with GeckoDriverManager

### ISSUE THREAD

**Issue by heinp** [SergeyPirogov/webdriver_manager#273]
Recently (first time noticed it last week) when trying to install GeckoDriver using the GeckoDriverManager it freezes for a couple minutes on `Trying to download new driver from […]` and then raises a `JSONDecodeError` while trying to raise a `ValueError` indicating it didn't receive a 200 response. I do have an active internet connection.

Version of webdriver_manager: 3.2.1
OS: Arch

```
>>> from webdriver_manager.firefox import GeckoDriverManager
>>> exec_path = GeckoDriverManager().install()


[WDM] - ====== WebDriver manager ======
[WDM] - There is no [linux64] geckodriver for browser  in cache
[WDM] - Getting latest mozilla release info for v0.30.0
[WDM] - Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/x/.local/lib/python3.9/site-packages/webdriver_manager/firefox.py", line 29, in install
    return self._get_driver_path(self.driver)
  File "/home/x/.local/lib/python3.9/site-packages/webdriver_manager/manager.py", line 28, in _get_driver_path
    file = download_file(driver.get_url())
  File "/home/x/.local/lib/python3.9/site-packages/webdriver_manager/utils.py", line 93, in download_file
    validate_response(response)
  File "/home/x/.local/lib/python3.9/site-packages/webdriver_manager/utils.py", line 81, in validate_response
    raise ValueError(resp.json())
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 901, in json
    return complexjson.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by heinp** [comment]
Updated to webdriver_manager v. 3.5.2. The problem persists.

**Comment by Bisteccowner** [comment]
I solved a problem like this for Chrome, using: 

os.environ['WDM_LOCAL'] = '1'

https://github.com/SergeyPirogov/webdriver_manager/issues/270

**Comment by heinp** [comment]
> I solved a problem like this for Chrome, using:
> 
> os.environ['WDM_LOCAL'] = '1'
> 
> #270

Thanks, but this doesn't work. Error persists.

**Comment by rachmadaniHaryono** [comment]
@heinp can you try #279

 it will not fix your actual error with webdriver_manager but it will print out actual error instead of jsondecodeerror

**Comment by heinp** [comment]
> @heinp can you try #279
> 
> it will not fix your actual error with webdriver_manager but it will print out actual error instead of jsondecodeerror

With that it works perfectly, there is no error at all anymore. Is this weird? Thanks though!

**Comment by rachmadaniHaryono** [comment]
> With that it works perfectly, there is no error at all anymore. Is this weird?

yes, if everything is working correctly and actual error is not yet resolved, there should be ValueError instead of jsondecodeerror

if not i think it could be fixed and you may not even need the pr
