### ISSUE TITLE
Running 32-bit Python on x64 Windows identifies the OS architecture incorrectly

### ISSUE THREAD

**Issue by vanderloos** [SergeyPirogov/webdriver_manager#28]
Hi Sergey,

To identify the OS bitness you've used `platform.architecture()` call, but it returns an architecture of Python itself. Rather than the OS. 
Cases when I have 32-bit Python on Win64 machines:
1. After the recent release a 64-bit version of Python 3.6 for Windows was not installable for a while;
In stdout when running the webdriver_manager:
```
...
Checking for win32 geckodriver:v0.19.1 in cache   # Win32 version got downloaded.
```
Python cli:
```
>>> platform.architecture()
('32bit', 'WindowsPE')
>>> platform.machine()
'AMD64'
```
2. I run Conda virtual environments on another Win10.
In stdout when running the webdriver_manager:
```
...
Checking for win geckodriver:v0.19.1 in cache   # Win32 version got downloaded.
```
Note the architecture is just 'win' for some reason.
Though in Python cli:
```
>>> platform.architecture()
('64bit', 'WindowsPE')
>>> platform.machine()
'AMD64'
```

It seems like `platform.machine()` call returns more relevant data. But there likely are some other possible options.

I'm here to answer any other questions one might have.

**Comment by SergeyPirogov** [comment]
Hm, good point. Could you please submit a PR to fix it?
