### ISSUE TITLE
Open en close

### ISSUE THREAD

**Issue by remcoNL** [SergeyPirogov/webdriver_manager#280]
As a total newby I'm assuming this downloads Chromedriver everytime? It's is often advised to close de webdriver while the program is still running.  

Is there a way to open (and close) the downloaded driver?

Tx!

**Comment by aleksandr-kotlyar** [comment]
Not a webdriver_manager issue.

It's a selenium thing.
Use `driver.quit()` to close browser and stop wedriver.
