### ISSUE TITLE
Hiding geckodriver.exe console window when used in a compiled script [PyInstaller]

### ISSUE THREAD

**Issue by hash3liZer** [SergeyPirogov/webdriver_manager#283]
Hi, the package works great. However, when i use it a compiled non-console script, the `webdriver_manager` package creates a new console window. The browser being used is `Firefox`. And this is the console window that i get upon launching the non-console agent: 

![image](https://user-images.githubusercontent.com/29171692/144269873-d4b7a75a-b230-4cbb-8015-7271496d31f1.png)

I used PyInstaller for compilaton: 
```
$ pyinstaller --noconsole script.py
```

My question is how can i hide this window? The documentation doesn't show any data related to this.

**Comment by aleksandr-kotlyar** [comment]
Do you use `driver.quit()` in your `script.py`? 

Not enough information to triage the issue. Please give more info and provide steps to reproduce. For example: code of script.py and action points how you make .exe by pyinstaller from it and how do you execute this .exe file.

**Comment by aleksandr-kotlyar** [comment]
@meichthys thank you for posting the solution! https://github.com/SergeyPirogov/webdriver_manager/issues/283#issuecomment-1095366926
