### ISSUE TITLE
does not re-download or unzip driver.zip if user deletes chromedriver.exe in webdriver-manager         3.5.2

### ISSUE THREAD

**Issue by vkkindia** [SergeyPirogov/webdriver_manager#286]
webdriver-manager         3.5.2

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST chromedriver version for 97.0.4692 google-chrome
Driver [D:\python\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache
Traceback (most recent call last):
  File "D:\python\install_driver.py", line 17, in <module>
    s=Service(ChromeDriverManager().install())
  File "D:\python\lib\site-packages\webdriver_manager\chrome.py", line 34, in install
    os.chmod(driver_path, 0o755)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\python\\.wdm\\drivers\\chromedriver\\win32\\97.0.4692.71\\chromedriver.exe'

Again downloads only if drivers.json file is deleted

**Comment by aleksandr-kotlyar** [comment]
In 3.2.2 or 3.4.2 versions problem saves?

**Comment by aleksandr-kotlyar** [comment]
Yep. It's expected behaviour of webdriver-manager.

drivers.json - is a cache controller of downloaded webdrivers. When you clean webdriver - you should remove the row from drivers.json or delete drivers.json if you want webdriver-manager to re-download the webdriver.

**Comment by aleksandr-kotlyar** [comment]
I have thoughts how to improve this.
