### ISSUE TITLE
feature request: PhantomJS driver manager

### ISSUE THREAD

**Issue by mdp18** [SergeyPirogov/webdriver_manager#289]
Is there any chance someone is willing to add PhantomJS as an additional driver to manage?

**Comment by aleksandr-kotlyar** [comment]
But why? :) It's dead for 7 years. https://phantomjs.org/releases.html
And it's not hard to make downloader for their releases https://bitbucket.org/ariya/phantomjs/downloads/
Adding support for dead webdriver with tests in webdriver_manager is wasting of time.

**Comment by mdp18** [comment]
Yeah I wrote that and later realized it was dead lol. Closing now.
