### ISSUE TITLE
chromedriver in path or .wdm/ which gets called?

### ISSUE THREAD

**Issue by vkkindia** [SergeyPirogov/webdriver_manager#303]
In my system i have chromedriver in path and also in .wdm that got autodownloaded.
Now when an update  comes and webdriver-manager downloads the newer  version and stored in .wdm.
But when the python program calls, the chromedriver in path (older ver) is getting run.
It would be nice if your program shows the path  of the chromedriver which is called.
for time being i have to delete the chromedriver in path. then no issue.
For the users who switches to your program, this will be annoying.

Thanks again

**Comment by aleksandr-kotlyar** [comment]
@vkkindia show the code please.
