### ISSUE TITLE
Edge WebDriver not getting downloaded. 

### ISSUE THREAD

**Issue by meet2712** [SergeyPirogov/webdriver_manager#304]
Since past few days I am not able to download the Edge Selenium Drivers using webdriver-manager version = 3.5.2

-------------------------------Logs-----------------------------

TypeError                                 Traceback (most recent call last)
Input In [6], in <module>
      1 from selenium import webdriver
      2 from webdriver_manager.microsoft import EdgeChromiumDriverManager
----> 4 driver = webdriver.Edge(EdgeChromiumDriverManager().install())

File ~\Downloads\VirtualEnviorment\lib\site-packages\webdriver_manager\microsoft.py:50, in EdgeChromiumDriverManager.__init__(self, version, os_type, path, name, url, latest_release_url, log_level, print_first_line, cache_valid_range)
     38 def __init__(
     39     self,
     40     version="latest",
   (...)
     48     cache_valid_range=1,
     49 ):
---> 50     super().__init__(path, log_level, print_first_line, cache_valid_range)
     51     self.driver = EdgeChromiumDriver(
     52         version=version,
     53         os_type=os_type,
   (...)
     56         latest_release_url=latest_release_url,
     57     )

File ~\Downloads\VirtualEnviorment\lib\site-packages\webdriver_manager\manager.py:13, in DriverManager.__init__(self, root_dir, log_level, print_first_line, cache_valid_range)
     11 if os.environ.get('WDM_PRINT_FIRST_LINE', str(print_first_line)) == 'True':
     12     log("\n", formatter='%(message)s', level=log_level)
---> 13 log("====== WebDriver manager ======", level=log_level)

File ~\Downloads\VirtualEnviorment\lib\site-packages\webdriver_manager\logger.py:25, in log(text, level, name, first_line, formatter)
     23 def log(text, level=logging.INFO, name="WDM", first_line=False, formatter='[%(name)s] - %(message)s'):
     24     """Emitting the log message."""
---> 25     _init_logger(level, name, first_line, formatter)
     26     loggers.get(name).info(text)

File ~\Downloads\VirtualEnviorment\lib\site-packages\webdriver_manager\logger.py:19, in _init_logger(level, name, first_line, formatter)
     17 handler.setFormatter(formatter)
     18 _logger.addHandler(handler)
---> 19 _logger.setLevel(level)
     20 loggers[name] = _logger

File ~\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py:1421, in Logger.setLevel(self, level)
   1417 def setLevel(self, level):
   1418     """
   1419     Set the logging level of this logger.  level must be an int or a str.
   1420     """
-> 1421     self.level = _checkLevel(level)
   1422     self.manager._clear_cache()

File ~\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py:201, in _checkLevel(level)
    199     rv = _nameToLevel[level]
    200 else:
--> 201     raise TypeError("Level not an integer or a valid string: %r" % level)
    202 return rv

TypeError: Level not an integer or a valid string: None

**Comment by aleksandr-kotlyar** [comment]
Fixed in #284. Waiting for release 3.5.3.

**Comment by meet2712** [comment]
> Fixed in #284. Waiting for release 3.5.3 today.

Thanks !
