### ISSUE TITLE
google-chrome version is UNKNOWN with webdriver_manager 3.5.3 (Win)

### ISSUE THREAD

**Issue by np-8** [SergeyPirogov/webdriver_manager#307]
Steps to reproduce:

```python
In [1]: import webdriver_manager

In [2]: webdriver_manager.__version__
Out[2]: '3.5.3'

In [3]: from webdriver_manager.utils import *

In [4]: get_browser_version_from_os("google-chrome")
[WDM] - Could not get version for google-chrome with the command:  powershell "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion 
} if (-not $? -or $? -match $error) { (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version } if (-not $? -or $? -match $error) { reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version }"
[WDM] - Current google-chrome version is UNKNOWN
Out[4]: 'UNKNOWN'
```

I tested with the `webdriver_manager` installed via pip (3.5.3) and the latest version from GitHub ( f7a0855 ).

**Comment by aleksandr-kotlyar** [comment]
Please add some additional info

1. Whats your windows version and architecture (32/64)?
2. What configuration - local computer, docker, virtual machine, cloud, something else?
3. Has powershell?
4. What is the version of powershell?
5. Does google chrome installed?
6. How google chrome has been installed? 
7. What location of google-chrome on the disc?
8. PATH variable has google chrome binary path?
9. What's the PATH to Google Chrome?
10. Bonus: if you can find register which contains installed google chrome version to share with us - this will help a lot to resolve your issue.

**Comment by np-8** [comment]
I did some debugging on this. So basically, the `chrome.exe` filepath is searched with the following ways:

```
(1)
(Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion

(2)
(Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion

(3)
(Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion

(4)
reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version

(5)
reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version
```

Here are the outputs on my machine:

### (1)

```
PS C:\Users\niko> (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
Get-Item : Cannot find path 'C:\Program Files\Google\Chrome\Application\chrome.exe' because it does not exist.
At line:1 char:2
+ (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.e ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Program Files\Go\u2026lication\chrome.exe:String) [Get-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

### (2)

```
PS C:\Users\niko> (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion

Get-Item : Cannot find path 'C:\Program Files(x86)\Google\Chrome\Application\chrome.exe' because it does not exist.
At line:1 char:2
+ (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chr ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Program Files(x8\u2026lication\chrome.exe:String) [Get-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```

### (3)

```
PS C:\Users\niko> (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
Get-Item : Cannot find path 'C:\Users\niko\AppData\Local\Google\Chrome\Application\chrome.exe' because it does not exist.
At line:1 char:2
+ (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.e ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\niko\AppDa\u2026lication\chrome.exe:String) [Get-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
```
### (4)

```
PS C:\Users\niko> reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version

HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\BLBeacon
    version    REG_SZ    97.0.4692.99
```

### (5)

```
PS C:\Users\niko> reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
    version    REG_SZ    98.0.4758.102
```

### My Chrome version

My `chrome.exe` is located at: `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`.  Inside the `C:\Program Files (x86)\Google\Chrome\Application\` folder I have actually 
- Folder called `97.0.4692.99`
- Folder called `98.0.4758.102`
- Executables `chrome.exe` and `new_chrome.exe`.

I have update logo at the top right corner of the Chrome window:

![image](https://user-images.githubusercontent.com/17479683/154439651-7bf90683-7800-4da2-8e97-0a574dd2e17d.png)

Before clicking "Update", the version was `97.0.4692.99`, and after clicking update is was `98.0.4758.102`. After clicking the update button the folder `97.0.4692.99` and `new_chrome.exe` were removed from `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`.  So this explains why the two `reg query` commands gave different chrome versions; the Chrome update was process was unfinished. Still after the Chrome update, the ` get_browser_version_from_os("google-chrome")` returns `'UNKNOWN'`.

### What might be the problem 

The first problem is that the path returned with `(2)` is actually `'C:\Program Files(x86)\Google\Chrome\Application\chrome.exe'` which is *missing the space just before (x86)*!  

That does not entirely explain why the returned Chrome version is `'UNKNOWN'` as both of the `reg query` commands give after the finished Chrome update the same version:

````
PS C:\Users\niko> reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version

HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\BLBeacon
    version    REG_SZ    98.0.4758.102

PS C:\Users\niko> reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
    version    REG_SZ    98.0.4758.102
```

**Comment by np-8** [comment]
In addition to above, @aleksandr-kotlyar: 

1. Windows 10 64-bit, Version 21H2, Build 19044.1466
2. Local computer
3. Yes
4. I have multiple versions of powershell installed. If I start `powershell` from cmd, I can see this:

```
PS C:\Users\niko> (Get-Host).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1320
```

5. Yes
6. Downloaded with Edge, probably
7. See previous comment 
8. No
9. \-
10. See previous comment

**Comment by np-8** [comment]
Now debugging inside the `webdriver_manager\utils.py:read_version_from_cmd`.

```python
def read_version_from_cmd(cmd, pattern):
    with subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        stdin=subprocess.DEVNULL,
        shell=True,
    ) as stream:
        stdout = stream.communicate()[0].decode()
        version = re.search(pattern, stdout)

    breakpoint()
    return version
```

The `cmd` and `stdout` are: 

```
In [3]: cmd
Out[3]: ' powershell "$ErrorActionPreference=\'silentlycontinue\' ; (Get-Item -Path "$env:PROGRAMFILES\\Google\\Chrome\\Application\\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\\Google\\Chrome\\Application\\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-Item -Path "$env:LOCALAPPDATA\\Google\\Chrome\\Application\\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query "HKCU\\SOFTWARE\\Google\\Chrome\\BLBeacon" /v version } if (-not $? -or $? -match $error) { reg query "HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Google Chrome" /v version }"'

In [4]: stdout
Out[4]: ''
```

So the problem seems to be that nothing is returned to `stdout`.

**Comment by np-8** [comment]
I'm trying to run just the powershell script part. I copy-pasted the script contents, which are:

```
$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? 
-match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version } if (-not $? -or $? -match $error) { reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version }
```

into a new script file, and ran it, and got:

```
PS C:\Users\niko> powershell -File C:\tmp\testscript.ps1
At C:\tmp\testscript.ps1:2 char:1
+ -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrom ...
+ ~~~~~~
Missing closing ')' after expression in 'if' statement.
At C:\tmp\testscript.ps1:2 char:14
+ -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrom ...
+              ~
Unexpected token ')' in expression or statement.
At C:\tmp\testscript.ps1:2 char:123
+ ... \Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $ ...
+                                                                ~~
Unexpected token 'if' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisAfterStatement
```

**Comment by np-8** [comment]
While running this in powerhell works:
```
PS C:\Users\niko> (Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
98.0.4758.102
```

..the same command does not produce desired output when using the `communicate()`: 

```python
In [44]: cmd = r""" powershell "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVer 
    ...: sion ;"""

In [45]: with subprocess.Popen(
    ...:     cmd,
    ...:     stdout=subprocess.PIPE,
    ...:     stderr=subprocess.DEVNULL,
    ...:     stdin=subprocess.DEVNULL,
    ...:     shell=True,
    ...: ) as stream:
    ...:     print(stream.communicate())
(b'', None)
```

I'm trying make a minimal example that will return the output from the powershell to python.

**Comment by aleksandr-kotlyar** [comment]
Thank you for such detailed research! 
Yeah, seams that there is missing space for env with PROGRAMFILES (x86)
You can make a PR if you want or I can do it this evening.

**Comment by np-8** [comment]
Coming back to this. Probably it is a good idea to add the following flags to the `powershell` command: 

```
-ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command
```

Then, I did some simple experiments using just `cmd`. 

When running in **powershell**, the following command works:

```
PS C:\Users\niko>  (Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
98.0.4758.102
```

When running this in **cmd**, I got this:

```
C:\Users\niko> powershell  -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command  "(Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion"
x86 : The term 'x86' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:36
+ (Get-Item -Path $env:PROGRAMFILES (x86)\Google\Chrome\Application\chr ...
+                                    ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

you might already guessed from this that the problem has something to do with quoting. Reading from [here](https://stackoverflow.com/a/49956922/3015186) I guessed that I should add the number of quotes in the subexpression. So, using **four doublequotes** (`""""`) instead of a single doublequote (`"`) will work:

```
C:\Users\niko> powershell  -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command  "(Get-Item -Path """"$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion"
98.0.4758.102
```

**Comment by np-8** [comment]
Replacing single doublequotes with four doublequotes works, almost:

```
C:\Users\niko> powershell -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path """"$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path """"$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-Item -Path """"$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query """"HKCU\SOFTWARE\Google\Chrome\BLBeacon"""" /v version } if (-not $? -or $? -match $error) { reg query """"HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome"""" /v version }"

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
    version    REG_SZ    98.0.4758.102
```

Now the problem is that for some reason the version is read from the `req query` command and not from the previous working command using the `Get-Item`. Simplifying the command above gives:

```
C:\Users\niko>powershell -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path """"$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path """"$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion }"
```

.. which does not work. It can be simplified even more:

```
C:\Users\niko>powershell -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command "{ (Get-Item -Path """"$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion }"
 (Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
```

which just prints the command back to the console. The problem seems to be the braces (`{}`). When you remove the braces, you'll see:

```
C:\Users\niko>powershell -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -Command "(Get-Item -Path """"$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe"""").VersionInfo.FileVersion"
98.0.4758.102
```

So apparently there should be special handling of quotes when they are enclosed in braces.

**Comment by np-8** [comment]
I have a feeling that it might be difficult trying to get command passed from cmd to Powershell in every situation as is. From [this answer](https://stackoverflow.com/a/30269513/3015186) it looks like the `-EncodedCommand` might be the way to go.

**Comment by np-8** [comment]
Here is a powershell script I came up with that seems to do the job. First, the "all okay" case:

```
$ErrorActionPreference='silentlycontinue'

$chromepathending = "\Google\Chrome\Application\chrome.exe"
$chromepath = Get-Item -Path (Join-Path ${env:ProgramFiles} -ChildPath $chromepathending)

if (-not (Test-Path -Path $chromepath))
{
	$chromepath = Get-Item -Path (Join-Path ${env:ProgramFiles(x86)} -ChildPath $chromepathending)
}
if (-not (Test-Path -Path $chromepath))
{
	$chromepath = Get-Item -Path (Join-Path ${env:LOCALAPPDATA} -ChildPath $chromepathending)
}

if ((Test-Path -Path $chromepath))
{
	echo $chromepath.VersionInfo.FileVersion
} else {
	reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version
	reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version
} 
```

When I run this, I will get:

```
PS C:\Users\niko> & C:\tmp\testscript.ps1
98.0.4758.102
```

If there will be no match, it will print:

```
PS C:\Users\niko> & C:\tmp\testscript.ps1

HKEY_CURRENT_USER\SOFTWARE\Google\Chrome\BLBeacon
    version    REG_SZ    98.0.4758.102


HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
    version    REG_SZ    98.0.4758.102
 ```

If one of the `reg query`'s will not work, it will print:

```
PS C:\Users\niko> & C:\tmp\testscript.ps1
ERROR: The system was unable to find the specified registry key or value.

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome
    version    REG_SZ    98.0.4758.102
```

and if *everything* fails, it will print:

```
PS C:\Users\niko> & C:\tmp\testscript.ps1
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
```.

This output string is then parsed in `webdriver_manager\utils.py:read_version_from_cmd`:

```python
        stdout = stream.communicate()[0].decode()
        version = re.search(pattern, stdout)
```

as `pattern` is 

```
In [7]: pattern
Out[7]: '\\d+\\.\\d+\\.\\d+'
```
it will find the first (and correct) version number in any of the cases.

**Comment by np-8** [comment]
Actually, the values from the registry can also be read with powershell commands. This simplifies a possible implementation a bit. The following

```
$ErrorActionPreference='silentlycontinue'

(Get-Item -Path (Join-Path ${env:ProgramFiles} -ChildPath "\Google\Chrome\Application\chrome.exe")).VersionInfo.FileVersion
(Get-Item -Path (Join-Path ${env:ProgramFiles(x86)} -ChildPath "\Google\Chrome\Application\chrome.exe")).VersionInfo.FileVersion
(Get-Item -Path (Join-Path ${env:LOCALAPPDATA} -ChildPath "\Google\Chrome\Application\chrome.exe")).VersionInfo.FileVersion
(Get-ItemProperty -Path Registry::HKCU\SOFTWARE\Google\Chrome\BLBeacon).version
(Get-ItemProperty -Path Registry::"HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome").version
```

will print just

```
PS C:\Users\niko> & C:\tmp\testscript.ps1
98.0.4758.102
98.0.4758.102
98.0.4758.102
```

Now it should be relatively straightforward to edit the `windows_browser_apps_to_cmd` a bit to check a list of commands that return a value and stop on the first hit.

**Comment by np-8** [comment]
@aleksandr-kotlyar for some reason the `windows_browser_apps_to_cmd` did not work. As a reference, here is a [branch](https://github.com/np-8/webdriver_manager/tree/test-without-windows_browser_apps_to_cmd-change) without changes in `windows_browser_apps_to_cmd`. The output with that branch is the same as with when using a8f64d2:

```python
In [1]: from webdriver_manager.utils import *

In [2]: get_browser_version_from_os("google-chrome")
[WDM] - Could not get version for google-chrome with the command:  powershell "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\AppVersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-ItemProperty -Path Registry::HKCU\SOFTWARE\Google\Chrome\BLBeacon).version } if (-not $? -or $? -match $error) { (Get-ItemProperty -Path Registry::"HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome").version }"      
[WDM] - Current google-chrome version is UNKNOWN
Out[2]: 'UNKNOWN'
```

PS. There was actually no problem in the `$env:PROGRAMFILES(x86)`; it should be like that.

**Comment by GonadiusPrime** [comment]
Same results on Windows Server 2016.  As a result of this, I believe it is going and pulling the latest driver, even though it exists locally.  This combined with xdist, I suspect, is making all the Jenkins runs fail.

First this...
INFO     WDM:logger.py:26 ====== WebDriver manager ======
INFO     WDM:logger.py:26 Could not get version for google-chrome with the command:  powershell "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version } if (-not $? -or $? -match $error) { reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version }"
INFO     WDM:logger.py:26 Current google-chrome version is UNKNOWN
INFO     WDM:logger.py:26 Get LATEST chromedriver version for UNKNOWN google-chrome
INFO     WDM:logger.py:26 Trying to download new driver from https://chromedriver.storage.googleapis.com/98.0.4758.102/chromedriver_win32.zip

Which leads to...
c:\python37\lib\site-packages\webdriver_manager\chrome.py:32: in install
    driver_path = self._get_driver_path(self.driver)
c:\python37\lib\site-packages\webdriver_manager\manager.py:32: in _get_driver_path
    driver_name, os_type, driver_version)
c:\python37\lib\site-packages\webdriver_manager\driver_cache.py:28: in save_file_to_cache
    files = archive.unpack(path)
c:\python37\lib\site-packages\webdriver_manager\archive.py:30: in unpack
    return self.__extract_zip(directory)
c:\python37\lib\site-packages\webdriver_manager\archive.py:36: in __extract_zip
    archive = zip_class(self.file_path)
c:\python37\lib\zipfile.py:1222: in __init__
    self._RealGetContents()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <zipfile.ZipFile [closed]>

    def _RealGetContents(self):
        """Read in the table of contents for the ZIP file."""
        fp = self.fp
        try:
            endrec = _EndRecData(fp)
        except OSError:
            raise BadZipFile("File is not a zip file")
        if not endrec:
>           raise BadZipFile("File is not a zip file")
E           zipfile.BadZipFile: File is not a zip file

c:\python37\lib\zipfile.py:1289: BadZipFile

On subsequent runs lead to this...
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 98.0.4758
[WDM] - Get LATEST driver version for 98.0.4758
[WDM] - There is no [win32] chromedriver for browser 98.0.4758 in cache
[WDM] - Get LATEST driver version for 98.0.4758
[WDM] - Trying to download new driver from https://chromedriver.storage.googleapis.com/98.0.4758.102/chromedriver_win32.zip
[WDM] - Driver has been saved in cache [C:\Users\Jenkins\.wdm\drivers\chromedriver\win32\98.0.4758.102]

selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

subprocess.py - PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

Or it may be completely unrelated.  I know the webdriver is capable of working, in a single instance, just not multiple.  Roughly the same results with MSEdge.

**Comment by geojitsu** [comment]
It does appear webdriver is looking in c:\Program Files, and not where google installs by default -- C:\Program Files (x86)

Simple solution, just create a link to chrome between the two directories

1) Create the folder structure C:\Program Files\Google\Chrome
2) Link the "Application" subdirectory to c:\Program Files (x86)\Google\Chrome\Application (see below)
3) Profit

Run command prompt as admin
mkdir "C:\Program Files\Google\Chrome"
mklink /J "c:\Program Files\Google\Chrome\Application" "c:\Program Files (x86)\Google\Chrome\Application"

**Comment by aleksandr-kotlyar** [comment]
> It does appear webdriver is looking in c:\Program Files, and not where google installs by default -- C:\Program Files (x86)
> 
> Simple solution, just create a link to chrome between the two directories
> 
> 1. Create the folder structure C:\Program Files\Google\Chrome
> 2. Link the "Application" subdirectory to c:\Program Files (x86)\Google\Chrome\Application (see below)
> 3. Profit
> 
> Run command prompt as admin mkdir "C:\Program Files\Google\Chrome" mklink /J "c:\Program Files\Google\Chrome\Application" "c:\Program Files (x86)\Google\Chrome\Application"

@geojitsu webdriver-manager is already looking in both places
```python
$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe
$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe
```
what version of webdriver-manager do you use? If it appears on the latest versions of webdriver-manager - please create new issue if it reproduces and link to this issue. Cause this issue is closed.
