### ISSUE TITLE
Win 32 Bit Versions of Drivers Downloaded for Win 64

### ISSUE THREAD

**Issue by ransom4real** [SergeyPirogov/webdriver_manager#31]
I am using the webdriver manager on a windows 10 64 bit machine and each time i attempt to use the webdriver manager, it downloads 32 bit versions of the drivers. However, when i execute the code `utils.os_type()` I can see win64 returned.

**Comment by SergeyPirogov** [comment]
@ransom4real Driver for which browser you are trying to download?

**Comment by ransom4real** [comment]
@SergeyPirogov Firefox.

**Comment by SergeyPirogov** [comment]
@ransom4real Have you installed the library from pypi? Which version do you have?

**Comment by ransom4real** [comment]
@SergeyPirogov yes i have installed it from pypi. I currently have version 1.4.5

**Comment by SergeyPirogov** [comment]
@ransom4real Hello, I've checked this and everything works fine. I added additional logging and now you can see in your console smth like:

```
Getting latest mozila release info for v0.19.1
Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
Unpack archive /home/travis/.wdm/geckodriver/v0.19.1/linux64/geckodriver-v0.19.1-linux64.tar.gz
```
Please double check and give your feedback

**Comment by ransom4real** [comment]
@SergeyPirogov on it!. Thanks!

**Comment by SergeyPirogov** [comment]
Release 1.5 have all fixes

**Comment by ransom4real** [comment]
@SergeyPirogov it has certainly been fixed. Thank you so much for your help!
