### ISSUE TITLE
Error in webdriver.util get_browser_version_from_os for 32 bit applications

### ISSUE THREAD

**Issue by vong0** [SergeyPirogov/webdriver_manager#315]
the latest version of the webdriver manager has a bug where these is no space between program files and (x86).

```
r'(Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion'
```

this results in errors since: 'C:\Program Files(x86)' does not exist.

to fix this, all "$env:PROGRAMFILES(x86)" should be replaced with "$env:PROGRAMFILES (x86)"

**Comment by vong0** [comment]
hmm. not only that. the entirely of this method seems completely broken:

```
from webdriver_manager.utils import get_browser_version_from_os
get_browser_version_from_os("google-chrome")
```

**Comment by aleksandr-kotlyar** [comment]
@vong0 thank you for report! Please attach code and stacktrace to reproduce that.

**Comment by vong0** [comment]
The code to reproduce, run on any windows machine with google chrome installed:
```
from webdriver_manager.utils import get_browser_version_from_os
get_browser_version_from_os("google-chrome")
```

Error Log:
```
[WDM] - Could not get version for google-chrome with the command:  powershell "$ErrorActionPreference='silentlycontinue' ; (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion ; if (-not $? -or $? -match $error) { (Get-Item -Path "$env:PROGRAMFILES(x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion } if (-not $? -or $? -match $error) { reg query "HKCU\SOFTWARE\Google\Chrome\BLBeacon" /v version } if (-not $? -or $? -match $error) { reg query "HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome" /v version }"
[WDM] - Current google-chrome version is UNKNOWN
```

Note that when running manually on my machine one of these individual commands work:
```
(Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
(Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion
```

I think the issues lies at:
- should be a space before (x86) in the dictionary definitions but even with that fix it still won't run
- also this function "windows_browser_apps_to_cmd"

**Comment by vong0** [comment]
Ok I did some more investigation. This only seems to apply for google chrome and on windows (edge + firefox work fine)

**Comment by aleksandr-kotlyar** [comment]
@vong0 please try now the current master branch from repo. PR #316 should fix this.

**Comment by vong0** [comment]
thanks. i think that fixed it.
