### ISSUE TITLE
IE Driver download points to an incorrect link

### ISSUE THREAD

**Issue by ransom4real** [SergeyPirogov/webdriver_manager#32]
Downloading IE Driver points to http://selenium-release.storage.googleapis.com/3.8/IEDriverServer_Win64_3.8.0.zip but looking at the source it is meant to refer to http://selenium-release.storage.googleapis.com/3.8/IEDriverServer_x64_3.8.0.zip

**Comment by SergeyPirogov** [comment]
No, everything works fine.

```
Checking for x64 IEDriverServer:3.8.0 in cache
There is no cached driver. Downloading new one...
Trying to download new driver from http://selenium-release.storage.googleapis.com/3.8/IEDriverServer_x64_3.8.0.zip
Unpack archive /home/travis/.wdm/IEDriverServer/3.8.0/x64/IEDriverServer.zip
```

**Comment by ransom4real** [comment]
@SergeyPirogov 1.5 seems to have fixed this issue. Thank you!
