### ISSUE TITLE
Give Manager Specific Path to Chrome

### ISSUE THREAD

**Issue by flancast90** [SergeyPirogov/webdriver_manager#329]
Hi!
I have a portable version of chrome bundled in my application, which I would like to use in conjunction with webdriver_manager. However, there seems to be no way to give webdriver_manager a path to Chrome. Is there such an option I can use, or something simple I can tweak to allow this?

**Comment by raffaem** [comment]
I was going to ask the exact same thing.

My chromium is located at `/usr/bin/chromium-freeworld`.

webdriver_manager is trying to get the location by calling `chromium --version` and can't get it.

There is a path argument, but I guess that is for the webdriver.

**Comment by aleksandr-kotlyar** [comment]
@raffaem Just add your chrome_binary file to PATH on your linux. And then webdriver-manager could find it by standard.

**Comment by aleksandr-kotlyar** [comment]
@flancast90 what OS do you use? And where do you place the installation of Chrome?

**Comment by raffaem** [comment]
> @raffaem Just add your chrome_binary file to PATH on your linux. And then webdriver-manager could find it by standard.

The path to chromium is already in PATH.

I can open it by just calling `chromium-freeworld`.

**Comment by aleksandr-kotlyar** [comment]
chromium and chromium-freeworld are different packages of chrome
webdriver_manager doesn't support chromium freeworld

but! There is a workaround

Just pass your chromium-freeworld chromium version to ChromeDriverManager and it will find the webdriver for it. 

Example how to do this is in [README.md](https://github.com/SergeyPirogov/webdriver_manager#version).

**Comment by raffaem** [comment]
> Just pass your chromium-freeworld chromium version to ChromeDriverManager and it will find the webdriver for it.

This is what I said I did in my [first message](https://github.com/SergeyPirogov/webdriver_manager/issues/329#issuecomment-1054603069) to this thread

> This is my workaround for the moment:
> ```
> version = subprocess.run([chromium_path, "--version"], text=True, capture_output=True).stdout.replace("Chromium", "").strip()
> ```

I'm passing this version to webdriver-manager.

Wouldn't it be easier to implement a way to pass the path to the browser to webdriver-manager?

**Comment by metalyc** [comment]
I'm having this same issue, except I'm using chrome beta (as version 99 is required by the latest version of chromedriver).  So this is more than an issue for custom Chrome installations.

Basically chrome beta changes the location from `.../Google/**Chrome**/Application/chrome.exe` to `.../Google/**Chrome Beta**/Application/chrome.exe`, which webdriver_manager doesn't check.

I worked around this by changing the location of chrome.exe to match webdriver_managers expectation. So far, no issues.

**Comment by flancast90** [comment]
> @flancast90 what OS do you use? And where do you place the installation of Chrome?

Kali Linux 2.0. I placed in ``Desktop/Project/Chrome``. I ended up moving from Webdriver_Manager to just a static ``set_binary`` since the version I'll distribute in my program won't update automatically.

For any looking to make a portable Chrome cross-platform, I grabbed the executable/binary path from ``chrome://version`` and included the parent-folder in my program root. On linux, this path is ``opt/google/chrome``, for example.

**Comment by aleksandr-kotlyar** [comment]
Version determination of browsers has never been the main feature of webdriver-manager library.
webdriver-manager has always been:
- First of all - it downloads the 'latest' version of webdriver. 
- Second - it downloads the version you pass to it.
- Third - as a bonus - it can determine version of browser from standard installation paths. That feature has been very raw until three latest releases and it's still not ideal. 

I will try to think how modify current project for your feature request. Seems that some parts are ready and some parts need to be modified a bit. 

@flancast90 @raffaem thank you for requesting this. I understand how important this has become since we fixed the browser version detection from default installation paths.

**Comment by aleksandr-kotlyar** [comment]
I think about not specific path - but specific command to detect browser version. Because Windows and Linux/MacOS have different commands to get browser version. And we cant unify it for Windows and Linux/MacOS in this case.

**Comment by aleksandr-kotlyar** [comment]
@flancast90 @raffaem @metalyc I have made a research and I think I have found the solution. Please check this out!

### Solution
In 3.5.3 and below
```python
from webdriver_manager.utils import read_version_from_cmd

version = read_version_from_cmd(your_command, pattern)
version = version.group(0) if version else None
```

In 3.5.4+ (commit at master https://github.com/SergeyPirogov/webdriver_manager/commit/5dd282e362c4670038175051ff43f015e0579fd5)
```python
from webdriver_manager.utils import read_version_from_cmd

version = read_version_from_cmd(your_command, pattern)
```

where `pattern` is a regexp and could be like on of these
https://github.com/SergeyPirogov/webdriver_manager/blob/5dd282e362c4670038175051ff43f015e0579fd5/webdriver_manager/utils.py#L58-L64

where `your_command` could be one of these
```python
your_command = "/usr/bin/chromium-freeworld --version"
```
or
```python
from webdriver_manager.utils import windows_browser_apps_to_cmd

your_command = windows_browser_apps_to_cmd(
    r'(Get-Item -Path "$env:PROGRAMFILES (x86)\Mozilla Firefox\firefox.exe").VersionInfo.FileVersion',
    r"(Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion",
)
```
or
```python
from webdriver_manager.utils import linux_browser_apps_to_cmd

your_command = linux_browser_apps_to_cmd(
    "chromium-freeworld",
    "chromium-freeworld-beta",
)
```

**Comment by aleksandr-kotlyar** [comment]
> @flancast90 @raffaem @metalyc I have made a research and I think I have found the solution. There is no need to implement specific paths or something else. Just a little refactoring and you can easily use functions built into webdriver-manager.
> 
> Please check this out!
> 
> ### Solution
> In 3.5.3 and below
> 
> ```python
> from webdriver_manager.utils import read_version_from_cmd
> 
> version = read_version_from_cmd(your_command, pattern)
> version = version.group(0) if version else None
> ```
> 
> In 3.5.4+ (commit at master [5dd282e](https://github.com/SergeyPirogov/webdriver_manager/commit/5dd282e362c4670038175051ff43f015e0579fd5))
> 
> ```python
> from webdriver_manager.utils import read_version_from_cmd
> 
> version = read_version_from_cmd(your_command, pattern)
> ```
> 
> where `pattern` is a regexp and could be like on of these
> 
> https://github.com/SergeyPirogov/webdriver_manager/blob/5dd282e362c4670038175051ff43f015e0579fd5/webdriver_manager/utils.py#L58-L64
> 
> where `your_command` could be one of these
> 
> ```python
> your_command = "/usr/bin/chromium-freeworld --version"
> ```
> 
> or
> 
> ```python
> from webdriver_manager.utils import windows_browser_apps_to_cmd
> 
> your_command = windows_browser_apps_to_cmd(
>     r'(Get-Item -Path "$env:PROGRAMFILES (x86)\Mozilla Firefox\firefox.exe").VersionInfo.FileVersion',
>     r"(Get-Item (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\firefox.exe').'(Default)').VersionInfo.ProductVersion",
> )
> ```
> 
> or
> 
> ```python
> from webdriver_manager.utils import linux_browser_apps_to_cmd
> 
> your_command = linux_browser_apps_to_cmd(
>     "chromium-freeworld",
>     "chromium-freeworld-beta",
> )
> ```

3.5.4 have been released. You can try 3.5.4 solution from above.

**Comment by flancast90** [comment]
Sounds great! I’ll test it out!

**Comment by aleksandr-kotlyar** [comment]
> Sounds great! I’ll test it out!

@flancast90 Thank you. I'm looking forward to feedback on this!

**Comment by flancast90** [comment]
> @flancast90 Thank you. I'm looking forward to feedback on this!

It worked the way you had sent before on Linux! 

However, I'm wondering why it has to be two separate functions (Linux, windows). Wouldn't it be easier to have one function that checks the OS and runs the necessary function based on that? 

I am imagining something like: 
`webdriver.Chrome(service=Service(ChromeDriverManager(custom_dir="path/to/chrome").install()))`

Where the function in the library could be something like (untested): 
from platform import system

```
def ChromeDriverManager(version=None, custom_dir=None):
    if version is not None and custom_dir is not None:
        raise RuntimeError("Too many args given! Please use only a custom directory OR a version")
    if custom_dir is not None: 
        if system.lower() == "windows":
            cmd = get version for windows using given dir
            return ChromeDriverManager(version=cmd)
        elif system.lower() == "linux" or system.lower() == "darwin":
            cmd = get version for linux/UNIX using given dir
            return ChromeDriverManager(version=cmd)
```

Obviously the code above would need to be refactored for production, especially so as not to waste processing time on recursive returns, but, something like that should integrate nicely with the existing function as a "quick-fix"

**Comment by aleksandr-kotlyar** [comment]
@flancast90 thank you for the idea, but it will be hard to support and to use.
We already have a workaround for not default installations of browsers.
The simplest webdriver-manager will be - the easier it will be to use.
