### ISSUE TITLE
Error when fetching gecko driver on Mac OSX

### ISSUE THREAD

**Issue by ransom4real** [SergeyPirogov/webdriver_manager#33]
I get the following error when fetching gecko driver

> Checking for mac64 geckodriver:v0.19.1 in cache
> There is no cached driver. Downloading new one...
> Getting latest mozila release info for v0.19.1
> Exception IndexError: list index out of range

**Comment by SergeyPirogov** [comment]
Oh, looks like thay changed macos links. Need to fix this for Mac in 1.5.1

**Comment by SergeyPirogov** [comment]
Fixed in 1.5.1 available via pypi
