### ISSUE TITLE
Operadriver cache file can not work in Winodws, it downloads always

### ISSUE THREAD

**Issue by carlymyy** [SergeyPirogov/webdriver_manager#338]
the operadriver archive file has extra directory, not like other drivers eg.chromedriver, when it wants to find the cache file, find wrong path

save path:"C:\Users\USERNAME\.wdm\drivers\operadriver\win64\v.98.0.4758.82\operadriver_win64\operadriver.exe"
find path:"C:\Users\USERNAME\.wdm\drivers\operadriver\win64\v.98.0.4758.82\operadriver.exe"

**Comment by aleksandr-kotlyar** [comment]
Fixed in #311 #313 wait for 3.5.4 release please :)
