### ISSUE TITLE
Allow custom webdriver path

### ISSUE THREAD

**Issue by KumaTea** [SergeyPirogov/webdriver_manager#339]
First of all thanks for this great project!

Currently there is no ARM64 (`aarch64`) version of Chrome, as well as chromedriver. 

However, there is an up-to-date ARM64 [Chromium only from the snap store](https://snapcraft.io/chromium).
And it surprisingly comes with a `/snap/bin/chromium.chromedriver` in the same version as chromium.

`webdriver_manager/chrome.py` does not support custom path yet. I will suggest:

```diff
-    def install(self):
+    def install(self, custom_path=None):
+    if custom_path:
+        return custom_path
        driver_path = self._get_driver_path(self.driver)

        os.chmod(driver_path, 0o755)
        return driver_path
```

**Comment by aleksandr-kotlyar** [comment]
Just pass this path to selenium webdriver then. webdriver-manager does not need in this case as far as I can see.

**Comment by KumaTea** [comment]
Thank you for your advice!

**Comment by aleksandr-kotlyar** [comment]
You are welcome.
