### ISSUE TITLE
Module not found webdriver-manager

### ISSUE THREAD

**Issue by magpiekingdom** [SergeyPirogov/webdriver_manager#349]
Please help me, i m getting this error
Module not found webdriver_manager

**Comment by aleksandr-kotlyar** [comment]
@magpiekingdom please show the code and how you had installed webdriver_manager.

**Comment by magpiekingdom** [comment]
@aleksandr-kotlyar from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from urllib.parse import quote
import os

**Comment by magpiekingdom** [comment]
File "C:\Users\office\OneDrive\Desktop\bholenath\automator.py", line 6, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named '

**Comment by aleksandr-kotlyar** [comment]
@magpiekingdom How did you install webdriver-manager?

**Comment by danielzwhe** [comment]
Encountered the same error, does anybody can help? thanks.
I have installed like that:
```
pip3 install webdriver-manager
```
and my code is:
```
import selenium
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

def print_hi(name):
    driver = webdriver.Chrome(ChromeDriverManager().install())
    driver.get("https://www.google.com")

if __name__ == '__main__':
    print_hi('PyCharm')
```

**Comment by danielzwhe** [comment]
hi, I have solved the issue by adding the `webdriver-manager` through python interpreter in setting.
<img width="982" alt="image" src="https://user-images.githubusercontent.com/11730005/161212622-6706c131-03db-4ab5-94d2-d2facdc0190f.png">

**Comment by aleksandr-kotlyar** [comment]
`pip install webdriver-manager` doesn't work?
or
`pip install -U webdriver-manager` if you already have previous version of webdriver-manager

**Comment by aleksandr-kotlyar** [comment]
@danielzwhe pip3 install webdriver-manager also works - i suggest that you hadn't activated venv in your console before install the library or hadn't chosen venv in pycharm, or pycharm has lagged and need to be restarted if you did all right.
Anyway I am happy you have found the solution and it's not the webdriver-manager issue.
