### ISSUE TITLE
Specify version for driver

### ISSUE THREAD

**Issue by frankvu191** [SergeyPirogov/webdriver_manager#35]
Hello,
By default, webdriver_manager will download the latest version of drivers. Can we specify the version of drivers to use?
Kind regards,
Frank

**Comment by SergeyPirogov** [comment]
Hello,

there are two options. First, you can specify version using constructor 
```
ChromeDriverManager("2.26").install()
```
Second, you can use property file

https://github.com/SergeyPirogov/webdriver_manager#configuration

**Comment by frankvu191** [comment]
Thanks
