### ISSUE TITLE
'chromedriver.exe' executable may have wrong permissions.

### ISSUE THREAD

**Issue by mdp18** [SergeyPirogov/webdriver_manager#357]
Hey there. I'm getting this error at random runs with no change in code. What could possibly be cause this?

`'chromedriver.exe' executable may have wrong permissions.`

**Comment by aleksandr-kotlyar** [comment]
Maybe your antivirus or firewall blocks it. Try to turn them off and re-check. Don't forget about default windows defender/firewall/uac system.

**Comment by aleksandr-kotlyar** [comment]
@mdp18 what version of webdriver-manager do you use?
Can you print a result of your code sample?  To let us check that path to chromedriver.exe is correct in your case.
```python
print(ChromeDriverManager(log_level=0).install(),options=chrome_options))
```
