### ISSUE TITLE
TypeError: init() got an unexpected keyword argument 'service'

### ISSUE THREAD

**Issue by drew109** [SergeyPirogov/webdriver_manager#359]
Error: 
**driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
TypeError: __init__() got an unexpected keyword argument 'service'**

**Comment by PRich13** [comment]
I got this error when using the Selenium4 example with Selenium3. Try using the Selenium3 example instead. This resolved it for me.

**Comment by drew109** [comment]
Thank you for that it fixed it
