### ISSUE TITLE
Running test in remote

### ISSUE THREAD

**Issue by frankvu191** [SergeyPirogov/webdriver_manager#36]
Hi,
Can we manage the binary to register to remote grid? Something like this in Java
public class RegisterChrome {

    public static void main(String[] args) throws Exception {
        ChromeDriverManager.getInstance().setup();
        GridLauncherV3.main(new String[] { "-role", "node", "-hub",
                "http://localhost:4444/grid/register", "-browser",
                "browserName=chrome,version=59", "-port", "5555" });
    }

}
Kind regards,
Frank

**Comment by SergeyPirogov** [comment]
Unfortunately no, because Selenium grid is written in Java
