### ISSUE TITLE
Chromedriver for Intel downloaded on Apple Silicon Mac

### ISSUE THREAD

**Issue by JG-Park** [SergeyPirogov/webdriver_manager#360]
I'm using an Apple Silicon Mac. (MacBook Pro 14")
I updated my Chrome to chrome 100. (100.0.4896.60)
Webdriver-manager downloads chromedriver for Intel architecture.
I'm using it temporarily by sneaking it over for the m1, but this should be fixed
<img width="848" alt="jgp@JGPui-MacBook-Pro-14:~ 2022-04-06 12-55-24" src="https://user-images.githubusercontent.com/50548719/161892679-1a002afd-a37f-4c32-a7fa-0a6a203b509c.png">
.

**Comment by aleksandr-kotlyar** [comment]
@JG-Park thank you for report!
What version of webdriver-manager do you use?

**Comment by JG-Park** [comment]
@aleksandr-kotlyar The result of checking the version is as follows.

![image](https://user-images.githubusercontent.com/50548719/161960659-f3aaf01c-3c53-483e-9467-78da249db5fb.png)

**Comment by aleksandr-kotlyar** [comment]
@JG-Park good! i will check the problem. Thank you!

**Comment by aleksandr-kotlyar** [comment]
@JG-Park but anyway - does it work on m1? May be just a bug in path - not in downloaded webdriver?

**Comment by JG-Park** [comment]
Sorry for the late reply.
it works. However, it works extremely slowly.
It should be downloaded with the path mac64_m1.
The chromedriver file must also be downloaded as mac64_m1.

![image](https://user-images.githubusercontent.com/50548719/163164529-efbb9f34-7fee-4464-9681-96b6e421a368.png)
![image](https://user-images.githubusercontent.com/50548719/163164612-86f215d7-188e-4295-b9f6-f6915f47fc23.png)

**Comment by JG-Park** [comment]
I think I found the cause.
When I change the path in the driver.json file like the picture, it uses the chromedriver of the m1 path.
It looks like you can fix this by referring to it.

![image](https://user-images.githubusercontent.com/50548719/163677632-d504942f-107f-4560-a5f3-19bd2594fe2c.png)

**Comment by SergeyPirogov** [comment]
I don't have a mac m1, so it's hard to debug

**Comment by SergeyPirogov** [comment]
@JG-Park It's fixed in 3.6.2, please try it
