### ISSUE TITLE
Get WebDriverException (Status code 127) when running on  gitlab-CI machine (linux)

### ISSUE THREAD

**Issue by mmonfared** [SergeyPirogov/webdriver_manager#363]
I'm getting this error while running tests on gitlab CI runner.  (even with headless):

`WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/100.0.4896.60/chromedriver unexpectedly exited. Status code was: 127`

This part is passed:
```
Get LATEST chromedriver version for None google-chrome
There is no [linux64] chromedriver for browser None in cache
Trying to download new driver from https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/100.0.4896.60]
```
What is the problem? 

Also tried this simple script. The same is here. 

```python
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
service = Service(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)

driver.get("http://google.com")
driver.find_element('name', 'q').send_keys("Wikipedia")

```

This is one of the pipelines:
https://gitlab.com/mmonfared/test/-/jobs/2350697126

This is a sample project:
https://gitlab.com/mmonfared/test

**Comment by aleksandr-kotlyar** [comment]
@mmonfared hi! Thank you for report. It seems that you have an issue with docker and gitlab.

You run your tests from Docker. Docker by default uses root user. GitLab throws an error when you try to run something in docker from root user.

Change your dockerfile a bit:
Add this row to Dockerfile
```docker
USER test
```

Your dockerfile will become something like (if i parsed your [image](https://hub.docker.com/layers/python-selenium/monfared/python-selenium/latest/images/sha256-a84ca7cb5abf1fb7cd213f39112eb8f877d6a66edb3ac21252e04e3d0ce290d0?context=explore) from hub.docker.com well) 
```
....
USER test

CMD ["python3"]

RUN /bin/sh -c pip install

COPY requirements.txt . # buildkit

RUN /bin/sh -c pip install

COPY src/ . # buildkit

CMD ["python" "trtest.py"]
```

**Comment by SergeyPirogov** [comment]
It's a problem with the chrome driver. The driver manager is not responsible for starting driver process
