### ISSUE TITLE
ModuleNotFoundError: No module named 'webdriver_manager'

### ISSUE THREAD

**Issue by StathisKap** [SergeyPirogov/webdriver_manager#364]
```
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get("http://www.python.org")
```
Gives me the same error "No module named 'webdriver_manager", no matter what I try. 
I don't know what to do

**Comment by aleksandr-kotlyar** [comment]
@StathisKap and what have you already tried?

How did you install webdriver_manager?

**Comment by StathisKap** [comment]
On my M1 Macbook

I tried:
pip3/pip install webdriver-manager
pip3/pip install webdriver_manager
pip3/pip install webdrivermanager
I also did 
brew install chromedriver

**Comment by aleksandr-kotlyar** [comment]
This doesn't matter but you dont need to use 'brew install chromedriver' if you use webdriver-manager ;) 

What's your python version?
And what's in log when you call `pip3/pip install webdriver-manager`?

Do you use virtualenv or globalenv? If virtualenv - Had you activated venv? And where did you install wdm?

**Comment by StathisKap** [comment]
ah nice. Thanks for the tip.

Python version is 3.9.12
The output when using pip3 install webdriber-manager is:
```
Defaulting to user installation because normal site-packages is not writeable
Collecting webdriver-manager
  Using cached webdriver_manager-3.5.4-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: requests in ./Library/Python/3.8/lib/python/site-packages (from webdriver-manager) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./Library/Python/3.8/lib/python/site-packages (from requests->webdriver-manager) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in ./Library/Python/3.8/lib/python/site-packages (from requests->webdriver-manager) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./Library/Python/3.8/lib/python/site-packages (from requests->webdriver-manager) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in ./Library/Python/3.8/lib/python/site-packages (from requests->webdriver-manager) (3.3)
Installing collected packages: webdriver-manager
Successfully installed webdriver-manager-3.5.4
```
I'm not sure whether I'm in a virtualenv or globalenv, but when I rn `pip3 -V` I get 
```
pip 22.0.4 from /Users/stathis/Library/Python/3.8/lib/python/site-packages/pip (python 3.8)```

and when I run 
```
import sys
sys.prefix == sys.base_prefix
```
I get True. So I think I'm not in a virtualenv.
Do I still need to avtiavle venv?


P.S - I have experience with C but I'm new to Python.

**Comment by StathisKap** [comment]
just following up on this

**Comment by aleksandr-kotlyar** [comment]
@StathisKap do you have `__init__.py` modules in your root dir of the project and in your tests dirs?

**Comment by StathisKap** [comment]
yeah. I have it like this

<img width="1514" alt="Screenshot 2022-05-11 at 06 56 26" src="https://user-images.githubusercontent.com/69547998/167778663-9c285624-6ddb-4c40-aedc-ce95e445ab75.png">

**Comment by StathisKap** [comment]
sorry, ignore the above screen shot. On that one I forgot to add the import back in.

This is the correct screenshot
<img width="1415" alt="Screenshot 2022-05-11 at 07 04 49" src="https://user-images.githubusercontent.com/69547998/167779801-33fbb70d-b2d8-403f-8718-4f7d2832dfb6.png">
