### ISSUE TITLE
Feature Request: Use Cache if Possible

### ISSUE THREAD

**Issue by Wyko** [SergeyPirogov/webdriver_manager#365]
I use this in an environment where most people are behind a VPN, and would need to get off the VPN in order to get the web driver. It would be good if I could set the `.install` method to use a local available WebDriver if possible. That way they can just use the currently installed WebDriver if one exists, and only install a new one if it doesn't exist.

Something like this:

```
cm = ChromeDriverManager().install(only_if_needed = True)
driver = webdriver.Chrome(service=Service(cm)
```

**Comment by Wyko** [comment]
Alternatively / additionally: An option to "fallback to best available cached driver" would be fantastic.

**Comment by aleksandr-kotlyar** [comment]
@Wyko hi! webdriver-manager already has this functional!
Read the docs please https://github.com/SergeyPirogov/webdriver_manager#cache_valid_range

You can set any cache time you want. For example: 365 days:
ChromeDriverManager("2.26", cache_valid_range=365).install()

**Comment by Wyko** [comment]
Certainly... except it doesn't work quite like I would hope. As a simple example, go ahead and cache an appropriate driver, then disable your network connection and run this:

`cm = ChromeDriverManager(cache_valid_range=100).install()`

Ignoring for the moment that Selenium wouldn't work; this mimics being behind a VPN that blocks your connection to the service. You'll notice you get a `ConnectionError` in `get_latest_release_version` at line `resp = requests.get(url=latest_release_url, verify=self.ssl_verify)`

I would hope that instead it would by default fall back to the most recent cached driver instead of erroring out.

**Comment by aleksandr-kotlyar** [comment]
@Wyko hi! I have checked your issue and your PR. Thank you for such an initiative to report and making the proposal solution for it.

I want to clarify the logic of webdriver-manager.
When you not set the version of webdriver you want to download - it's the "latest" by default.
To be the "latest" means: go online and check "latest" version of webdriver which is available online.
Making "fallback" is a workaround for the problem which doesn't exist because you can use the version == specific version, not "latest" and then cache=XXX will work well for this. (May be we should add this to Readme to clarify that "cache would work offline only for specific version of webdriver-manager else it will always go online".)

That's why adding fallback to cache for the online checking feature is a wrong use of webdriver-manager.

**Comment by Pavocracy** [comment]
Hey guys. I wanted to jump in here and say I was having a similar issue as @Wyko where I only wanted to use a local webdriver for a specific period of time. Funnily enough I only found the caching by accidently reading [driver_cache.py](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/driver_cache.py)

For my use case, I wanted to be able to use cached drivers, but not hardcoding a specific version that either some users might not have, or I have to constantly keep updating. But there is also the problem of sometimes we want to check if the latest version is the same. So my work around was writing my own function that checks the drivers.json file and if the timestamp is valid for a date range I choose, I pass that driver version to webdriver_manager. 

If you wanted to have a look you can find my function [here](https://github.com/Pavocracy/leetscraper/blob/main/src/leetscraper/driver.py). The code isn't great but I'm hoping you can at least get an idea of a workaround that may be suitable for you. FYI most of the code is inspired by how the actual driver_cache.py works anyway. The same thing happened for how I setup my [browser checks](https://github.com/Pavocracy/leetscraper/blob/main/src/leetscraper/system.py#L58), where much of the mechanisms came from [utils.py](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/utils.py#L135)

Hopefully this information helps :)

**Comment by SergeyPirogov** [comment]
If you already have a driver in the cache, just fix the version via the constructor parameter.
