### ISSUE TITLE
Use with Vivaldi chrometype

### ISSUE THREAD

**Issue by Ashark** [SergeyPirogov/webdriver_manager#369]
The readme misses description for Vivaldi browser, which I use. In ChromeType object I see CHROMIUM, BRAVE, MSEDGE, GOOGLE, but no **VIVALDI**.

I tried to use webdriver_manager with vivaldi as `chrome_type=ChromeType.CHROMIUM`, and it worked until now.
I made a system upgrade (I use Arch by the way), and chromium package was updated to version to 101.0.4951.41. While vivaldi-snapshot stayed at 5.3.2656.3 (uses version 100.0.4896.133 internally).

Now when I run my script, I get error:
```
from session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 100.0.4896.133
```

Uninstalling chromium made webdriver_manager confused, because it could not find its binary:
`Could not get version for chromium.Is chromium installed?`

### workaround 1
You can use [version](https://github.com/SergeyPirogov/webdriver_manager#:~:text=specify%20the%20version%20of%20webdriver%20you%20need.) parameter. As said in [drivers download page](https://sites.google.com/chromium.org/driver/downloads):

> If you are using Chrome version 100, please download ChromeDriver 100.0.4896.60

So I can use  
```python
driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM, version="100.0.4896.60").install()), options=chrome_options)
```

### workaround 2
Downgrade chromium/vivaldi and keep an eye that vivaldi's internal version and chromium version matches.

**Comment by SergeyPirogov** [comment]
Please provide more details if you can. I can not understand the source of the problem

**Comment by Ashark** [comment]
The task is to add support of a new browser type called Vivaldi. It is based on Chromium.
Vivaldi uses the usual chromium web driver. But vivaldi has their own versioning.

The task is to make webdriver manager to understand which chromium driver version is needed for the vivaldi browser.

**Comment by Ashark** [comment]
Can you please reopen?

**Comment by Ashark** [comment]
It is probably easier to fix than I think. Because as I said, webdriver manager _can_ determine the internal chromium version of vivaldi. The error message is the following:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
from session not created: This version of ChromeDriver only supports Chrome version 107
Current browser version is 106.0.5249.169  # <--- It can determine the current version!
```

**Comment by aleksandr-kotlyar** [comment]
> It is probably easier to fix than I think. Because as I said, webdriver manager _can_ determine the internal chromium version of vivaldi. The error message is the following:
> 
> ```
> selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222
> from session not created: This version of ChromeDriver only supports Chrome version 107
> Current browser version is 106.0.5249.169  # <--- It can determine the current version!
> ```

@Ashark No, It's selenium which determines the underhood version in your message.

But you are right  need the same commit as BRAVE and don't forget about updating README.md 

> There was a similar commit for brave browser: https://github.com/SergeyPirogov/webdriver_manager/commit/a28e1bb3baa1b7c50d523930b052455ccbec3cf9

You can try to make a PR 😉

**Comment by Ashark** [comment]
The Vivaldi is not added in [ChromeType](https://github.com/SergeyPirogov/webdriver_manager/blob/178a390311e297f8aba9fc20234c7398b934ed5b/webdriver_manager/core/os_manager.py#L8).
Can you please reopen?
