### ISSUE TITLE
How to get to edge latest update ?

### ISSUE THREAD

**Issue by loctruong96** [SergeyPirogov/webdriver_manager#37]
Hello,

This is more of a question than an issue. How did you get the latest version of edge? I looked at your default.ini but that link is dead for Microsoft edge. I was thinking about scraping Microsoft website to get the latest one but i think i will ask around first before doing such inefficient method.

Thank  you for any info,

Loc

**Comment by SergeyPirogov** [comment]
The correct link is https://download.microsoft.com/download/D/4/1/D417998A-58EE-4EFE-A7CC-39EF9E020768/MicrosoftWebDriver.exe

You can easily update link using a property file. Just replace old link with this one

**Comment by loctruong96** [comment]
Thanks for the reply. I know how to get to the correct link by copying the url from Microsoft. I thought Microsoft have an api where they store all of their versions and so on like google does for chrome driver. That is why i asked around on here haha. But i guess not. I will just scrap their website for new link from now on.
