### ISSUE TITLE
How to get path to cached webdriver

### ISSUE THREAD

**Issue by JayDoubleU1003** [SergeyPirogov/webdriver_manager#370]
Hi there, 

The automatic detection of browser version and downloading respective chrome driver version worked for me, and I have managed to use the browser using the path of the cached webdriver found on the terminal. 
![image](https://user-images.githubusercontent.com/44334025/166092646-5d9688c7-1c88-462c-86bc-cff4bc92923e.png)

However it still required me to manually copy and paste it to my code before it could work.
![image](https://user-images.githubusercontent.com/44334025/166092639-3c4e36d2-2456-415d-92bb-2ea2b9bdc4c3.png)

Is there any way to get a string that contains the path to the webdriver executable directly so that I don't need to copy it from the terminal?

**Comment by aleksandr-kotlyar** [comment]
Hi, @JayDoubleU1003 ! Please read the [docs](https://github.com/SergeyPirogov/webdriver_manager/blob/259cfdba30493c8835cba746683b0f14caefe0cf/README.md#use-with-chrome)
https://github.com/SergeyPirogov/webdriver_manager/blob/259cfdba30493c8835cba746683b0f14caefe0cf/README.md#L44-L60

**Comment by JayDoubleU1003** [comment]
Hi, @aleksandr-kotlyar ! thanks for your reply. I followed the docs and the installation of the chromedriver worked, but is there a method to get the path that points to the installed chromedriver in the cache as a string? 

Here's my code: 
![image](https://user-images.githubusercontent.com/44334025/166096430-7d7893aa-c72b-4937-931d-e9ad1f3012b8.png)

In line 14, I had to copy the path of the installed chromedriver that is provided in the log on the console (last line in image below) for my code to work. Is there a method to get the path as a string so that the next time chromedriver updates, I don't need to edit line 14 again?

![image](https://user-images.githubusercontent.com/44334025/166096585-48533189-1931-4a6c-a85d-eeeefecc3972.png)

**Comment by obrizan** [comment]
@aleksandr-kotlyar `ChromeDriverManager().install()` returns the path:

https://github.com/SergeyPirogov/webdriver_manager/blob/259cfdba30493c8835cba746683b0f14caefe0cf/webdriver_manager/chrome.py#L31-L35

**Comment by JayDoubleU1003** [comment]
> @aleksandr-kotlyar `ChromeDriverManager().install()` returns the path:
> 
> https://github.com/SergeyPirogov/webdriver_manager/blob/259cfdba30493c8835cba746683b0f14caefe0cf/webdriver_manager/chrome.py#L31-L35

Ahhh I see, silly me. I was abit too fixated on my older code structure. Thanks a lot for the help, code's working now
