### ISSUE TITLE
"Result: Failure Exception: WebDriverException: Message: unknown error: cannot find Chrome binary" in python code

### ISSUE THREAD

**Issue by manish-rocks** [SergeyPirogov/webdriver_manager#372]
## below is the code to install chrome driver in Linux server in azure but this script is not working the error screenshot is attached
### adding one more thing this code is written for the azure function which runs on a schedule basis

          from selenium import webdriver
          from webdriver_manager.chrome import ChromeDriverManager
          from selenium.webdriver.common.by import By
          from selenium.webdriver.chrome.options import Options
          from selenium.common.exceptions import 
           NoSuchElementException,StaleElementReferenceException,TimeoutException,ElementClickInterceptedException
          from selenium.webdriver.chrome.service import Service

          service = Service(executable_path=ChromeDriverManager().install())
          options = Options()
          options.add_argument('--disable-blink-features=AutomationControlled') ## to avoid getting detected
          options.add_argument('headless')
          
          driver = webdriver.Chrome(service= service, options=options)

<img width="655" alt="image" src="https://user-images.githubusercontent.com/37300125/167702258-6b3035a1-6345-4d4c-a729-f4cf4d70392d.png">
<img width="716" alt="image" src="https://user-images.githubusercontent.com/37300125/167702352-3610c8db-11b9-4407-88b2-0b268efd4e84.png">

**Comment by aleksandr-kotlyar** [comment]
There are two points:
1.  wdm cannot detect your installation of GoogleChrome. It's not critical because wdm has a fallback to download the latest chromedriver then.

    Do you have GoogleChrome on your azure machine or Chromium? It depends how to use wdm in this case (readme will help).

2. The final stacktrace is because Selenium (not a wdm) cannot detect your chrome binary. It's critical.

    The solution is: install browser GoogleChrome or Chromium or send selenium a path to it's installation.

    ```python
    binary_location = "/usr/bin/google-chrome" # should be your path to browser here
    options.binary_location = binary_location # binary location of your GoogleChrome or Chromium browser
    ```

**Comment by manish-rocks** [comment]
> @manish-rocks hi, thank you for the report.
> 
> There are two points:
> 
> 1. wdm cannot detect your installation of GoogleChrome. It's not critical because wdm has a fallback to download the latest chromedriver then.
>    Do you have GoogleChrome on your azure machine or Chromium? It depends how to use wdm in this case (readme will help).
> 2. The final stacktrace is because Selenium (not a wdm) cannot detect your chrome binary. It's critical.
>    The solution is: install browser GoogleChrome or Chromium to azure machine or send path of its installation to Selenium like this:
>    ```python
>    binary_location = "/usr/bin/google-chrome" # should be your path to browser here
>    options.binary_location = binary_location # binary location of your GoogleChrome or Chromium browser
>    ```

@aleksandr-kotlyar Hi, thanks for the reply. 
But as you can see I have already specified the path to chrome driver which is using this line below:
"service = Service(executable_path=ChromeDriverManager().install()) "
then why it is not able to detect the binary 🤔

plz help as webdriver-manager suggest in readme also not to specify the hard coded path instead use  this 
code " service = Service(executable_path=ChromeDriverManager().install()) ". I am confused here

**Comment by aleksandr-kotlyar** [comment]
@manish-rocks 
code
```python
service = Service(executable_path=ChromeDriverManager().install())
```
is same as
```python
driver_path = ChromeDriverManager().install()
service = Service(executable_path=driver_path)
```
I try to tell you that you need browser_path, where is your GoogleChrome or Chromium is installed.
it's 
```python
browser_path = "/usr/bin/google-chrome" # should be your path to browser here
```
so your code should be
```python
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service


service = Service(executable_path=ChromeDriverManager().install())
options = Options()
options.add_argument('--disable-blink-features=AutomationControlled') ## to avoid getting detected
options.add_argument('headless')
options.binary_location = "/usr/bin/google-chrome" # <<<<---- this row should contain path to Browser's binary location to make solve your issue
driver = webdriver.Chrome(service=service, options=options)
```

**Comment by manish-rocks** [comment]
Hi @aleksandr-kotlyar , Thanks for the solution but I think in azure function we don't have ability to install chrome browser . So is there any way to use any VM for that and what is the process to integrate that VM into the azure function code. plz help on this.

**Comment by aleksandr-kotlyar** [comment]
@manish-rocks we discovered that you don't have a browser on Azure VM or have not default installation path to the browser. 
Based on your logs webdriver-manager works well.
It's not an issue of webdriver-manager now. 
You need to find out the way to install browser on Azure VM or find the path to installed browser. And then the solution from above will work and if not - come here, we will try help you.

**Comment by zackees** [comment]
I'm running into this same bug. Setting the binary path in the ChromeOptions doesn't work. I see that the binary is being passed directly into the Service, and that that the binary is valid and the executable bits are ok.

However, it fails to find the chrome driver and an error is generated in the log.


The affected system is Ubuntu for me. It fails on a local VM running ubuntu, or on any of the test production servers I'm using. What's interesting is that THE CHROME DRIVER WORKS IN GITHUB ACTIONS. But what i see is that github actions actually has a chrome driver built in and set in the path.

To reproduce, please follow these steps:
  1. Get an Ubuntu instance without chrome driver installed.
  2. `git clone https://github.com/zackees/open-webdriver`
  3. `cd open_webdriver`
  4. `pip install -e .`
  5. The debug run `python open_webdriver/demo_app.py`

What's interesting is that it works well on Windows/MacOS without issue. I suspect the reason Ubuntu works in github is because there is already a chrome driver installed and it falls back to this.

**Comment by zackees** [comment]
I figured out the bug. Both the chrome driver and chrome need to be installed.

On ubunut I needed to install this:

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
```

**Comment by aleksandr-kotlyar** [comment]
> I figured out the bug. Both the chrome driver and chrome need to be installed.
> 
> On ubuntu it's needed to install this:
> 
> ```
> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo dpkg -i google-chrome-stable_current_amd64.deb
> ```

@zackees you are right! That's what I have talked about in my [message](https://github.com/SergeyPirogov/webdriver_manager/issues/372#issuecomment-1126494243) above. ;)

**Comment by zackees** [comment]
Yup. I wanted to be explicit so others will find this bug report.

The BIG revelation for me was that the ChromeDriver and Chrome are actually *two different products*. For half a decade I always assumed the chome driver was just a special version of the chrome codebase with an api endpoint. The fact that the driver drives an installed instance of chrome *blows my mind*.
