### ISSUE TITLE
Implement YandexDriver for YandexBrowser

### ISSUE THREAD

**Issue by Shersula** [SergeyPirogov/webdriver_manager#374]
The issue is related to Yandex browser. I failed to launch the browser using the Chromium driver, but I successfully launched it for a long time through this driver https://github.com/yandex/YandexDriver
Can I make a custom driver download or ask you to implement Yandex Driver in the Driver Manager

**Comment by aleksandr-kotlyar** [comment]
Sure! Try to make a PR.

**Comment by SergeyPirogov** [comment]
Sorry, but Yandex is a Russian company. No support will be added
