### ISSUE TITLE
pylint complains of unexpected keyword arguments since 3.7.0

### ISSUE THREAD

**Issue by Pavocracy** [SergeyPirogov/webdriver_manager#382]
dependabot put up a PR to bump webdriver_manager to version 3.7.0, but my workflow fails because pylint is giving new errors regarding unexpected keyword arguments for webdriver_manager. 

You can see the [workflow here](https://github.com/Pavocracy/leetscraper/blob/main/.github/workflows/pull_requests.yml), the [error messages here](https://github.com/Pavocracy/leetscraper/runs/6574057114?check_suite_focus=true) and the use of webdriver_manager in [my code here](https://github.com/Pavocracy/leetscraper/blob/main/src/leetscraper/driver.py).

**Comment by Pavocracy** [comment]
Was there a breaking change to webdriver_manager in 3.7.0? I can't use the `.install()` method, i get an error `ChromeDriverManager.__init__() got an unexpected keyword argument 'log_level'`

**Comment by aleksandr-kotlyar** [comment]
Hi, @Pavocracy! `log_level` and `print_first_line` were removed somewhere between 3.5.4 and 3.7.0. Read the patch notes in CHANGELOG.md and README.md of current master.

**Comment by Pavocracy** [comment]
Interesting. Fair enough. Semver usually bumps the major version when there is breaking changes to the API. If i had saw 4.0.0 i would of known why my scraper broke using webdriver)manager FYI :)

**Comment by SergeyPirogov** [comment]
Yes, sorry for that.
