### ISSUE TITLE
webdriver_manager v3.6 & 3.7 make new download issues

### ISSUE THREAD

**Issue by JE-Chen** [SergeyPirogov/webdriver_manager#383]
When I using curl -I https://api.github.com/users/JE-Chen commnad

GITHUB Response:

X-RateLimit-Limit: 60
X-RateLimit-Remaining: 57
X-RateLimit-Reset: 1653461174
X-RateLimit-Resource: core
X-RateLimit-Used: 3

```command line
HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 25 May 2022 05:47:26 GMT
Content-Type: application/json; charset=utf-8
Cache-Control: public, max-age=60, s-maxage=60
Vary: Accept, Accept-Encoding, Accept, X-Requested-With
ETag: W/"0ccdafb5bf474e393b5c1e645643c414a27e2db7efe9a74ed8677d04216e6002"
Last-Modified: Tue, 24 May 2022 11:44:09 GMT
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 57
X-RateLimit-Reset: 1653461174
X-RateLimit-Resource: core
X-RateLimit-Used: 3
Accept-Ranges: bytes
Content-Length: 1359
X-GitHub-Request-Id: E9D4:53C8:606D81:695B79:628DC2EE
```

but webdriver_manager  raise exception

ValueError: API Rate limit exceeded. You have to add GH_TOKEN!!!

**Comment by aleksandr-kotlyar** [comment]
@JE-Chen please read the docs https://github.com/SergeyPirogov/webdriver_manager/blob/master/README.md#gh_token

**Comment by JE-Chen** [comment]
but in old version like v3.5.4 i don't need add GH_Token to download firefox webdriver
when i use old version on same time i can download same webdriver without GH_Token and no error
 thank your for your response

**Comment by juliuskertscher** [comment]
I have the same problem at the moment. On an older instance, I'm running 3.5.3 which works great without a GH-Token. In theory, I shouldn't need any Token, cause I will never exceed the API limits. But after doing a fresh install on another machine, it told me to provide a Token. So I went back to the old machine and updated the version to 3.7. Now, this PC also requires a Token. Are there any reasons for the change in the last version?

PS: I can still reach the API successfully through my browser. There is no error occurring. It's just happening while using the manager.

**Comment by SergeyPirogov** [comment]
Need to investigate

**Comment by SergeyPirogov** [comment]
Fixed
