### ISSUE TITLE
ChromeDriver: Add support for "LATEST_RELEASE_"

### ISSUE THREAD

**Issue by roniemartinez** [SergeyPirogov/webdriver_manager#386]
There are extra rules to get the latest release specified in https://chromedriver.chromium.org/downloads/version-selection

As a summary, here are important notes taken from the link:

> Take the Chrome version number, remove the last part, and append the result to URL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_". For example, with Chrome version 72.0.3626.81, you'd get a URL "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_72.0.3626".
> 
> Use the URL created in the last step to retrieve a small file containing the version of ChromeDriver to use. For example, the above URL will get your a file containing "72.0.3626.69". (The actual number may change in the future, of course.)
> 
> Use the version number retrieved from the previous step to construct the URL to download ChromeDriver. With version 72.0.3626.69, the 

There are more rules included in the link.

**Comment by roniemartinez** [comment]
For reference implementation:

https://github.com/roniemartinez/dude/blob/0247c3b0e65a504ca9a28e1a633a07d58d30fe7b/dude/optional/utils.py#L69-L87

**Comment by SergeyPirogov** [comment]
Could you please submit a PR for this?

**Comment by roniemartinez** [comment]
@SergeyPirogov Sure!

**Comment by aleksandr-kotlyar** [comment]
Whats the purpouse? It already works underhood of webdriver-manager through the LATEST_RELEASE_<version>
