### ISSUE TITLE
Looks for incorrect binary for edgedriver on Linux

### ISSUE THREAD

**Issue by unixfy** [SergeyPirogov/webdriver_manager#387]
I noticed that Webdriver Manager will always try to download a new version of edgedriver on Linux, even when it's already present in the WDM cache (note that this issue does not occur on Windows).

After further testing, I noticed that this is caused by the condition [here](https://github.com/SergeyPirogov/webdriver_manager/blob/35e244ef239723dfac608ed428f217fa74a5e10d/webdriver_manager/core/driver_cache.py#L117) failing and causing find_driver to return None. 

In turn, the failed condition is caused by the value of `binary_path` looking something like this `/home/myuser/.wdm/drivers/edgedriver/linux64/102.0.1245.33/edgedriver` instead of looking like this `/home/myuser/.wdm/drivers/edgedriver/linux64/102.0.1245.33/msedgedriver` - note that it's looking for _edgedriver_ (which doesn't exist) instead of _msedgedriver_ (which does exist). `driver_binary_name` is also equal to `edgedriver` instead of `msedgedriver` at line 115 of the same file.

I was able to consistently reproduce this issue on different systems and different Linux distros, although I'm not sure why.

The workarounds I found were to:
- rename the msedgedriver binary to edgedriver in the cache directory
- remove that condition mentioned earlier
- set `driver_binary_name` to `msedgedriver`, i.e., replace [lines 110-112](https://github.com/SergeyPirogov/webdriver_manager/blob/35e244ef239723dfac608ed428f217fa74a5e10d/webdriver_manager/core/driver_cache.py#L110) with something like this:
```
driver_binary_name = "msedgedriver"
```

I don't think any of these workarounds are longterm fixes but maybe they'll provide a place to start.

**Comment by dpr10** [comment]
Actually, the solution is pretty simple, it seems the typical confusion with the variable, changing `driver_name` for `driver_binary_name`  [(here)](https://github.com/SergeyPirogov/webdriver_manager/blob/35e244ef239723dfac608ed428f217fa74a5e10d/webdriver_manager/core/driver_cache.py#L114) fixes the issue

**Comment by unixfy** [comment]
Oof, kicking myself for not catching that simple error. I opened a PR to resolve this issue. Thanks dpr10!
