### ISSUE TITLE
Progress bar for downloading new driver

### ISSUE THREAD

**Issue by Mandera** [SergeyPirogov/webdriver_manager#388]
I'm on a bad connection and couldn't for the life of me figure out why nothing was happening. Took almost a minute to download the driver with no feedback. A progress bar in the terminal would be pretty nice regardless of connection speed

**Comment by Mandera** [comment]
I made pull request #389 to add this feature, just waiting for it to be reviewed :)

**Comment by Mandera** [comment]
There is no Timeout handling, it will hang until the connection is closed. The `timeout` parameter would have to be defined [here](https://github.com/SergeyPirogov/webdriver_manager/blob/35e244ef239723dfac608ed428f217fa74a5e10d/webdriver_manager/core/http.py#L32)

**Comment by SergeyPirogov** [comment]
Left a review comment

**Comment by SergeyPirogov** [comment]
Fixed in 3.8.3
