### ISSUE TITLE
Duplicated logging messages

### ISSUE THREAD

**Issue by chesucr** [SergeyPirogov/webdriver_manager#390]
I am still getting duplicated logs when I use Webdriver Manager with Chromedriver as [this other person pointed out time ago](https://github.com/SergeyPirogov/webdriver_manager/issues/277#issuecomment-1024984195)

    ====== WebDriver manager ======
    09:54:26 INFO  >> ====== WebDriver manager ====== (logger.py:27)
    Current chromium version is 102.0.5005
    09:54:27 INFO  >> Current chromium version is 102.0.5005 (logger.py:27)
    Get LATEST chromedriver version for 102.0.5005 chromium
    09:54:27 INFO  >> Get LATEST chromedriver version for 102.0.5005 chromium (logger.py:27)
    Driver [/home/db/.wdm/drivers/chromedriver/linux64/102.0.5005.61/chromedriver] found in cache
    09:54:32 INFO  >> Driver [/home/db/.wdm/drivers/chromedriver/linux64/102.0.5005.61/chromedriver] found in cache (logger.py:27)

I am using the recommended approach with my logger (with two handlers and `setLevel`)

    FORMAT = '%(asctime)s %(levelname)-5s >> %(message)s (%(filename)s:%(lineno)d)'

    lg = logging.getLogger()
    lg.setLevel(logging.DEBUG)

    c_handler = logging.StreamHandler()
    c_handler.setLevel(logging.INFO)
    c_format = CustomFormatter(FORMAT)
    c_handler.setFormatter(c_format)

    f_handler = logging.FileHandler(ERROR_LOG, delay=True)
    f_handler.setLevel(logging.ERROR)
    f_format = logging.Formatter(FORMAT, datefmt='%H:%M:%S')
    f_handler.setFormatter(f_format)

    lg.addHandler(c_handler)
    lg.addHandler(f_handler)

The only solution I see is to disable the logging completely

    import os
    os.environ["WDM_LOG"] = "0"

But I just want to get the messages without duplication

**Comment by chesucr** [comment]
Uhm, I am using the version `3.7.1` and duplicated messages are still showing up. Is my implementation wrong?

**Comment by SergeyPirogov** [comment]
Look at README, we have WDM_LOG configuration for logs

**Comment by chesucr** [comment]
It was not helpful, but thanks for your time !!

I have tried it a little bit more on my own and I got the result I wanted by removing the wdm logger handler like this:

        lg_wdm = logging.getLogger('WDM')
        lg_wdm.removeHandler(lg_wdm.handlers[0])

This way, I keep logging propagation working, so upper logger keep getting messages. Now, the messages are not repeated because the WDM logger does not have handler to print each message again.

**Comment by andrewvaughan** [comment]
This bug shouldn't be closed - the issue persists and has nothing to do with `WDM_LOG`.

There is a duplicate log handler baked into the module that outputs directly to STDOUT.  Changing `WDM_LOG` does nothing for this. For example, this is with `WDM_LOG` off:

```
[WDM] - ====== WebDriver manager ======
2022-07-10 14:10:37,080 [    INFO ] ====== WebDriver manager ====== (WDM)
[WDM] - Current google-chrome version is 103.0.5060
2022-07-10 14:10:37,177 [    INFO ] Current google-chrome version is 103.0.5060 (WDM)
[WDM] - Get LATEST chromedriver version for 103.0.5060 google-chrome
2022-07-10 14:10:37,177 [    INFO ] Get LATEST chromedriver version for 103.0.5060 google-chrome (WDM)
[WDM] - Driver [/Users/andrewvaughan/.wdm/drivers/chromedriver/mac64/103.0.5060.53/chromedriver] found in cache
2022-07-10 14:10:37,219 [    INFO ] Driver [/Users/andrewvaughan/.wdm/drivers/chromedriver/mac64/103.0.5060.53/chromedriver] found in cache (WDM)
```

@chesucr has a solution that works, but obviously putting a workaround in your code due to a bug in a dependency is a pretty terrible pattern.
