### ISSUE TITLE
There is no Timeout handling

### ISSUE THREAD

**Issue by Mandera** [SergeyPirogov/webdriver_manager#391]
There is no Timeout handling, it will hang until the connection is closed. The `timeout` parameter would have to be defined [here](https://github.com/SergeyPirogov/webdriver_manager/blob/35e244ef239723dfac608ed428f217fa74a5e10d/webdriver_manager/core/http.py#L32)

_Originally posted by @Mandera in https://github.com/SergeyPirogov/webdriver_manager/issues/388#issuecomment-1156317255_

**Comment by SergeyPirogov** [comment]
You'd suggest adding a timeout, right? What the default value should be?

**Comment by Mandera** [comment]
In requests [issue](https://github.com/psf/requests/issues/3070#issuecomment-617781177) they mention window's default value is 240 seconds, seems like a good number

**Comment by aleksandr-kotlyar** [comment]
@Mandera you can define your own http client and pass it to webdriver-manager with any timeout connection and other settings.
