### ISSUE TITLE
Error while using Edge driver manager

### ISSUE THREAD

**Issue by kareemmahlees** [SergeyPirogov/webdriver_manager#393]
when specifying  the executable path to `EdgeChromiumDriverManager().install()` it gives the following err:
`OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software`
I tried running vs code as administrator and it doesn't work either, the strange thing is that it works with Chrome without problem?

**Comment by SergeyPirogov** [comment]
To be honest I can not help here. This requires investigation, but I don't have a Windows machine to test

**Comment by kareemmahlees** [comment]
@SergeyPirogov if you have some spare time, you can create a windows virtual machine with virtual box

**Comment by SergeyPirogov** [comment]
@SergeyPirogov The problem is related to Windows Guard (Win defender). It's blocking the driver. Try to add it to the exception or allowlist. Unfortunately, it is impossible to do this on the side of the driver manager, because it requires root privileges

**Comment by ysparrow** [comment]
Confirm the reason of issue. When you turn-off windows-defender everething works fine.
