### ISSUE TITLE
Path to binary to detect version

### ISSUE THREAD

**Issue by latot** [SergeyPirogov/webdriver_manager#395]
Hi, I'm using Gentoo, how we compile everything from 0 we try to install some apps as a bin (there is only a few packages with this), if there is no need to more need of optimization.

In this case the firefox bin is in ```/usr/bin/firefox-bin```, so:

```
driver = webdriver.Firefox(firefox_binary="/usr/bin/firefox-bin", executable_path=GeckoDriverManager().install())
[WDM] - ====== WebDriver manager ======
[WDM] - Could not get version for firefox. Is firefox installed?
[WDM] - Get LATEST geckodriver version for None firefox
[WDM] - GH_TOKEN will be used to perform requests
```

I think would be great add a param to tell where the bin is, and not just for firefox.

Thx!

**Comment by SergeyPirogov** [comment]
I think that sounds reasonable, feel free to open a PR for this.

**Comment by aleksandr-kotlyar** [comment]
@latot webdriver-manager already has this functional 
```python
from webdriver_manager.utils import read_version_from_cmd, PATTERN
version = read_version_from_cmd("/usr/bin/firefox-bin --version", PATTERN["firefox"])
driver_binary = FirefoxDriverManager(version=version).install()
```

But today firefox is a bad example cause it's not determined by browser-version == webdriver-version yet. But this will work for Google, Chromium, MSEdge well.

**Comment by raffaem** [comment]
@aleksandr-kotlyar for current version is:

```
from webdriver_manager.core.utils import read_version_from_cmd, PATTERN
version = read_version_from_cmd("/usr/bin/firefox-bin --version", PATTERN["firefox"])
driver_binary = FirefoxDriverManager(version=version).install()
```

Can we put this in the README and close this issue?

**Comment by SergeyPirogov** [comment]
@raffaem Feel free to open a PR
