### ISSUE TITLE
Offer option to choose release channel

### ISSUE THREAD

**Issue by RyuuOujiXS** [SergeyPirogov/webdriver_manager#398]
There's currently a bug in Chromium 103 that causes webdriver errors. A fix was applied in 104, but 104 is currently only available on the beta channel. Please offer an option that defaults to the release channel, but allows user to override to the beta channel. This may not be possible due to where the driver repo's are, but I haven't dived that deep into this to understand it that well.

**Comment by RyuuOujiXS** [comment]
Used 'version' parameter with beta version of Chrome. Silly meh

**Comment by SergeyPirogov** [comment]
Web Driver Manager have constructor parameter - url pointing to the source. You can put your url and try to download a driver
