### ISSUE TITLE
Add IE Driver support

### ISSUE THREAD

**Issue by SergeyPirogov** [SergeyPirogov/webdriver_manager#4]

**Comment by rafiten90** [comment]
Hi, added a pull request for this feature, I need this working for one of my projects.

**Comment by SergeyPirogov** [comment]
Good, only one question. Is there any chance to check for the latest version? I don't really like hardcoded version in ini.

**Comment by rafiten90** [comment]
Thanks for suggestion, it seems I was having very similar solution on how to retrieve latest version, here is part I just wrote but did not push anywhere because it is almost the same as the one you entered:

```
import requests
import xml.etree.ElementTree as ET

r = requests.get('http://selenium-release.storage.googleapis.com')
root = ET.fromstring(r.text)
keys = root.findall('.//{http://doc.s3.amazonaws.com/2006-03-01}Key')
ie_drivers = []
for key in keys:
    if 'IEDriverServer' in key.text:
        ie_drivers.append(key.text)

last = ie_drivers[len(ie_drivers)-1]
version = last[last.rfind('_')+1:last.rfind('.')]
```

**Comment by SergeyPirogov** [comment]
Yeah, will publish new version tomorrow

**Comment by SergeyPirogov** [comment]
@rafiten90 The new version 1.4.4 released with IE driver support included

**Comment by rafiten90** [comment]
@SergeyPirogov Just checked it and it is working as expected, thanks!

**Comment by SergeyPirogov** [comment]
Thank you for your time and contribution
