### ISSUE TITLE
Deprecate python 3.6 support

### ISSUE THREAD

**Issue by SergeyPirogov** [SergeyPirogov/webdriver_manager#400]
Python 3.6 support ended 5 years ago https://endoflife.date/python. Wdm still have the lowest version 3.6 and we have tested for this. Need to fix.

**Comment by SergeyPirogov** [comment]
@aleksandr-kotlyar can you help with this?

**Comment by aleksandr-kotlyar** [comment]
@SergeyPirogov Sure. I will do this in a few days.

**Comment by SergeyPirogov** [comment]
fixed in #402
