### ISSUE TITLE
It is possible to install specific driver versions with this package

### ISSUE THREAD

**Issue by nasiegel88** [SergeyPirogov/webdriver_manager#401]
I am having issues using the most recent geckodriver and was wondering if there is functionality for installing specific versions of drivers? Something like:
```python
driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install(version=0.15.0)))
```
From this [post](https://www.edureka.co/community/37805/what-versions-of-firefox-browser-supported-by-selenium-ide), I see Selenium no longer supports newer versions of Firefox which suggests that newer versions of geckodriver are unnecessary.

**Comment by aleksandr-kotlyar** [comment]
@nasiegel88 hi! README.md will help you with your request. Please take a look at [this](https://github.com/SergeyPirogov/webdriver_manager/blob/e7d9d584b9674d83582094616486d49a005c9614/README.md#version) part.
