### ISSUE TITLE
disabling logs stopped working after upgrading to 3.8.0

### ISSUE THREAD

**Issue by eyaler** [SergeyPirogov/webdriver_manager#407]
windows 10. python 3.9.12. selenium 4.3.0
after upgrading from 3.7.1 to 3.8.0, i am getting log printouts even with:

```
logging.getLogger('WDM').setLevel(logging.NOTSET)
os.environ['WDM_LOG'] = 'false'
```

reverting back to 3.7.1 fixed it.
i also tried deleting the cache .wdm folder but that did not help.

**Comment by hyeoni369** [comment]
yes me too
