### ISSUE TITLE
Change log location?

### ISSUE THREAD

**Issue by apacelus** [SergeyPirogov/webdriver_manager#410]
```
driver = webdriver.Firefox(log_path="./logs/geckodriver.service=FirefoxService(GeckoDriverManager().install()), options=driver_options)
```
I have the above code in my main.py file, but geckodriver.log is still saved to the same dir as main.py and not in ./log. I would like to keep logging on, but move the log file to a sub-dir. Is that possible?

**Comment by SergeyPirogov** [comment]
Hello, it's a question to Selenium webdriver. See example here https://stackoverflow.com/questions/50109910/how-do-i-relocate-disable-geckodrivers-log-file-in-selenium-python-3

**Comment by apacelus** [comment]
@SergeyPirogov thats the issue! It doesnt work. In my code above you can see I added ```log_path="./logs/geckodriver.log"``` but the log is still saved in the main dir.

**Comment by SergeyPirogov** [comment]
Its question to Selenium team
