### ISSUE TITLE
Import of module overrides my custom logger configuration

### ISSUE THREAD

**Issue by smv7** [SergeyPirogov/webdriver_manager#411]
## Context
For a custom class I create a custom logger.
This custom logger have a custom configuration (formatters and handlers with different log levels for stream and file).
The file handler saves the logs in the file with correct format; no problem.
The stream handler for the contrary, prints to standard output in the terminal console logs that should not be displayed, because those logs are configured with a specific severity level; only are displayed when they are warnings, errors or critical messages.

## I try...
moving the configuration of the logger to other parts of the file, setting the logger to be a simple variable on top of my custom class, then to be a class attribute (`self.logger`) thinking that maybe the location of the code was related, but nothing. Of course I check the quality of my logging code with the official documentation and some short python logging tutorials, to see if I was missing something. Also I try using `os.environ["WDM_LOG"] = str(logging.NOTSET)` (like the README specifies) on top of all imports (except above `import logging` obviously), then below the import of the defective class and nothing.

## I found a footprint
When commenting the import to `from webdriver_manager.firefox import GeckoDriverManager` my custom logs stop to be overridden, so the problem starts there. A piece of code executed automatically when importing that class cause the override of my custom logging configuration. Maybe the imports of other classes cause this issue as well, because `GeckoDriverManager` inherits from other classes.

## Proposal
I am a simple user of the package that clones it to take a quick look, although I don't feel prepared to scan strange source code in deep and develop a pull request (also I'm a little busy), so I expect that people better prepared that understand the code better can use this issue to solve it. Thanks for your time, reader.

**Comment by SergeyPirogov** [comment]
What version of the package do you use? Can you provide a peace of code showing the exact problem you want to solve

**Comment by smv7** [comment]
Greetings
I'm using the Pypi version (3.8.0).
The code relevant to the issue (logger configuration with `logging` and the import) looks like this:
```py
import datetime
import logging

from webdriver_manager.firefox import GeckoDriverManager  # <- This override the configuration of the stream handler.


# Creating the logger and making available to
# the handlers all severity levels.
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# Configuring handler for stream logs to be only for WARNING logs or above.
stream_handler = logging.StreamHandler()
stream_handle.setLevel(logging.WARNING)
stream_formatter = logging.Format

# Configuring handler for file logs to be for all severity levels (DEBUG logs or above).
current_date = datetime.datetime.today().strftime('%Y_%m_%d')
file_handler = logging.FileHandler(f'./log/{current_date}_{__name__}.log', mode='w', encoding='utf-8')
file_handler.setLevel(logging.DEBUG)
file_formatter = logging.Formatter('%(levelname)s %(asctime)s [%(name)s] %(message)s', datefmt='%H:%M:%S')
file_handler.setFormatter(file_formatter)

# Adding the handlers to the logger.
logger.addHandler(file_handler)
logger.addHandler(stream_handler)
```
When I tried to log DEBUG or INFO messages (severity level below the threshold of the stream handler) are printed with the default format and they should not even be displayed. But when I comment the import to `GeckoDriverManager` my logs begin to work as expected. Again, some configuration of the logger of the module overrides the configuration of my custom logger, printing all messages without considering the severity level set to them.

**Comment by SergeyPirogov** [comment]
Your logger config should be above the code with wdm

**Comment by smv7** [comment]
I tried that, don't work. All calls to my logger's log methods made below the import are overridden by the configuration of the logger of the package. This still suggest the same 2 things that I say in the 2 previous messages. I think the explanation of the issue is very clear. As a maintainer of the package, if you are too busy or you don't care (that I think is not the case because the issue received 2 answers in 2 days) or feel unwilling to develop a more friendly response, don't bother.

**Comment by SergeyPirogov** [comment]
You can look at example test https://github.com/SergeyPirogov/webdriver_manager/blob/master/tests/test_silent_global_logs.py
