### ISSUE TITLE
remove empty lines prints to stdout

### ISSUE THREAD

**Issue by eyaler** [SergeyPirogov/webdriver_manager#417]
there are some lines with print statements:

https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/core/manager.py#L16
https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/core/driver_cache.py#L20

if i install several drivers i get a block of empty lines in my terminal. more over these go to stdout so they would create an issue if my code relies on stdout pipe data flow. if these are needed, i guess these should write instead to the logger (or at least to stderr).

my temporary solution is to suppress with `with redirect_stdout(None)`

**Comment by jefferystone** [comment]
I agree that this is a problem - please allow the flag to remove blank lines as before or don't print them at all.

**Comment by SergeyPirogov** [comment]
I don't understand what kind of issues it can cause. Can you provide a real life example?

**Comment by eyaler** [comment]
e.g. if web_scrape.py uses webdriver_manager, the following CLI usage would add unexpected lines to my output file.
```
python web_scrape.py > file.txt
```

**Comment by alexanderroidl** [comment]
I agree, I'm using WDM inside a project and the empty line caused unnecessary output.

**Comment by SergeyPirogov** [comment]
Fixed in 3.8.3
