### ISSUE TITLE
Enable log (Log not showing in version 3.8.3)

### ISSUE THREAD

**Issue by MarcosBaungartner** [SergeyPirogov/webdriver_manager#423]
With version 3.8.3 the Log has stopped printing on the console window when executing a script.
I tried to put this code in the beginning to no avail:

```
import os
os.environ['WDM_LOG'] = '1'
```

**Comment by SergeyPirogov** [comment]
It's not a problem if wdm. Maybe you have some redirects?

**Comment by MarcosBaungartner** [comment]
I know, I just want it to show those information. It stopped showing after I updated to the latest version (3.8.3).
I'm referring to that initial information which begins with "====== WebDriver manager ======" on the console.

**Comment by faalbers** [comment]
I'm using logging to log into a file.
When I use:
from webdriver_manager.chrome import ChromeDriverManager

logging does not work correctly anymore. It prints in the console instead of in the log file

**Comment by SergeyPirogov** [comment]
Please provide an example

**Comment by faalbers** [comment]
If you un comment the webdriver_manager import line, the logging will not go to the 'test.log'  log file anymore. It will go to the console.
`import logging
# from webdriver_manager.chrome import ChromeDriverManager

logging.basicConfig(filename='test.log', level=logging.INFO, format='%(message)s')

logging.info('Test line in log file')
`

**Comment by MarcosBaungartner** [comment]
So, WDM 3.8.3 doesn't have this log printed on the console anymore?

![Captura de tela 2022-08-02 201149](https://user-images.githubusercontent.com/21061990/182491622-49e4ec99-2750-42a7-9bf9-3fe158c519dc.jpg)

**Comment by SergeyPirogov** [comment]
I don't believe in this. We have tests and logs are present there. Go to github actions and [see](https://github.com/SergeyPirogov/webdriver_manager/runs/7590122071?check_suite_focus=true)

**Comment by MarcosBaungartner** [comment]
I see. But for me, there is no "INFO" printed on the console, despite this, it is working fine.

**Comment by aleksandr-kotlyar** [comment]
@MarcosBaungartner please try to add pytest.ini file to your project
and put the code inside

```python
[pytest]
log_cli = 1
log_level = INFO
```
it works in all versions, now it works in 3.8.5

<img width="626" alt="image" src="https://user-images.githubusercontent.com/17043964/216825384-7f4a2af2-c9c3-40ab-8f4c-d60690c72852.png">

Have a nice day!
