### ISSUE TITLE
[Deprecation Warning] executable_path has been deprecated, please pass in a Service object

### ISSUE THREAD

**Issue by hydino2085143** [SergeyPirogov/webdriver_manager#428]
**Description of the problem**: Upon running a script using webdriver_manager, a deprecation warning is emitted in the console

**Browser and version**: Chrome 104

**Operating system**: Windows 10

**WebDriverManager version**: 3.8.3

**WebDriverManager call**: 
```python
driver = webdriver.Chrome(ChromeDriverManager().install())
```

**WebDriverManager traces**: 
```
%userprofile%\Programming\project\src\main.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
```

**Comment by SergeyPirogov** [comment]
I you go and look through README, you will find an example. You use selenium v4 it's present in the description

**Comment by Derpitron** [comment]
Why was I assigned to this issue ?

**Comment by aleksandr-kotlyar** [comment]
> Why was I assigned to this issue ?

Never mind

**Comment by Derpitron** [comment]
What?
