### ISSUE TITLE
Should raise when installing `IE` on unsupported platform? (+ potential bug 🐛 )

### ISSUE THREAD

**Issue by cmin764** [SergeyPirogov/webdriver_manager#430]
According to this [line](https://github.com/SergeyPirogov/webdriver_manager/blob/6b17f06a20d15af3635d2c5fc54657e254ceb991/webdriver_manager/drivers/ie.py#L25):
```python
self.os_type = "x64" if os_type == "win64" else "Win32"
```
you won't take into account the cases when IE will be tried to be installed on Linux/Mac. And a default Win32 version will be downloaded as a consequence.

Is that the expected behaviour?

**Comment by cmin764** [comment]
🐛 When no `os_type` is passed to the manager (and [here](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/microsoft.py#L27)) a Win32 version of the IE browser will be used even when running on 64bit. Is that expected?

Potential fix if not:
```python
self.os_type = "x64" if self.get_os_type() == "win64" else "Win32"
```

**Comment by aleksandr-kotlyar** [comment]
Give an example how to install IE on MacOS/Linux please. All I know that support of IE for mac has ended in 2005
https://ru.wikipedia.org/wiki/Internet_Explorer_for_Mac

On linux it's possible only through wine. That's not what you want to support. 

Webdriver-manager is developed for the direct usage on OSes with supportable browsers.
It has a functional for direct downloading webdriver from url you pass to it. You can use this workaround.

**Comment by aleksandr-kotlyar** [comment]
> 🐛 When no `os_type` is passed to the manager (and [here](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/microsoft.py#L27)), a Win32 version of the IE browser will be used even when running on 64bit. Is that expected?
> 
> Potential fix if not:
> 
> ```python
> self.os_type = "x64" if self.get_os_type() == "win64" else "Win32"
> ```

Yes. It is expected. You can have 32-bit IE on your win64 and need to run it this way.
