### ISSUE TITLE
Any plan to support plain Edge as well?

### ISSUE THREAD

**Issue by cmin764** [SergeyPirogov/webdriver_manager#431]
There is support for ChromiumEdge browser already, but any plan to download the Edge driver as well? (usable by `selenium.webdriver.Edge`)

**Comment by aleksandr-kotlyar** [comment]
@cmin764 Plain Edge you mean <= 44 Edge version?

**Comment by cmin764** [comment]
I guess so, I've just learnt that the support for the legacy Edge already ended, so no real need to support the discontinued flavour.
