### ISSUE TITLE
GH_TOKEN does not work - explanation unclear - please make this a warning only!

### ISSUE THREAD

**Issue by WolfgangFahl** [SergeyPirogov/webdriver_manager#433]
```bash
pip list | grep driver
webdriver-manager             3.8.3
python --version
Python 3.10.5
uname -a
Darwin ... 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
```

Today all over sudden my unit test failed with the message:
```
ValueError: API Rate limit exceeded. You have to add GH_TOKEN!!!
```
I tried to find out what the issue is and found:

https://stackoverflow.com/questions/72357156/selenium-webdriver-firefox-error-api-rate-limit-exceeded-you-have-to-add-gh-to
which points to
https://github.com/SergeyPirogov/webdriver_manager#gh_token
which points to 
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
where you end up with literally dozens of options (see screenshot below). 

**What kind of token is needed for the rate limit and how is it made working?**
I tried the token i am using for my daily github work and it doesn't seem to have any effect if i put it in the environment. The error message keeps showing up.

I created a new token setting all options and added the token to the enviroment and checked that it shows up in python
using
```
 print (os.environ['GH_TOKEN'])
```
where it is printed just fine and again **no effect**. 

Please update the documentation and stackoverflow documentation accordingly since this is very frustrating and a showstopper. 

To avoid the showstopper effect it would be just great to make this a warning only and keep working with the currently downloaded driver instead of trying to get a new one to no avail. Chances are the driver will still work (if it has been downloaded so often that the rate limit is exceeded ...)

I personally think the cache_valid_range=1 default is far too low and as a work-around i increased it way higher.

![grafik](https://user-images.githubusercontent.com/1336221/187375057-56bba16c-12e8-4cd8-a3b7-db8992641aa6.png)

**Comment by ronny-rentner** [comment]
I think usage of this token sounds highly suspicious. Why would you need a Github API token to download a gzip file from the web like https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz

**Comment by WolfgangFahl** [comment]
I am running into this problem again. https://docs.github.com/en/actions/security-guides/automatic-token-authentication is what tries to explain what to do. How is this to be applied in the context of the webdriver manager?

**Comment by aleksandr-kotlyar** [comment]
Long-long time ago, before github-actions have born the GITHUB_TOKEN was a private user variable.
Now if you use github-actions - then the recipe from above is better then creating personal token.

"Limit exceed" is not about webdriver-manager documentation - it's about github only.
The docs of wdm are clear enough I think.

**Comment by aleksandr-kotlyar** [comment]
Mark checkbox "read projects" it should be enough i think for personal token as GH_TOKEN variable for other CI-s or local usage,
