### ISSUE TITLE
How to hide webdriver manager downloading bar ?

### ISSUE THREAD

**Issue by mouadessalim** [SergeyPirogov/webdriver_manager#434]
Hey, I've searched quit a lot on how can i hide the downloading bar from printing without changing source module code. I've already tested the `os.environ['WDM_LOG_LEVEL'] = '0'` and `os.environ['WDM_LOG'] = str(logging.NOTSET)`.

![image](https://user-images.githubusercontent.com/38190847/188997850-dcb0ad33-fcc0-4bcc-b9a6-f27dc5126aac.png)

And what about this comment @SergeyPirogov : https://github.com/SergeyPirogov/webdriver_manager/pull/389#issuecomment-1177128709

> Thanks for helping ! 😊

**Comment by SergeyPirogov** [comment]
Hello, it's not possible now

**Comment by mouadessalim** [comment]
ok do you think it may possible in the futur to support it ?

**Comment by DAKExDUCK** [comment]
You can use tmux if you have some troubles with running in background.

For example, you are using `python3 main.py & disown`, your code have file logger and wdm bar trying to flush(), there will be error.
Solution:
`tmux`
`python3 main.py`
`<ctrl+b> <d>`
if you want go back to session:
`tmux attach` or `tmux attach -t N` N is a number of session 

if something is unclear, you can contact again

**Comment by mouadessalim** [comment]
@DAKExDUCK hey thanks for your reply unfortunately I don't use a linux vps to use tmux it's more of a beautifully designed windows console application that uses selenium to grab some things from the web. This is why the downloading bar broke the designed tool

You can understand better if I send you the repository : https://github.com/9P9/Discord-QR-Token-Logger

**Comment by DAKExDUCK** [comment]
@mouadessalim So, now i understand, maybe I'll try adding arguments to .install() to avoid the progress bar. But also, I'm not sure if it will get into main

Good luck!

**Comment by nakami** [comment]
It's merged. I added a PR which mentions this env variable in the README.md.

If it hasn't been clear, you can use this:

```python
import os
os.environ['WDM_PROGRESS_BAR'] = str(0)
```
