### ISSUE TITLE
Can support ARM64 for chromium?

### ISSUE THREAD

**Issue by siroo2137** [SergeyPirogov/webdriver_manager#436]
please add arm64 support:

screenshot of error:
![image](https://user-images.githubusercontent.com/72565664/189495025-c2ab74f4-b9cc-4ab0-80fe-05eaf5fa64d9.png)

**Comment by aleksandr-kotlyar** [comment]
Do selenium & Chrome working on ARM already?

**Comment by siroo2137** [comment]
yep, they work, the webdriver-manager just downloads the wrong file :)

**Comment by aleksandr-kotlyar** [comment]
You are welcome to make a PR into the project :-)

**Comment by axoroll7** [comment]
> You are welcome to make a PR into the project :-)

Some directions anyone ?

**Comment by aleksandr-kotlyar** [comment]
The answer is [above](https://github.com/SergeyPirogov/webdriver_manager/issues/436#issuecomment-1336283372). Thanks to @axoroll7! 🙂 

Here is the short version

### Resolution 

For now no releases for Linux Arm64 Chrome/Chromium on page https://chromedriver.storage.googleapis.com/

For Debian use
`sudo apt update && sudo apt install chromium chromium-driver`
and add them to PATH.

Answered. Closed.
