### ISSUE TITLE
ValueError: There is no such driver by url 

### ISSUE THREAD

**Issue by alexander-gridnev** [SergeyPirogov/webdriver_manager#443]
Hello, getting this issue:

```
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
 ```
 
After short debugging, figured out, it's due to changed format of url here: https://chromedriver.storage.googleapis.com/

it used to be:
https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip

but, for version 106.0.5249.61 it's actually became:
https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac_arm64.zip

mac64_m1.zip (old) vs mac_arm64.zip (new). Hard to say if it's permanent change, or just somebody's typo..

**Comment by alexander-gridnev** [comment]
relevant PR - https://github.com/SergeyPirogov/webdriver_manager/pull/445

**Comment by vladimir-nechaev** [comment]
It is a permanent change: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4215

**Comment by Jfromtheroc** [comment]
Its weird because it will fail in the terminal but works in my IDE

**Comment by jensVivende** [comment]
I have the latest version of webdriver-manager, and the install() keeps adding m_1 to the end of the string (before .zip) no matter what I do. Can you please make it so that if the latestReleaseUrl is set, then it uses that without modifying it?
This makes it impossible to run this on newer macs without actually downloading source code and modifying that.
Please repoen.

**Comment by chrisgraham24** [comment]
Still an issue for me...totally blocking. What is status of this?

**Comment by bmilovanovic** [comment]
Blocking me too, the code is unrunnable as of now :(

**Comment by alisatas** [comment]
I have the same issue. It's blocking me. Cant run my scripts anymore

**Comment by krishnanandv** [comment]
I'm facing the same issue, script was running fine earlier.

**Comment by Marellasai** [comment]
Upgrade to the latest version guys,  which is "webdriver-manager==3.8.4" has solved the issue.

**Comment by pokexperience** [comment]
`python3 -m pip install webdriver-manager --upgrade
python3 -m pip install packaging`

**Comment by chrisgraham24** [comment]
I still get this: "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_mac64_m1.zip"

**Comment by AlphaMoury** [comment]
> `python3 -m pip install webdriver-manager --upgrade` `python3 -m pip install packaging`

worked like a charm!

**Comment by aleksandr-kotlyar** [comment]
3.8.5 version works fine too

**Comment by jainever** [comment]
pip install webdriver-manager --upgrade
pip install packaging  
worked fine in python 3.9 as well
