### ISSUE TITLE
Browser version list update

### ISSUE THREAD

**Issue by lozik4** [SergeyPirogov/webdriver_manager#456]
How often update the browser list?
The last Edge version was in list 100 but now the last version is 108
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

**Comment by aleksandr-kotlyar** [comment]
Hi, @lozik4! How does this question affect webdriver-manager functional?

**Comment by aleksandr-kotlyar** [comment]
Update how u like.
