### ISSUE TITLE
chromedriver Version not matching with browser Version in MAC

### ISSUE THREAD

**Issue by VishO7** [SergeyPirogov/webdriver_manager#459]
Hello,
I am trying to run my selenium project in MAC, but Im getting this error about version mismatch.

`Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.119, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /var/folders/dc/x84fk4gx79z...}, goog:chromeOptions: {debuggerAddress: localhost:54478}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:54478/devtoo..., se:cdpVersion: 106.0.5249.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}`

I have tried downloading the latest chromeDriverversion but from the downloads [page](https://sites.google.com/chromium.org/driver/), it seems there is no version yet for 106.0.5249.119 

Can someone tell when this new version will be available or am i missing something ?

**Comment by aleksandr-kotlyar** [comment]
> Hello, I am trying to run my selenium project in MAC, but Im getting this error about version mismatch.
> 
> `Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.119, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /var/folders/dc/x84fk4gx79z...}, goog:chromeOptions: {debuggerAddress: localhost:54478}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:54478/devtoo..., se:cdpVersion: 106.0.5249.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}`
> 
> I have tried downloading the latest chromeDriverversion but from the downloads [page](https://sites.google.com/chromium.org/driver/), it seems there is no version yet for 106.0.5249.119
> 
> Can someone tell when this new version will be available or am i missing something ?

@VishO7 hello! Please provide example of code to reproduce and the full stacktrace you've got. I don't understand from your topic what went wrong. Today i see the driver version for MAC on the site you provided 106.0.5249.61
![image](https://user-images.githubusercontent.com/17043964/197379062-36989324-99c3-49f3-a7ac-a4cd39b0355f.png)

**Comment by elyamurza** [comment]
@aleksandr-kotlyar @VishO7 I'll chime in here from what I have discovered. It seems that chrome has renamed their mac drivers package from the usual `chromedriver_mac_m1.zip` to `chromedriver_mac_arm64.zip`.

I believe webdriver-manager is looking for the old 'm1.zip' file - and isn't finding it. due to the renaming.
