### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by alaminshakeel** [SergeyPirogov/webdriver_manager#462]
Hello, we need an immediate attention for this issue, we are stuck.
when its saying sometimes like "zipfile.BadZipFile: File is not a zip file"
please have a look at the attached image

Regards

![image](https://user-images.githubusercontent.com/10036600/200229900-d364e6a1-2904-44b8-9501-d3d8fb4309e2.png)

**Comment by aleksandr-kotlyar** [comment]
Executed in multithread?

version of wdm
python version
os version
sample code to reproduce
