### ISSUE TITLE
Driver manager installs a chrome driver of an older version after browser update (Windows)

### ISSUE THREAD

**Issue by RomanBredehoft** [SergeyPirogov/webdriver_manager#464]
I've recently encountered an issue where the `ChromeDriverManager` downloads an old chrome driver, which is incompatible with my browser's current version. After looking a bit at it, it turns out that the version of google chrome found in the registry is older than the current browser version r : 
```
reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version

HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon
    version    REG_SZ    105.0.5195.127
```
while my current browser version is `107.0.5304.107` :

```
wmic datafile where name="C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" get Version /value
Version=107.0.5304.107
```

this is an issue as the Driver manager use the registry version in order to download the (older) chrome driver, which I can't used : 
```
====== WebDriver manager ======
Current google-chrome version is 105.0.5195
Get LATEST chromedriver version for 105.0.5195 google-chrome
```

Would you know how to solve such an issue ? Also, it would be great if we could specify the browser version when instantiating a `ChromeDriverManager` object and not only a chrome driver version !

Besides, I'm using webdriver-manager's latest release
```
pip show webdriver-manager
Name: webdriver-manager
Version: 3.8.4

```

Thanks !

**Comment by aleksandr-kotlyar** [comment]
@RomanBredehoft hi! Interesting. Old browser version has been deleted or it exists in your system?

**Comment by jcdevil** [comment]
Encountering the same error with python `3.10.9` on Windows 2019, and
```
Name: webdriver-manager
Version: 3.8.5
```
Getting this kind of error : 
```
SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 110.0.5481.77 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
``` 
Thx for your help

**Comment by aleksandr-kotlyar** [comment]
@jcdevil you have had 108 chrome and upgraded it to 110, right?
Have u removed 108 or its still on your system an registry?

**Comment by jcdevil** [comment]
I indeed had 108 chrome, but the Chrome autoupdate installed 110 (Windows VM).
However, it seems that the registry is still indicating version 108 is installed.
In such case, that may be a Chrome issue then ... will check that and let you know : WDYT ?

**Comment by aleksandr-kotlyar** [comment]
> I indeed had 108 chrome, but the Chrome autoupdate installed 110 (Windows VM).
> However, it seems that the registry is still indicating version 108 is installed.
> In such case, that may be a Chrome issue then ... will check that and let you know : WDYT ?

Thank you, it would be Great! Also try to call this in powershell and attach here the result
 
 ```
(Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion'
```

**Comment by jcdevil** [comment]
Sorry but I could not access our VM. I only know that Chrome autoupdate is NOT enabled ... so that I wonder how we could get in the situation with a mismatch between the version in registry and the version of the installed Chrome. 🤷‍♂️

**Comment by aleksandr-kotlyar** [comment]
@jcdevil You can also set version manually 
```
driver_path = ChromeDriverManager(version="latest").install()
```
or
```
driver_path = ChromeDriverManager(version="110.0.5481").install()
```

The browser version determiner feature of webdriver-manager is just a bonus which could not work properly if user hadn't cleaned previous browser installation well. 

If you have autoupdate on your machine, just use "latest" version from example above 😉

**Comment by jcdevil** [comment]
@aleksandr-kotlyar : thx for your help & info.
My current code is
```
driver_path = ChromeDriverManager(path='/path/to/my/install').install()
```
so that no `version` parameter is provided; but given the code in WebdriverManager 3.8.5, to get the version is
```
    def get_version(self):
        if not self._version:
            try:
                return self.get_latest_release_version()
            except Exception:
                return self.get_browser_version()
        return self._version
```
I would expect the "latest" version to be automatically selected.
Am I missing sthg here ?

**Comment by aleksandr-kotlyar** [comment]
@jcdevil It should, but is kind of bugged.
I’ve been working on a fix for the past few days.

Till that fix I recommend you to use full version == your installed browser. That will work well.

**Comment by jcdevil** [comment]
@aleksandr-kotlyar : OK then will apply the fix then.
Notice that, for now, I rebuilt the Windows VM, so that the registry is currenlty "clean". I will keep you posted if the problem occurs again, to let you know if the fix is fine (I will apply it when the problem will occur).
Thx a lot for your help !

**Comment by aleksandr-kotlyar** [comment]
@jcdevil you are welcome!
