### ISSUE TITLE
Unable to find binary in default location on WSL2 Ubuntu

### ISSUE THREAD

**Issue by frankhuurman** [SergeyPirogov/webdriver_manager#468]
I guess this is somewhat of an edge case issue since webdriver is trying to find the actual Firefox binary which is outside of the Ubuntu that is running inside WSL and on the Windows system itself but I still wanted to share the issue:

```
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```
I get this exception while trying to run the Firefox example in the docs(with selenium 4) on Ubuntu 20.04 on WSL with Python 3.8.10.
The code:
```
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager

driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
```

**Comment by kislay-ps** [comment]
### no 'moz:firefoxOptions.binary' capability

**Full Error**
`selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line`

I am running driver-manager in Docker with following settings and getting the same error
`OS - Linux 5.15.49-linuxkit (Docker python:3.9.16-slim base image)`
```
python==3.9.16
selenium==4.7.2
webdriver-manager==3.8.5
```


The Code:

```
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager

class ConnectToLocalHostTest_Firefox(unittest.TestCase):
    def setUp(self):
        self.browser = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
        
    def test_landing_page_access_firefox(self):
        browser = self.browser
        browser.get('http://localhost:8000')
        sleep(10)
        self.assertIn("Welcome", browser.title)

if __name__=='__main__':
    unittest.main()
```

**Comment by aleksandr-kotlyar** [comment]
what is path for Firefox browser binary then? on WSL2 ubuntu and is it in the PATH var?

**Comment by Surfict** [comment]
I also have the same problem, with WSL Ubuntu 20.04

**Comment by aleksandr-kotlyar** [comment]
It's not webdriver-manager issue.
Read an error and add to selenium the path to the Firefox binary on wsl2.
