### ISSUE TITLE
un-Pythonic inconsistency in package name, installation instructions, and import command

### ISSUE THREAD

**Issue by richlysakowski** [SergeyPirogov/webdriver_manager#469]
If the package name is "webdriver_manager" then why is the installation instruction "pip install webdriver-manager". 

Remember that Python modules (files) are objects too.  Python objects cannot have a minus sign "-" character (aka hyphen or dash) in their name.  

Is it too late to update the package name to "webdriver_manager" to make it Pythonic?

**Comment by SergeyPirogov** [comment]
Can't fix
