### ISSUE TITLE
 There is no such driver by url https://chromedriver.storage.googleapis.com/71.0.3542/chromedriver_win32.zip

### ISSUE THREAD

**Issue by Mrfuhang** [SergeyPirogov/webdriver_manager#470]
# selenium 4
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromiumService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import ChromeType

driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
driver.get('https://www.baidu.com')
driver.close()

------------------------------------------------
Running the above code generates an error： There is no such driver by url https://chromedriver.storage.googleapis.com/71.0.3542/chromedriver_win32.zip

**Comment by aleksandr-kotlyar** [comment]
What was the answer @Mrfuhang ? 🙂

**Comment by ooglyboogly** [comment]
> I alread get answer.thanks

I have a fresh install of 3.8.5 and am getting the same error. Would also love to understand the answer to resolve.

**Comment by aleksandr-kotlyar** [comment]
> > I alread get answer.thanks
> 
> I have a fresh install of 3.8.5 and am getting the same error. Would also love to understand the answer to resolve.
> 
> EDIT: I have a similar issue, but different enough that I will make my own Issue

@ooglyboogly solved in 3.8.6 version of wdm
