### ISSUE TITLE
tqdm progress bar for download remains in terminal 

### ISSUE THREAD

**Issue by Pavocracy** [SergeyPirogov/webdriver_manager#472]
The [progress bar](https://github.com/SergeyPirogov/webdriver_manager/blob/3d4d9b23fc7221e52ec88a6ba143649e4efaa2d2/webdriver_manager/core/utils.py#L289) in the `show_download_progress` function does not set a value for `leave` and so uses the default value of `True`. This means the bar stays in the terminal once the download is complete. 

For a cleaner user experience (this is VERY subjective though so please give your thoughts) It would be nice if this function was changed to use `leave=False` for the tqdm progress bar.  

Or going even further, maybe exposing this as a configuration option so the user can choose the behavior? Having control over console output from WDM would be awesome (like when you added the option to turn off logging through an environment variable)

**Comment by nakami** [comment]
Yeah, as of now, it's also not possible to silence that progress bar via the environment variable meant to mute logging in general:
https://github.com/SergeyPirogov/webdriver_manager/issues/434

**Comment by Pavocracy** [comment]
This is great! I can also see your PR to add this to the documentation has been merged. Thank you very much :)
