### ISSUE TITLE
Since Chromium 109.0.5414.74, the webdriver manager not working properly

### ISSUE THREAD

**Issue by michael-m-truong** [SergeyPirogov/webdriver_manager#477]
It seems like webdriver manager does not install the correct webdriver. It started happening today. Before today, when I ran "sudo apt install -y chromium-browser" it would install version 108.0.5359.124 and the webdriver would work with the chromium version. Now running that command, it installs version Chromium 109.0.5414.74, and selenium gives me the error: This version of ChromeDriver only supports Chrome version 109 Current browser version is 108.0.5341.0 with binary path /usr/bin/chromium (even though I checked my current browser version is 109)

**Comment by michael-m-truong** [comment]
Yep I  just checked the webdriver manager downloads the webdriver version 108 instead of 109

**Comment by musabgultekin** [comment]
Is there any workaround?

**Comment by michael-m-truong** [comment]
it also looks like the binary path is set /usr/local/bin/chromium instead of chromium-browser, which seems to be the problem. I ran 
ls -al /usr/bin/chromium
sudo rm /usr/bin/chromium and then 

chrome_service = ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install())

chrome_options = Options()
options = [
    "--headless",
    "--disable-gpu",
    "--window-size=1920,1200",
    "--ignore-certificate-errors",
    "--disable-extensions",
    "--no-sandbox",
    "--disable-dev-shm-usage"
]
for option in options:
    chrome_options.add_argument(option)

driver = webdriver.Chrome('/usr/local/bin/chromium-browser', service=chrome_service, options=chrome_options)
 and it says selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist

I think i'll just manually install the chromedriver for now

**Comment by michael-m-truong** [comment]
> Having the same problem. Is there any workaround?

I did this to solve the issue: 
- name: install chromedriver manually
        run: |
          wget https://chromedriver.storage.googleapis.com/108.0.5359.22/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver

then here is my python code: 

os.environ["PATH"] += os.pathsep + '/usr/local/bin'
#chrome_service = ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install())

chrome_options = Options()
options = [
    "--headless",
    "--disable-gpu",
    "--window-size=1920,1200",
    "--ignore-certificate-errors",
    "--disable-extensions",
    "--no-sandbox",
    "--disable-dev-shm-usage"
]
for option in options:
    chrome_options.add_argument(option)

driver = webdriver.Chrome(options=chrome_options)

**Comment by musabgultekin** [comment]
Thank you!  @michael-m-truong
I was able to solve it even without putting it into usr/local/bin

I just did the first part that you posted.

wget https://chromedriver.storage.googleapis.com/108.0.5359.22/chromedriver_linux64.zip
unzip chromedriver_linux64.zip

**Comment by aleksandr-kotlyar** [comment]
Hello! Whats the code? I don't met any problem.


> It seems like webdriver manager does not install the correct webdriver. It started happening today. Before today, when I ran "sudo apt install -y chromium-browser" it would install version 108.0.5359.124 and the webdriver would work with the chromium version. Now running that command, it installs version Chromium 109.0.5414.74, and selenium gives me the error: This version of ChromeDriver only supports Chrome version 109 Current browser version is 108.0.5341.0 with binary path /usr/bin/chromium (even though I checked my current browser version is 109)

It means you have 2 browsers: GoogleChrome and Chromium? Or you just installed new version of Chromium and now have 2 Chromium browsers?

**Comment by aleksandr-kotlyar** [comment]
> sudo apt install -y chromium-browser

I have read 10 more times. And seems that webdriver-manager does all well. But somehow you don't put the right binary location to new version of browser.

Please use the code below next time:
```python
binary_location = '/usr/bin/chromium-browser' # or another u need to use in case

option = webdriver.ChromeOptions()
option.binary_location = binary_location
driver_path = ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()
driver = webdriver.Chrome(service=ChromiumService(driver_path)
```
That would solve your first comment issue. 

P.S. what you have done after I couldn't really understand because the root cause was Selenium couldnt see right version of chromium. webdriver-manager did all well - you installed 109 - it downloaded 109. Just take a look at the code above - the issue was in your selenium usage in your case. Not the webdriver-manager issue.

Have a nice day!
