### ISSUE TITLE
GeckoDriver on aarch 64 Linux

### ISSUE THREAD

**Issue by sameer** [SergeyPirogov/webdriver_manager#479]
Hello,

The Github release page for geckodriver includes builds for linux-aarch64. Would it be possible to configure those downloads?

That way, the Gecko driver will work out of the box on ARM 64-bit devices.

**Comment by kuro2052** [comment]
I am using raspi os. Currently the webdriver manager is downloading the linux64 driver instead of aarch64 which will not work. Is there any way to make it download the aarch64 one. Are there any parameters I can put?

**Comment by aleksandr-kotlyar** [comment]
You can send url to wdm download driver you need.

**Comment by kaliiiiiiiiii** [comment]
@aleksandr-kotlyar guess those should work [stack-overflow answer](https://stackoverflow.com/a/57586200/20443541)

**Comment by aleksandr-kotlyar** [comment]
> @aleksandr-kotlyar guess those should work [stack-overflow answer](https://stackoverflow.com/a/57586200/20443541)

@kaliiiiiiiiii ty for such a page, i think it will be helpful for arm64 enthusiasts 👍 
But in my previous message I have meant this functional of webdriver-manager:
```python
GeckoDriverManager(url="https://github.com/mozilla/geckodriver/releases/download/v0.32.2/geckodriver-v0.32.2-win-aarch64.zip").install()

ChromeDriverManager(url="https://github.com/electron/electron/releases/download/v16.0.6/chromedriver-v16.0.6-linux-arm64.zip").install()
```

**Comment by MoofyWoofy** [comment]
Hello

I tried doing 

```py
web_driver = webdriver.Firefox(service=Service(GeckoDriverManager(url="https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux-aarch64.tar.gz").install()), options=options)
```

but it gives `OSError: [Errno 8] Exec format error: '/home/melvin/.wdm/drivers/geckodriver/linux64/0.33/geckodriver'`
Am I doing it wrong?

**Comment by kuro2052** [comment]
There is a parameter called os_type in driver manager. I using that and it's working fine.
`driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager(os_type="linux-aarch64").install()))`

**Comment by MoofyWoofy** [comment]
It works now. Thank you very much! :)

**Comment by iamtalhaasghar** [comment]
Why `webdriver_manager` downloads `linux64` geckodriver at the first place in a `aarch64` type system?
