### ISSUE TITLE
Check for driver latest version once a day

### ISSUE THREAD

**Issue by maratori** [SergeyPirogov/webdriver_manager#48]
Here is an idea.

## What?

Cache not only binary of the driver but the latest version number as well. And update this number, let's say once a day.

## Why?

How frequently drivers are updated? Not very much.
But we waste time on each test run for requesting the latest version from the internet.
Such caching can speed up testing.

**Comment by SergeyPirogov** [comment]
Good point. Any ideas how to invalidate cache? Check only once a day?

**Comment by Maratori** [comment]
I think we can go straight forward. Use some file `.wdm/latest_versions` where to store for each driver: latest version and time when we got it. Then check this file. If elapsed time is more than configured, request again and update the file.
The only think we should be aware of is issues with parallel writing to that file.
