### ISSUE TITLE
Why on "Raspberri Pi latest" wdm 3.8.5 downloads chromedriver_linux32 which not exist?

### ISSUE THREAD

**Issue by ooglyboogly** [SergeyPirogov/webdriver_manager#482]
System:
Raspberry Pi latest running on a Pi Zero W

Code being used:
```
        opts = Options()
        opts.binary_location = '/usr/bin/chromium-browser'
        opts.add_argument("--headless")
        opts.add_argument("--hide-scrollbars");
        opts.add_argument('--force-device-scale-factor=1')
        driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()),options=opts)
```
Error: 
`There is no such driver by url https://chromedriver.storage.googleapis.com/110.0.5481.77/chromedriver_linux32.zip `

Any suggestions on why it is trying to call a URL that seems to not exist?

**Comment by aleksandr-kotlyar** [comment]
Webdriver-manager determines your os type as linux 32 bit.
And Google hadn’t not released chrome driver for linux32 bit.
Thats why.

**Comment by aleksandr-kotlyar** [comment]
You can try to find driver for your OS on this page  https://chromedriver.storage.googleapis.com/

And tell us which one works on your operating system.

**Comment by aleksandr-kotlyar** [comment]
Same question as https://github.com/SergeyPirogov/webdriver_manager/issues/436
Answered in comment https://github.com/SergeyPirogov/webdriver_manager/issues/436#issuecomment-1427042421
