### ISSUE TITLE
When will python 3.11 be compatible?

### ISSUE THREAD

**Issue by sryu1** [SergeyPirogov/webdriver_manager#483]
I was planning to use this when it becomes available for python 3.11, is there any time when it will work with 3.11?

**Comment by aleksandr-kotlyar** [comment]
Any proofs that its not?

**Comment by aleksandr-kotlyar** [comment]
> I was planning to use this when it becomes available for python 3.11, is there any time when it will work with 3.11?


Now tested webdriver-manager 3.8.5 on python 3.11.1. MacOS 10.14.6. All tests passed.
