### ISSUE TITLE
why this happening?

### ISSUE THREAD

**Issue by mobile1021** [SergeyPirogov/webdriver_manager#488]
![image](https://user-images.githubusercontent.com/90590106/221532844-b40100db-a35c-400e-ac28-1bc47ca34467.png)
![image](https://user-images.githubusercontent.com/90590106/221532983-9da1a0fe-b6d1-4cff-9877-fe18cac78741.png)
![image](https://user-images.githubusercontent.com/90590106/221534361-8662a8d9-036c-457c-b8ca-eab7329bfc88.png)

My code worked fine until a few days ago.
What's the cause of the sudden errors?

**Comment by mobile1021** [comment]
![image](https://user-images.githubusercontent.com/90590106/221534314-53ab5225-3f14-48c4-a361-31cbaaf9dc15.png)

**Comment by aleksandr-kotlyar** [comment]
I dont see error here from webdriver manager. 

Please attach full stacktrace in codeblock and describe where is webdriver manager error in it.

Till that i close it as invalid.

Fill free to reopen when you will have more descriptive details.
