### ISSUE TITLE
webdriver_manager opens google chrome instead of brave

### ISSUE THREAD

**Issue by bennaaym** [SergeyPirogov/webdriver_manager#489]
### Issue
Although I specified Brave as the browser type, Webdriver Manager is still executing tests on Chrome instead of Brave.

```py
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import ChromeType


webdriver.Chrome(service=ChromeService(ChromeDriverManager(chrome_type=ChromeType.BRAVE).install()))
```

### Expected Behavior
Test to be run on Brave browser

### Environment

Python: 3.9.0
WebDriver Manager: 3.8.5
OS: Win 10

**Comment by aleksandr-kotlyar** [comment]
@bennaaym hi! Go to readme and make opera example for your brave. You need pass binary location to browser into your selenium.

Not a webdriver manager issue. Close.

**Comment by bennaaym** [comment]
@aleksandr-kotlyar, thank you for clarifying. It seems that the current documentation may be lacking information regarding the process of passing a binary. It would be beneficial to update the documentation to include this important detail to ensure that users have a complete understanding of the tool. 

https://pypi.org/project/webdriver-manager/

**Comment by aleksandr-kotlyar** [comment]
@bennaaym yep. But somehow brave still starts by selenium on my test machines without any binary option. I have all browsers installed. If the problem has been massive there were more issues. You can always open a PR if you sure that something not documented well or works fine.
