### ISSUE TITLE
Pattern Minor Issue

### ISSUE THREAD

**Issue by sebieire** [SergeyPirogov/webdriver_manager#496]
The below will truncate correct version and then cause an error when trying to install the same version.

Example Pattern:
`ChromeType.CHROMIUM: r"\d+\.\d+\.\d+",`

For Chromium Browser version 111.0.5563.64. This will truncate the ".64".
Then "ChromeDriverManager(version=VERSION).install()" actually fails.

**Comment by aleksandr-kotlyar** [comment]
Please look at readme examples of usage. You are trying your own thing which wdm not expect. Provide full version without pattern and your code will work.
