### ISSUE TITLE
Support for cygwin?

### ISSUE THREAD

**Issue by macnewbold** [SergeyPirogov/webdriver_manager#497]
I spent a while trying to debug "Exception: Can not find browser google-chrome installed in your system!!!" before I started checking the source code, and found that in Cygwin Linux-like POSIX environment on Windows, sys.platform returns "cygwin" but found that webdriver_manager utils.py OSType class only supports Linux, Mac, or Windows. Is there any interest in a patch that would make cygwin be a recognized platform as well?

**Comment by aleksandr-kotlyar** [comment]
Hi, @macnewbold! Thank you for your report. This exception will disappear soon in next release 😉 It has already been removed from master branch here.
Anyway if you still interested in cygwin console support, i think we will not add it.
You can use webdriver-manager with setting os_type
```python
ChromeDriverManager(os_type="win64").install()
```
