### ISSUE TITLE
Public Binary Path

### ISSUE THREAD

**Issue by ryansherby** [SergeyPirogov/webdriver_manager#499]
Publicize binary_path variable to allow users to check if the executable exists within dynamic default installation location without immediately initiating installation if it is not found.

**Comment by aleksandr-kotlyar** [comment]
@ryansherby hi, binary path of what?

**Comment by ryansherby** [comment]
@aleksandr-kotlyar The binary path that _get_driver_path returns when called during the .install() method of a (e.g.,Chrome)DriverManager instance. I'm asking if it is possible to access the driver_path binary path variable without initiating the os.chmod installation

**Comment by aleksandr-kotlyar** [comment]
> @aleksandr-kotlyar The binary path that _get_driver_path returns when called during the .install() method of a (e.g.,Chrome)DriverManager instance. I'm asking if it is possible to access the driver_path binary path variable without initiating the os.chmod installation

@ryansherby what's wrong with os.chmod command?

**Comment by ryansherby** [comment]
Nothing is wrong with the os.chmod command, I just wanted to know if it is possible to return the driver_path variable without needing to begin the installation with os.chmod. As it stands, the only way to fetch the driver path is after it is returned by the install() function.

There are some cases where I'd like to check the dynamically-constructed driver path to see if the driver.exe is installed, and if it is not installed, to _not_ install it immediately. Basically, what the internal _get_driver_path function does.

**Comment by aleksandr-kotlyar** [comment]
@ryansherby okay, you can set ChromeDriverManager(path=...) and wdm will check first there, and if cache invalid or driver not exist on path - it will download it there.
Also there is WDM_LOCAL os env variable which can be used for project relative paths with `path=` also.
