### ISSUE TITLE
Inside docker container driver manager do not use config.ini file and always download latest driver version

### ISSUE THREAD

**Issue by KursLabIgor** [SergeyPirogov/webdriver_manager#50]
I use docker for running test. 
```
Create folder .wdm in $HOME directory. 
$HOME in my case  = /root
copy to $HOME/.wdm config.ini file. (result path /root/.wdm) 
Run test 
Will be downloaded latest driver anyway.
```
But same flow locally work perfect for Windows and MacOS system. 
Do you have some idea where can be problem? 
Script output even when config.ini file is same folder and point to v0.20.1 version
> Checking for linux64 geckodriver:v0.21.0 in cache
> There is no cached driver. Downloading new one...
> Getting latest mozila release info for v0.21.0
> Trying to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
> Unpack archive /root/.wdm/geckodriver/v0.21.0/linux64/geckodriver-v0.21.0-linux64.tar.gz

**Comment by SergeyPirogov** [comment]
@KursLabIgor you should say offline true

**Comment by itereshchuk** [comment]
Even if driver should be downloaded ? driver v0.20.1 should be downloaded since on system it absent.

**Comment by SergeyPirogov** [comment]
@itereshchuk can't understand your case. Please give a bit more description about your use case

**Comment by itereshchuk** [comment]
Ok. My use case the following. 
1. Start docker 
2. Download geckodriver **not latest** version (for it i copy config.ini where specify exact version) and start tests
Expected: 
That exact version from config.ini will be downloaded
Actual: 
Always latest version downloaded.

**Comment by SergeyPirogov** [comment]
Try to use the latest version of driver manager *1.7*. I've added support for ENV VARIABLES, so now you can set driver version by setting ENV VARIABLE VERSION=v0.20.1. This should work

**Comment by itereshchuk** [comment]
OK

**Comment by itereshchuk** [comment]
So what format of env should be? 
geckodriver=v0.20.1 and for config.ini file remove it?

**Comment by SergeyPirogov** [comment]
Just set 
```
VERSION=v0.20.1
```

**Comment by itereshchuk** [comment]
OK, thanks
