### ISSUE TITLE
Version Issue - Mismatch With Chromium Driver - Chromium / Chrome Examples Please - Pattern Problem Generates Invalid Chromedriver Download Link

### ISSUE THREAD

**Issue by sebieire** [SergeyPirogov/webdriver_manager#501]
Hi! Thanks for your help in advance with this.

This relates to previously already described but closed issues for example here:
https://github.com/SergeyPirogov/webdriver_manager/issues/500 and from me here https://github.com/SergeyPirogov/webdriver_manager/issues/496 as well

This error keeps happening. Latest example happened today with a result of:

_This version of ChromeDriver only supports Chrome version 112
Current browser version is 111.0.5563.110 with binary path /usr/bin/chromium_ which will make selenium crash.

Evidently the version was just updated to 112. I am using Chromium. After some testing I've realised that the 'read_version_from_cmd' function doesn't always work properly (Pattern issue?) so I had already attempted to change it in my previous ticket. Please read on to see what I mean.

The above is already from the fallback I've built in which means **if the original pattern wasn't recognised it will default to download the latest version**. I'll show below what I mean to follow and hopefully reproduce the steps.

In your examples you have given this:
```
from webdriver_manager.core.utils import read_version_from_cmd, PATTERN
version = read_version_from_cmd("/usr/bin/firefox-bin --version", PATTERN["firefox"])
driver_binary = FirefoxDriverManager(version=version).install()
```

Could you please give the same example for Chromium / Chrome to see how you make this work. Below is the issue with my code (simple example that actually fails):

```
from webdriver_manager.core.utils import read_version_from_cmd, PATTERN, ChromeType
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.service import Service

browser_version = read_version_from_cmd("/usr/bin/chromium-browser --version", PATTERN[ChromeType.CHROMIUM]) #<<--- exchange with 'GOOGLE' is the same result
driver_binary = ChromeDriverManager(version=browser_version).install()
driver = webdriver.Chrome(service=Service(driver_binary))
```
Running this with version 111.0.5563 at the moment. This will attempt to download from the following URL: https://chromedriver.storage.googleapis.com/111.0.5563/chromedriver_linux64.zip
If you follow it you see the problem which results in the following Error:
**_ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/111.0.5563/chromedriver_linux64.zip_**

The correct link should be: https://chromedriver.storage.googleapis.com/111.0.5563.19/chromedriver_linux64.zip

So I believe the "PATTERN" (which I've also tried manually - see my previous ticket - and got it then to work occasionally) creates an issue leading to the wrong download link.

The other side problem of this is as follows: As I said above my fallback is that it will download the latest version if everything else fails. But that means if there is a new release of chromedriver the process will mismatch with Selenium freaking out to the initial error I've described. With the above version link failing to a URL that is non existent it will download the latest version and then there is a mismatch resulting in Selenium to fail.

The function 'read_version_from_cmd' can return Null (based off the version of Chromium/Chrome) which means the `driver_binary` will be invalid but no Error is thrown here so it is difficult to recognise this problem as it isn't evident what actually fails. My initial workaround involved a Pattern list that will test until a Pattern matches and does not return Null anymore.

Trivial example: `Pattern_List = ["\d+\.\d+\.\d+.\d+.\d+.\d+", "\d+\.\d+\.\d+.\d+.\d+", "\d+\.\d+\.\d+.\d+", "\d+\.\d+\.\d+"]` The problem is while one pattern in the list might work and not return Null it doesn't check if the generated URL actually exists. That's the missing step here leading to the main issue of the incorrect download-link.

I hope this makes it clearer as to what I meant in my original post and now with this issue arising again with the new version being released.

For me one added problem is that I am running this all in a Docker container otherwise I could just update Chromium/Chrome with every new release of chromiumdriver. But that isn't as straight forward in the container and I can't check/re-deploy it every time a new chromiumdriver gets released.

Thank you very much for your help with this. 👍

**Comment by aleksandr-kotlyar** [comment]
Dont use pattern and it will be ok.

**Comment by sebieire** [comment]
Thanks for the reply.

You mean like this basically? 

```
driver_binary = ChromeDriverManager().install()
driver = webdriver.Chrome(service=Service(driver_binary))
```
Will this auto detect the correct version chromiumdriver according to chromium browser?

Thanks

**Comment by sebieire** [comment]
PPS: Ok I can confirm that it doesn't work unfortunately. I've just tested it in a docker setup as well.

My code is (more less like that- just the important parts):

PART A:
```
CACHE_RANGE_DAYS = X
browser_version = read_version_from_cmd("/usr/bin/chromium-browser --version", PATTERN[ChromeType.CHROMIUM])
driver_binary = ChromeDriverManager(version=browser_version, cache_valid_range=CACHE_RANGE_DAYS).install()
driver = webdriver.Chrome(options=chrome_options, service=Service(driver_binary))

```

And when that fails I use this as backup.

PART B:
```
driver_binary = ChromeDriverManager(version=browser_version, cache_valid_range=CACHE_RANGE_DAYS).install()
driver = webdriver.Chrome(options=chrome_options, service=Service(driver_binary))
```

Which then also fails with the following errors:

_Error: Message: session not created: This version of ChromeDriver only supports Chrome version 112
Current browser version is 111.0.5563.110 with binary path /usr/bin/chromium_

**Comment by aleksandr-kotlyar** [comment]
@sebieire you can use this code for a while, sometimes it will not work for Chromium. But for GoogleChrome it should.

```python
browser_version = read_version_from_cmd("/usr/bin/chromium-browser --version")
driver_binary = ChromeDriverManager(version=browser_version).install()
driver = webdriver.Chrome(service=Service(driver_binary))
```
but better to wait new release with fix.

Or you can set version of your browser directly by
```python
driver_binary = ChromeDriverManager(version="111.0.5563.110").install()
driver = webdriver.Chrome(service=Service(driver_binary))
```

**Comment by sebieire** [comment]
Thanks very much for your reply @aleksandr-kotlyar!
I will test it out asap soon as I can and report back here. One one question :)

Doesn't the 'read_version_from_cmd' function require 2 parameters? 
That would make `read_version_from_cmd("/usr/bin/chromium-browser --version")` invalid?

**Comment by aleksandr-kotlyar** [comment]
> Doesn't the 'read_version_from_cmd' function require 2 parameters? That would make `read_version_from_cmd("/usr/bin/chromium-browser --version")` invalid?

Sure, ty, fixed this one.
