### ISSUE TITLE
Driver is not cached

### ISSUE THREAD

**Issue by baterflyrity** [SergeyPirogov/webdriver_manager#503]
Hi! 

Very nice tool, thanks a lot.

I am using wdm with firefox portable edition (windows 10 x64). Unfortunately I can not see any driver caching at all.

Can someone please explain me is it possible and how?

```python
webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
```

> [WDM] - Downloading: 19.2kB [00:00, 2.80MB/s]                   
> [WDM] - Downloading: 19.2kB [00:00, 4.90MB/s]                   
> [WDM] - Downloading: 100%|██████████| 1.59M/1.59M [00:00<00:00, 1.91MB/s]
> [WDM] - Downloading: 19.2kB [00:00, 3.89MB/s] 
> [WDM] - Downloading: 19.2kB [00:00, 3.87MB/s]

**Comment by Muddyblack** [comment]
![image](https://user-images.githubusercontent.com/70057554/232159562-618f38c4-f505-42c8-9b4f-f9d8987116b3.png)

Try it with a specifc path.
But yeah normally it should be cached... Does it download new every time you run the script or only after a specifc period of time?

**Comment by aleksandr-kotlyar** [comment]
upgrade to 3.8.6 and check if still actual?

**Comment by baterflyrity** [comment]
@Muddyblack , thanks for reply. Actually this could be fixed with just `@functools.cache`.

@aleksandr-kotlyar , thanks for tip. Yes, actually after upgrade from 3.8.5 to 3.8.6 wdm doesnt redownload driver neither on each call, nor on each session/script execution!

**Comment by aleksandr-kotlyar** [comment]
@baterflyrity cool! Thank you for the feedback!
