### ISSUE TITLE
Selenium ChromeDriver on RaspberryPi - needs support added for correct driver branch

### ISSUE THREAD

**Issue by GoodnessJSON** [SergeyPirogov/webdriver_manager#507]
I would love to use this driver manager on a Raspberry Pi, but it errors out every time and says it can't find an eligible version.

If I use this chromedriver version listed here - https://ivanderevianko.com/2020/01/selenium-chromedriver-for-raspberrypi

Then it works fine in Selenium, but as its a separate package it will always have to be manually matched to the Chrome version.

Could support be added for Raspberry Pi's according to the above?

**Comment by aleksandr-kotlyar** [comment]
@GoodnessJSON hi! Thank you for using wdm library and suggestion such an improvement.

Honestly, it could be possible to increment suggested feature only when it will be a public table with matching versions of webdriver and chromium for pi.

**Comment by aleksandr-kotlyar** [comment]
Not able to do cause no public resources to match versions.
