### ISSUE TITLE
WebDriver manager Unable to download chromedriver，the download address has been lost

### ISSUE THREAD

**Issue by lj1998008** [SergeyPirogov/webdriver_manager#509]
WebDriver manager Unable to download chromedriver， the download address has expired
the download address：https://chromedriver.storage.googleapis.com/112.0.5615/chromedriver_win32.zip
the download address has been lost

run WebDriver manager：
Get LATEST chromedriver version for google-chrome 112.0.5615
About to download new driver from https://chromedriver.storage.googleapis.com/112.0.5615/chromedriver_win32.zip
the download address：https://chromedriver.storage.googleapis.com/112.0.5615/chromedriver_win32.zip
the download address has been lost

**Comment by aleksandr-kotlyar** [comment]
@lj1998008
Whats version of wdm?
What is code sample to reproduce?
Whats in the wdm logs?

**Comment by aleksandr-kotlyar** [comment]
@lj1998008 upgrade wdm to 3.8.6
