### ISSUE TITLE
Work with google credentials on Chrome's browser

### ISSUE THREAD

**Issue by samuelsennev** [SergeyPirogov/webdriver_manager#510]
Is there any way I can set the driver to use my google credentials, so I can use my own settings? (without setting them manually in the driver)

I've tried a few ways and the closest I've got was opening the browser with the driver, passing some args, such as "--profile-directory" and "--user-data-dir", to use my google account, and it kind off worked until this point, but nothing further. It got stuck on that "new-tab"'s default page, didn't open any site I've asked to.

**Comment by aleksandr-kotlyar** [comment]
@samuelsennev this library only downloads the webdriver and gives examples how to pass it to selenium webdriver. All what you want to do with it next is not relevant for the webdriver-manager. If you have a question how to use selenium please ask in selenium community. 

Best regards
