### ISSUE TITLE
Use of webdriver_manager from command line

### ISSUE THREAD

**Issue by BoPeng** [SergeyPirogov/webdriver_manager#511]
I am wondering if a command line interface could be provided to install drivers from command line, which could save the effort to check driver each time. I mean, instead of

```
python -c 'from webdriver_manager.firefox import GeckoDriverManager; GeckoDriverManager().install()'
```

This package could provide something like

```
python -m webdriver_manager.firefox install
```

even simply

```
webdriver_manager install firefox
```

The reason for this request is that I am building a Docker image with firefox, selenium etc, and it is easier to install the driver beforehand, instead of trying to install it each time the selenium driver starts.

**Comment by aleksandr-kotlyar** [comment]
No cli in plans afaik.

@BoPeng here are some solutions for this

> instead of trying to install it each time the selenium driver starts.

1. Use `cache_valid_range=10000` from readme examples - it will solve this.
2. you can use selenium/standalone-firefox and the same for chrome image - they already comes with matching browser and webdriver
3. you can write cmd in docker which will install webdriver and browser from the same repository like ubuntu - they should be synchronised by versions

Choose whats better match to you.

**Comment by BoPeng** [comment]
Thanks for the quick response. The first two solutions do not work because I want to "bake" the driver with the image to avoid downloading drivers later, and my docker image is based on Ubuntu and `apt-install firefox`.  Option 3 is the most suitable solution for me, although I will need to check what package to use. 

I still do not quite understand why you do not want to provide something like `install-webdriver` to automate the permanent installation of web drivers, in addition to cached installation through Python script. It would certainly be useful for the test environment on my local computer.

**Comment by SergeyPirogov** [comment]
Selenium has an official webdriver-manager cli
