### ISSUE TITLE
Unable to download Edge driver

### ISSUE THREAD

**Issue by iamernie8199** [SergeyPirogov/webdriver_manager#512]
it seems like the download address is dead
"https://msedgedriver.azureedge.net/LATEST_RELEASE"

**Comment by aleksandr-kotlyar** [comment]
> it seems like the download address is dead
> "https://msedgedriver.azureedge.net/LATEST_RELEASE"

@iamernie8199 provide code to reproduce and the stacktrace you get.
Have you edge browser installed?
What webdriver-manager version do you use?
What is os architecture and version where you run the webdriver-manager?
