### ISSUE TITLE
ChromeDriver with latest chrome browser version my code was not running. It was unable to locate the web element

### ISSUE THREAD

**Issue by karthik1896** [SergeyPirogov/webdriver_manager#519]
ChromeDriver with latest chrome browser version my code was not running. It was unable to locate the web element .

==================================================================================
Chrome Browser Version : 114.0.5735.91

**Comment by MouradZoghbiWork** [comment]
Try with 

 my_options.add_argument("--window-size=1920,1080")

or 

my_options.add_argument("--start-maximized")

**Comment by karthik1896** [comment]
> Try with
> 
> my_options.add_argument("--window-size=1920,1080")
> 
> or
> 
> my_options.add_argument("--start-maximized")

Still I'm facing the issue

**Comment by aleksandr-kotlyar** [comment]
Not webdriver-manager issue.
