### ISSUE TITLE
Specifying an empty version doesn't work anymore in 3.8.6

### ISSUE THREAD

**Issue by rnestler** [SergeyPirogov/webdriver_manager#520]
Previously specifying `""` as the version to use would just do the right thing and installing the latest version for the currently installed browser version. Now it raises an error:
```
E           packaging.version.InvalidVersion: Invalid version: ''

../../../../.cache/pypoetry/virtualenvs/buhler-qualib-bWkKix15-py3.9/lib/python3.9/site-packages/packaging/version.py:198: InvalidVersion
```

Originating from `../../../../.cache/pypoetry/virtualenvs/buhler-qualib-bWkKix15-py3.9/lib/python3.9/site-packages/webdriver_manager/drivers/chrome.py:45`

Using `"latest"` doesn't work, since it will install an incompatible version in my CI environment:
```
E       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
E       Current browser version is 113.0.5672.126 with binary path /usr/bin/google-chrome
```

Also specifying something like `LATEST_RELEASE_113` (as found on https://chromedriver.storage.googleapis.com/) doesn't work:
```
  File "/home/raphael/.cache/pypoetry/virtualenvs/minimal-webdriver-manager-example-5c0ipZHv-py3.11/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'LATEST_RELEASE_113'
```

**Comment by aleksandr-kotlyar** [comment]
> Previously specifying `""` as the version to use would just do the right thing and installing the latest version for the currently installed browser version. Now it raises an error:
> 
> ```
> E           packaging.version.InvalidVersion: Invalid version: ''
> 
> ../../../../.cache/pypoetry/virtualenvs/buhler-qualib-bWkKix15-py3.9/lib/python3.9/site-packages/packaging/version.py:198: InvalidVersion
> ```
> 
> Originating from `../../../../.cache/pypoetry/virtualenvs/buhler-qualib-bWkKix15-py3.9/lib/python3.9/site-packages/webdriver_manager/drivers/chrome.py:45`
> 
> Using `"latest"` doesn't work, since it will install an incompatible version in my CI environment:
> 
> ```
> E       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
> E       Current browser version is 113.0.5672.126 with binary path /usr/bin/google-chrome
> ```
> 
> Also specifying something like `LATEST_RELEASE_113` doesn't work:

What version when it worked and what version when its not? 
You can set nothing. And it will download version matches your browser version in most common cases on 3.8.6

What version of browser?
What is the path to your browser? 
is your browser bin in PATH variable?

**Comment by aleksandr-kotlyar** [comment]
Just do not specify, use example from Readme.

**Comment by rnestler** [comment]
@aleksandr-kotlyar Fair enough. It's just a bit annoying that the behavior in that regard changes often in patch releases. Previously I had to change it to `""` since `"latest"` didn't work anymore and now I have to change again.

But in the end the solution with passing `None` to do the auto-detection seems to be nice.

**Comment by aleksandr-kotlyar** [comment]
> @aleksandr-kotlyar Fair enough. It's just a bit annoying that the behavior in that regard changes often in patch releases. Previously I had to change it to `""` since `"latest"` didn't work anymore and now I have to change again.
> 
> 
> 
> But in the end the solution with passing `None` to do the auto-detection seems to be nice.

Yeah, I understand your pain. There were a lot of bugs after previous modifications. If only had known that fix will break such thing i would upgrade to 3.9.0 ;-)
