### ISSUE TITLE
Run as a remote server

### ISSUE THREAD

**Issue by erickmourasilva** [SergeyPirogov/webdriver_manager#521]
How to use webdriver-manager as a remote server?

The idea is to have the python code running on a server and another server with only chrome and webdriver-manager (standalone remote)

How can I connect this way?

**Comment by aleksandr-kotlyar** [comment]
@erickmourasilva i dont get your idea. What problem do you want to solve with such separation python code from webdriver-manager code? And why do you want to keep webdriver-manager near standalone browser? How do you see your schema will work?

Draw a sequence diagram on PlantUML orthen think about what do you want to run and where. It will definitely help you to find the best solution.

**Comment by SergeyPirogov** [comment]
Use selenium grid for this. Wd manager will not help here
