### ISSUE TITLE
error with firefox when executing in docker

### ISSUE THREAD

**Issue by MouradZoghbiWork** [SergeyPirogov/webdriver_manager#522]
When execute selenium test in docker and after adding theses lines

my_options = FirefoxOptions()
            my_options.add_argument('-headless')
            my_options.headless = True
            # my_options.add_argument("--accept_insecure_certs")
            # my_options.add_argument("--set_window_rect")
            
            my_options.add_argument("--no-sandbox")
            # my_options.add_argument("--single-process")
            # my_options.add_argument("--disable-dev-shm-usage")
            
            driver_binary = GeckoDriverManager().install()
            driver = webdriver.Firefox(
                service=FirefoxService(driver_binary), options=my_options
            )

I get this error : "message":"Failed to read marionette port"

**Comment by adrianwbsf** [comment]
Hi, this link is broken inside package:
        url: str = "https://github.com/mozilla/geckodriver/releases/download",

This is inside class **GeckoDriverManager**.
Path: webdriver_manager/firefox.py

**Comment by aleksandr-kotlyar** [comment]
> Failed to read marionette port"

@MouradZoghbiWork hi! How did you install firefox in Docker? Is it snap installation?
Anyway try to provide firefox browser binary path into selenium also.
