### ISSUE TITLE
[bug] Webdriver Download reaches 100% then hangs

### ISSUE THREAD

**Issue by Derpitron** [SergeyPirogov/webdriver_manager#523]
**Description of the problem**: Upon running a program which uses webdriver-manager, it downloads the latest webdriver and outputs the completion status to the console. But, upon reaching 100% completion, it seems to hang.

![image](https://github.com/bonigarcia/webdrivermanager/assets/46134462/6f2c27f4-ab09-494f-980f-1b06bc869eab)

**Browser and version**: Chrome 114.0.5735.134 (Official Build) (64-bit) (cohort: Stable) 

**Operating system**: Windows 11

**WebDriverManager version**: webdriver-manager 3.8.6

**WebDriverManager call**: https://github.com/Derpitron/Discord-OTP-Forcer/blob/81818ed1339f2a6ace936dd8264df4ecee6f9ec4/src/backend.py#L37

**WebDriverManager traces**: No logs appear at all.

**Error log**: No errors appear at all.

Related: https://github.com/Derpitron/Discord-OTP-Forcer/issues/64, https://github.com/Derpitron/Discord-OTP-Forcer/issues/63

**Comment by aleksandr-kotlyar** [comment]
> **Description of the problem**: Upon running a program which uses webdriver-manager, it downloads the latest webdriver and outputs the completion status to the console. But, upon reaching 100% completion, it seems to hang.
> 
> ![image](https://user-images.githubusercontent.com/46134462/246496059-6f2c27f4-ab09-494f-980f-1b06bc869eab.png)
> 
> **Browser and version**: Chrome 114.0.5735.134 (Official Build) (64-bit) (cohort: Stable)
> 
> **Operating system**: Windows 11
> 
> **WebDriverManager version**: webdriver-manager 3.8.6
> 
> **WebDriverManager call**: https://github.com/Derpitron/Discord-OTP-Forcer/blob/81818ed1339f2a6ace936dd8264df4ecee6f9ec4/src/backend.py#L37
> 
> **WebDriverManager traces**: No logs appear at all.
> 
> **Error log**: No errors appear at all.
> 
> Related: [Derpitron/Discord-OTP-Forcer#64](https://github.com/Derpitron/Discord-OTP-Forcer/issues/64), [Derpitron/Discord-OTP-Forcer#63](https://github.com/Derpitron/Discord-OTP-Forcer/issues/63)

@Derpitron Antivirus may be? Or strict politics? If it is try to disable and repeat.

**Comment by Derpitron** [comment]
> > **Description of the problem**: Upon running a program which uses webdriver-manager, it downloads the latest webdriver and outputs the completion status to the console. But, upon reaching 100% completion, it seems to hang.
> > ![image](https://user-images.githubusercontent.com/46134462/246496059-6f2c27f4-ab09-494f-980f-1b06bc869eab.png)
> > **Browser and version**: Chrome 114.0.5735.134 (Official Build) (64-bit) (cohort: Stable)
> > **Operating system**: Windows 11
> > **WebDriverManager version**: webdriver-manager 3.8.6
> > **WebDriverManager call**: [Derpitron/Discord-OTP-Forcer@`81818ed`/src/backend.py#L37](https://github.com/Derpitron/Discord-OTP-Forcer/blob/81818ed1339f2a6ace936dd8264df4ecee6f9ec4/src/backend.py#L37)
> > **WebDriverManager traces**: No logs appear at all.
> > **Error log**: No errors appear at all.
> > Related: [Derpitron/Discord-OTP-Forcer#64](https://github.com/Derpitron/Discord-OTP-Forcer/issues/64), [Derpitron/Discord-OTP-Forcer#63](https://github.com/Derpitron/Discord-OTP-Forcer/issues/63)
> 
> @Derpitron Antivirus may be? Or strict politics? If it is try to disable and repeat.

No change so far.
