### ISSUE TITLE
in multi process, I can not install webdirver

### ISSUE THREAD

**Issue by DevLSeH** [SergeyPirogov/webdriver_manager#524]
```
s = Service(ChromeDriverManager().install())
                self.driver = webdriver.Chrome(
                    service=s, options=options)
```
when I use this code in multiprocess(python 3.7 concurrent.futrue), code not work
but it work well when install webdriver first and using multi process

why I can't install driver with multi process?

runing device is macOS.m2

**Comment by DevLSeH** [comment]
runing device is macOS.m2

**Comment by SergeyPirogov** [comment]
What webdriver-manager version do you use? Provide simple code snippet that reporduce an issue

**Comment by DevLSeH** [comment]
version 3.8.6

sample code
```
pool = concurrent.futures.ProcessPoolExecutor(max_workers=20)

@atexit.register
def sig_handler():
    log.info("try to dispose process pool")
    pool.shutdown(wait=True)
    log.info("finish dispose")

def sample():
    try:
        ChromeDriverManager().install()
        log.info("install chromedriver in main method")
    except Exception as e:
        log.warning("install chromedriver is failed")
        log.error(e)

def main():
    futures = []
    futures.append(pool.submit(sample))
    futures.append(pool.submit(sample))

    for future in futures:
        try:
            result = future.result()
            log.info(result)  # check success or error
        except Exception as e:
            log.error(f"{e}\n{traceback.format_exc()}")
```
when i use this code, it takes error about process adopt exited

so i was solved this problem like this
```
def main():
    try:
        ChromeDriverManager().install()
        log.info("install chromedriver in main method")
    except Exception as e:
        log.warning("install chromedriver is failed")
        log.error(e)

    futures = []
    futures.append(pool.submit(sample))
    futures.append(pool.submit(sample))

    for future in futures:
        try:
            result = future.result()
            log.info(result)  # check success or error
        except Exception as e:
            log.error(f"{e}\n{traceback.format_exc()}")
```
then, it work well
i think the problem is that cant download webdriver in multiprocess

it doesnt matter when webdriver is downloaded already, only problem when need download something

**Comment by SergeyPirogov** [comment]
Yes, because it download driver in same folder. I've solved this for pytest,  but in such case we have to invent some wheel. There is env variable PYTEST_XDIST_WORKER, try to set it unique for every process and it should work

**Comment by DevLSeH** [comment]
then, is it pretty good solution that my code?
about install in main() method first and doing multi processing

**Comment by peppelongo96** [comment]
Same to me. I need more info about. @DevLSeH i agree with you since i got all well after restart. The first concurrent process went well, the second not. At restart this last one could download the file.

@SergeyPirogov what do you think about?  Could be an issue using the same webdriver? in principle not i think, since is what is done by UC for example that incorporates a webdriver for all process.

**Comment by SergeyPirogov** [comment]
@peppelongo96 Ive provided a solution above

**Comment by peppelongo96** [comment]
> @peppelongo96 Ive provided a solution above

I have like 50 process. It's not a solution for me mate...

**Comment by DevLSeH** [comment]
@peppelongo96 
my problem was can not download driver in multiprocess.
but your problem is not my case, because you can running first process and it has problem in second process.
can you check driver download path?
i think it's problem is can not found downloaded driver

**Comment by peppelongo96** [comment]
> @peppelongo96 my problem was can not download driver in multiprocess. but your problem is not my case, because you can running first process and it has problem in second process. can you check driver download path? i think it's problem is can not found downloaded driver

problem is on unzipping downloaded chromedriver. In the sense that since each process is overriding each downloading part of chromedriver, could be conflict on this for sure. So some processes go to error and some not. So my problem is the same of yours, they are just concurrent cases.

Ya just to answer to your question, the only set downloading path is the default one
