### ISSUE TITLE
Webdriver for Chrome does not work in Google Colab

### ISSUE THREAD

**Issue by ivanovmp** [SergeyPirogov/webdriver_manager#525]
I created a python notebook which simply install two packages and runs the code from [here](https://github.com/SergeyPirogov/webdriver_manager):
```
!pip install selenium webdriver-manager

# selenium 4
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
```

However, this snippet runs into the following error:
```
WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x557a6b28e4e3 <unknown>
#1 0x557a6afbdc76 <unknown>
#2 0x557a6afe4757 <unknown>
#3 0x557a6afe3029 <unknown>
#4 0x557a6b021ccc <unknown>
#5 0x557a6b02147f <unknown>
#6 0x557a6b018de3 <unknown>
#7 0x557a6afee2dd <unknown>
#8 0x557a6afef34e <unknown>
#9 0x557a6b24e3e4 <unknown>
#10 0x557a6b2523d7 <unknown>
#11 0x557a6b25cb20 <unknown>
#12 0x557a6b253023 <unknown>
#13 0x557a6b2211aa <unknown>
#14 0x557a6b2776b8 <unknown>
#15 0x557a6b277847 <unknown>
#16 0x557a6b287243 <unknown>
#17 0x7fb14cfe5609 start_thread
```
You can find the notebook in question [here](https://colab.research.google.com/drive/159hbtBReBmlNiG22C7R0zjjIrFdAOvTy?usp=sharing).

**Comment by SergeyPirogov** [comment]
There is no google chrome installed, that's why it will not work in this situation

**Comment by ivanovmp** [comment]
Well, as it's told in the desctiption of the project, the aim of `webdriver_manager` is to avoid boring steps of downloading and extracting binaries, then telling Selenium the path to those. So this packages only helps with downloading the Chrome driver but not Chrome Browser itself, doesn't it? If so, could you please suggest a way to also install Chrome Browser in as convenient way as possible?

**Comment by SergeyPirogov** [comment]
This project helps to manage Chrome driver only. Try to google how to install browser independently
