### ISSUE TITLE
Not able to fetch specified version of edge driver

### ISSUE THREAD

**Issue by aaravgotra** [SergeyPirogov/webdriver_manager#53]
local_driver = webdriver.Edge(EdgeDriverManager(version='3.14393').install())
Not able to fetch specified edge driver version(3.14393).

Version Details---
webdriver_manager==1.6.0
Selenium == 3.11
Python == 2.7

**Comment by SergeyPirogov** [comment]
Unfortunately, there is no  chance to fetch edge driver by version because of Microsoft website https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by SergeyPirogov** [comment]
Edge is deprecated
