### ISSUE TITLE
http.py raise NameError exception if network is offline

### ISSUE THREAD

**Issue by prrvchr** [SergeyPirogov/webdriver_manager#530]
Hi,

Thank for this great API.
I just noticed that an NameError occurs when the network is offline instead of the requests connection exception.
The name of the `exceptions` module is just missing in front of the `ConnectionError` exception in the [http.py](https://github.com/SergeyPirogov/webdriver_manager/blob/9c0b2187a5d453cca8e8db115efb2070e944bd82/webdriver_manager/core/http.py#L36) file

**Comment by SergeyPirogov** [comment]
@prrvchr please provide a fix or suggestion how to fix

**Comment by prrvchr** [comment]
I make [pull request](https://github.com/SergeyPirogov/webdriver_manager/pull/544)
