### ISSUE TITLE
Backport to python 2.7.18

### ISSUE THREAD

**Issue by prrvchr** [SergeyPirogov/webdriver_manager#531]
Hi,

I'm trying to integrate Selenium and webdriver_manager into an [OAuth2OOo](https://prrvchr.github.io/OAuth2OOo/) extension already providing OAuth2 services in LibreOffice and/or OpenOffice.

The integration of selenium in LibreOffice is carried out thanks to Calc formulas allowing:
- To open the browser
- Fill in a field.
- Fill out a form
- Click on a link/button
- Get and parse the content of the HTML page

If I want to remain compatible with OpenOffice I am obliged as long as they have not migrated to python 3 to support python 2.7.18 in the OAuth2OOo extension. That's why I'm currently only using selenium version 3 and had to backport webdriver_manager to python 2.7.18.

I have created a fork for this [backport](https://github.com/prrvchr/webdriver_manager) and am interested in any good information to help me succeed.

Anyway thank you for this excellent API.

**Comment by prrvchr** [comment]
The [backport](https://github.com/prrvchr/webdriver_manager) under python 2.7.18 has been made.

I cannot use the progress bar under python 2, the [buffer](https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/core/utils.py#L263) `bytearray()` it uses causes a decoding error when the Request.Response.json() method is called.

I haven't found a workaround but it's not really a problem since I don't need this progress bar.

**Comment by SergeyPirogov** [comment]
Open a PR
