### ISSUE TITLE
There is no such driver by url 

### ISSUE THREAD

**Issue by RPAroyalface** [SergeyPirogov/webdriver_manager#538]
Hi Alexander, how are you fine?

Today when I ran my code the following error appears:

There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

And when checking the latest version of Webdriver_manager, I realized that it did not match what appears in https://chromedriver.storage.googleapis.com/LATEST_RELEASE -> 114.0.5735.90

def __init__(
            self,
            version: Optional[str] = "114.0.5735.90", -> I manually changed it so the code could run
            os_type: Optional[str] = None,
            path: Optional[str] = None,
            name: str = "chromedriver",
            url: str = "https://chromedriver.storage.googleapis.com",
            latest_release_url: str = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE",
            chrome_type: str = ChromeType.GOOGLE,
            cache_valid_range: int = 1,
            download_manager: Optional[DownloadManager] = None,
    )

**Comment by moh-nex** [comment]
Will be resolved via https://github.com/SergeyPirogov/webdriver_manager/pull/537

**Comment by SergeyPirogov** [comment]
Fixed in 3.9.0
