### ISSUE TITLE
chromium version 115.0.5790

### ISSUE THREAD

**Issue by SSAdvisor** [SergeyPirogov/webdriver_manager#546]
The key isn't being pulled for the install. What can I do to resolve this? I entered the URI manually and it doesn't exist. I pulled the entire list and it doesn't exist.

**Comment by SergeyPirogov** [comment]
Update chrome browser and try again

**Comment by SSAdvisor** [comment]
I tried that before creating the issue but the version for my system was at its current version.  Now the weirder part is that I'm using a Chrome OS Linux Container. So I find it strange that Google would be removing something related from its API. I've used web-manager successfully in the past couple of weeks or so.

**Comment by kenricnguyen** [comment]
When using webdriver-manager v3.8.5 and Selenium v3.141.0   on Windows 11(64bit) v22H2, the Python code below failed:
`driver = webdriver.Chrome( executable_path=ChromeDriverManager().install())`
I received the below error:
`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip`.

Looking into the link in the url above, there is no version 115.0.5790. The last version is 114.0.5735.90 for win32.zip edition. Is there a way for us to fall back to the previous available version with this webdriver-manager version?

**Comment by SudhanshuBlaze** [comment]
> When using webdriver-manager v3.8.5 and Selenium v3.141.0 on Windows 11(64bit) v22H2, the Python code below failed: `driver = webdriver.Chrome( executable_path=ChromeDriverManager().install())` I received the below error: `ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip`.
> 
> Looking into the link in the url above, there is no version 115.0.5790. The last version is 114.0.5735.90 for win32.zip edition. Is there a way for us to fall back to the previous available version with this webdriver-manager version?
> 
> Note that the Python code above hasn't failed before from my various experiments in the past few weeks.

Update webdriver_manager to latest version, should work out

**Comment by JDShadowline** [comment]
It looks like google has changed the way they release the webdriver for chrome bast v115. See [https://googlechromelabs.github.io/chrome-for-testing/](https://googlechromelabs.github.io/chrome-for-testing/) for more info.

With that said it looks like this is accounted for and fixed by updating the webdriver-manager to the latest version like @SudhanshuBlaze mentions above.

**Comment by SSAdvisor** [comment]
@kenricnguyen I found the script to download the latest version of chromium. Here is the result `Exception: No such driver version 117.0.5908 for linux64`

@JDShadowline that isn't what @SudhanshuBlaze said. He was asking to downgrade webdriver-manager. I'm thinking of falling back to 3.7.1 to see if that helps me but ...

-pip uninstall webmanager-driver
pip install webmanager-driver==3.7.1-

**Comment by SSAdvisor** [comment]
https://chromedriver.storage.googleapis.com/LATEST_RELEASE

is currently giving a result of:

114.0.5735.90

This doesn't sound correct.

Based on the URL that  @JDShadowline  gave us the current version is the one titled in this issue.

**Comment by SSAdvisor** [comment]
@SergeyPirogov  and that doesn't work either.

**Comment by EGTomKies** [comment]
I'm hitting a similar issue: 

This is the version of webdriver-manager I have installed:

`Collecting webdriver-manager
PS C:\githubfiles\ecp\test_automation> pip show webdriver-manager
Name: webdriver-manager
Version: 3.9.1
Summary: Library provides the way to automatically manage drivers for different browsers
Home-page: https://github.com/SergeyPirogov/webdriver_manager
Author: Sergey Pirogov
Author-email: automationremarks@gmail.com
License: 
Location: c:\program files\python310\lib\site-packages
Requires: packaging, python-dotenv, requests
Required-by: `

My version of Chrome is:   Version 115.0.5790.99 (Official Build) (64-bit)

Initially we were getting the 'no url exists' type message, but after the update to 3.9.1 I'm getting:  

`        Specification: c:\githubfiles\ecp\test_automation\specs\localtesting\ta3557.spec:4
        Error Message: No such driver version 115.0.5790.99 for win32
        Stacktrace: 
        Traceback (most recent call last):
          File "C:\Users\tom.kies\AppData\Roaming\Python\Python310\site-packages\getgauge\executor.py", line 33, in execute_method
            step.impl(*params)
          File "c:\githubfiles\ecp\test_automation\step_impl\shared_impl\drivers\eg_drivers.py", line 733, in connect_to_web_browser
            create_web_driver(browser)
          File "c:\githubfiles\ecp\test_automation\step_impl\shared_impl\drivers\eg_drivers.py", line 755, in create_web_driver
            driver = webdriver.Chrome(ChromeDriverManager().install(),port=default_port)
          File "C:\Program Files\Python310\lib\site-packages\webdriver_manager\chrome.py", line 39, in install
            driver_path = self._get_driver_binary_path(self.driver)
          File "C:\Program Files\Python310\lib\site-packages\webdriver_manager\core\manager.py", line 33, in _get_driver_binary_path
            file = self._download_manager.download_file(driver.get_driver_download_url())
          File "C:\Program Files\Python310\lib\site-packages\webdriver_manager\drivers\chrome.py", line 59, in get_driver_download_url
            modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)
          File "C:\Program Files\Python310\lib\site-packages\webdriver_manager\drivers\chrome.py", line 94, in get_url_for_version_and_platform
            raise Exception(f"No such driver version {browser_version} for {platform}")
        Exception: No such driver version 115.0.5790.99 for win32`

**Comment by SergeyPirogov** [comment]
I will check it. Maybe win32 is not correct system name

**Comment by SSAdvisor** [comment]
So, what is occurring is that the browser_version is missing the 4th element of the version when it is passed into the get_url_for_version_and_platform function. So my 115.0.5790 full version is 115.0.5790.98 so the equality test in the loop is failing even though my version is listed in the json data.

**Comment by SSAdvisor** [comment]
For now I'm managing this issue by directly specifying the driver_version when I call the ChromeDriverManager. BUT, I shouldn't have to hard code it!

**Comment by demon071** [comment]
```python
def get_url_for_version_and_platform(self, browser_version, platform):
        url = "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
        response = self._http_client.get(url)
        data = response.json()
        versions = [version for version in data['versions'] if browser_version.split('.')[0] in version['version'] and 'chromedriver' in version['downloads']]
        max_version = versions[0]
        for v in versions:
            if v["version"] == browser_version:
                downloads = v["downloads"]["chromedriver"]
                for d in downloads:
                    if d["platform"] == platform:
                        return d["url"]
            elif version.parse(v['version']) < version.parse(browser_version) and version.parse(v['version']) > version.parse(max_version['version']):
                max_version = v
        downloads = max_version["downloads"]["chromedriver"]
        for d in downloads:
            if d["platform"] == platform:
                return d["url"]

        raise Exception(f"No such driver version {browser_version} for {platform}")
```
try replacing this function

**Comment by JasonCrowe** [comment]
We are experiencing this problem on Mac as well. We have updated Chrome and run pip upgrade. This is the result now.

![Screenshot 2023-07-25 at 8 21 37 AM](https://github.com/SergeyPirogov/webdriver_manager/assets/1906730/8bea74ff-ff07-4c6b-a83d-cf7856d61c2e)

**Comment by SergeyPirogov** [comment]
This is a bug in chromedriver

**Comment by SSAdvisor** [comment]
@SergeyPirogov Why did you close this? Is the issue with getting the version from the system binary losing the 4th element when driver_version isn't specified resolved?

**Comment by SergeyPirogov** [comment]
Provide an example

**Comment by SSAdvisor** [comment]
`from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromiumService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.os_manager import ChromeType

_options = webdriver.ChromeOptions()
_options.add_argument("--headless")
_options.add_experimental_option("excludeSwitches", ["enable-automation"])
_options.add_experimental_option('useAutomationExtension', False)
driver = webdriver.Chrome( service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()),options=_options)
`

**Comment by SSAdvisor** [comment]
@SergeyPirogov was my previous comment a good enough example?

**Comment by JasonCrowe** [comment]
> This is a bug in chromedriver

Is it possible that it's connected to this issue? I have three Mac Python scripts that all stopped working with this thread's bug. When I updated Chrome and webdriver-manager this is the result I get.
