### ISSUE TITLE
Extracted chromedriver for mac_arm64 / 115.0.5790.102 is not executable

### ISSUE THREAD

**Issue by bschuetze** [SergeyPirogov/webdriver_manager#547]
Hey, 
I am trying to update a, previously working, webdriver_manager and selenium application to work with the new chrome release methods (as discussed in #536).
After updating to 3.9.1, I now get a new issue:

```text
Trimmed Error:

PermissionError: [Errno 13] Permission denied: '/Users/user/.wdm/drivers/chromedriver/mac_arm64/115.0.5790.102/chromedriver-mac-arm64/chromedriver'

...

selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

Checking using `ls`, we can see that the executable perm is missing.

```bash
ls -al@ /Users/user/.wdm/drivers/chromedriver/mac_arm64/115.0.5790.102/chromedriver-mac-arm64/
total 31064

...

-rw-r--r--@ 1 user\group  15661456 24 Jul 13:07 chromedriver
```

I don't know if this related to the recent changes to how chrome is releasing, or perhaps a selenium issue. However adding the following (testing hack) resolves the error:

```python
# File: core/driver_cache.py
import stat

# ...

def save_file_to_cache(self, driver: Driver, file: File):
        path = self.__get_path(driver)
        archive = self.save_archive_file(file, path)
        files = self.unpack_archive(archive, path)
        binary = self.__get_binary(files, driver.get_name())
        binary_path = os.path.join(path, binary)
        self.__save_metadata(driver, binary_path)
        # Set executable permissions (FIX HERE)
        if self._os_system_manager.get_os_name() == "mac":
            current_perms = os.stat(binary_path)
            os.chmod(binary_path, current_perms.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        log(f"Driver has been saved in cache [{path}]")
        return binary_path
```

**Comment by SergeyPirogov** [comment]
Please provide a PR

**Comment by duncanariey** [comment]
Seeing the same issue, also on an M1 Mac; hoping a follow-up release to fix might be possible. 

@bschuetze do you know if there a way to manually add that missing executable perm in the meantime? Doing `chmod 755` on the chromedriver file causes Selenium to be unable to find the Chrome binary

**Comment by yuhymuk** [comment]
@bschuetze I've added your fix locally but it has not worked for Mac M1

**Comment by bschuetze** [comment]
> Seeing the same issue, also on an M1 Mac; hoping a follow-up release to fix might be possible.
> 
> @bschuetze do you know if there a way to manually add that missing executable perm in the meantime? Doing `chmod 755` on the chromedriver file causes Selenium to be unable to find the Chrome binary

This is a chromedriver bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1466427

Temp fix is to add this line to chrome options: `options.binary_location = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"`

**Comment by bschuetze** [comment]
> @bschuetze I've added your fix locally but it has not worked for Mac M1

Are you still seeing the same error or is it a different one?

**Comment by SergeyPirogov** [comment]
Try to update selenium to latest version, it has to manage drivers itself
