### ISSUE TITLE
TypeError: ChromeDriverManager.__init__() got an unexpected keyword argument 'version' - breaking change in 3.9.1

### ISSUE THREAD

**Issue by alexisml** [SergeyPirogov/webdriver_manager#549]
We started getting this TypeError from yesterday in all our regressions. By looking into the changes from 3.9.0 to 3.9.1 I can see that version was changed in favor of driver_version for ChromeDriverManager. This is not only a breaking change in a minor version, but also not documented. Is this supposed to be this way, or was this an error? 

Note: Firefox, Edge and Opera Driver Managers still have `version` in them, making the change more weird. 

See https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/chrome.py 

Thanks

**Comment by SergeyPirogov** [comment]
This is documented

**Comment by alexisml** [comment]
> This is documented

Sorry to insist, but where?

The readme page even shows an example doesn't work: https://github.com/SergeyPirogov/webdriver_manager#version 
Also, there's no mention anywhere in the release page https://github.com/SergeyPirogov/webdriver_manager/releases/tag/v3.9.1

**Comment by jjti** [comment]
Sorry to pile on but I agree with @alexisml that this is a breaking change. Would you mind if I added a fallback to maintain the `version` parameter @SergeyPirogov?
