### ISSUE TITLE
ChromeType not importable from webdriver_manager.core.utils in 3.9.1

### ISSUE THREAD

**Issue by nodlesh** [SergeyPirogov/webdriver_manager#552]
`from webdriver_manager.core.utils import ChromeType`

ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/usr/local/lib/python3.9/site-packages/webdriver_manager/core/utils.py)

I get a different error when going to 3.9.0, 
TypeError: expected string or bytes-like object

**Comment by SergeyPirogov** [comment]
Delete import and reimport from the right place
