### ISSUE TITLE
cannot find Chrome binary

### ISSUE THREAD

**Issue by AndrewPriadka** [SergeyPirogov/webdriver_manager#559]
Hello, I am faced with the next problem on my MacBook with an Intel processor.
The chromedriwer is downloading into `.wdm` but then I get this.
selene==2.0.0rc3
selenium==4.9.1
webdriver-manager==3.9.1

```
../../venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:378: in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
../../venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:440: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x13bb75030>
response = {'status': 500, 'value': '{"value":{"error":"unknown error","message":"unknown error: cannot find Chrome binary","stac...ff8191b71d3 _pthread_start + 125\\n19  libsystem_pthread.dylib             0x00007ff8191b2bd3 thread_start + 15\\n"}}'}

```

**Comment by occamssafetyrazor** [comment]
Downgrading to 3.8.6 and using this works until the fix (you can no longer specify the chromedriver in the latest release that I'm aware of):
`ChromeDriverManager(version="114.0.5735.90").install()`

**Comment by ema-aka-young** [comment]
Looks like it's a Chromedriver issue: [ChromeDriver requires a Chrome for Testing binary by default](https://bugs.chromium.org/p/chromium/issues/detail?id=1466427)

On Selenium I've found out a workaround for Java, maybe works also for python?
