### ISSUE TITLE
No driver for google chrome 115.0.5790.110

### ISSUE THREAD

**Issue by vulinh48936** [SergeyPirogov/webdriver_manager#562]
I get this error when I update google chrome.
```python
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
```

**Comment by SSAdvisor** [comment]
Sounds similar to ticket #546

**Comment by jamestejada** [comment]
I am getting a similar error after updating to the latest version of the Chrome browser, 115.0.5790.110 (it changed from about 10 hours ago when I updated previously, 115.0.5790.102). Basically it is not an issue with this library. 

In the [last-known-good-versions-with-downloads.json](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json) file, there is no version of the chromedriver in that document that matches the latest Chrome browser. 

![image](https://github.com/SergeyPirogov/webdriver_manager/assets/55721549/cbe73cd6-e628-4597-bc84-2ad5408422f0)
This is from the [endpoint availability page](https://googlechromelabs.github.io/chrome-for-testing/).

**Comment by SergeyPirogov** [comment]
Google is breaking things =(

**Comment by souravjamwal77** [comment]
Hi, @SergeyPirogov I know it's a closed issue, and as I understand the issue after going through #546 I don't want to create any new issues for this. Is there anything we can do to make it work?

**Comment by jamestejada** [comment]
As a workaround for right now, I am specifying the `driver_version` when initializing the ChromeDriverManager class.

`ChromeDriverManager(driver_version='115.0.5790.102').install()`

This has been working for me with browser version: 115.0.5790.110

**Comment by souravjamwal77** [comment]
Thanks 🙏 @jamestejada
