### ISSUE TITLE
cannot import name 'ChromeType'

### ISSUE THREAD

**Issue by hannibalbarx** [SergeyPirogov/webdriver_manager#563]
to use chromium all the docs for 3.9.1 says:

`from webdriver_manager.core.utils import ChromeType`

but i get 

`ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/usr/local/lib/python3.9/site-packages/webdriver_manager/core/utils.py)
`

looking at the source i can't find ChromeType in utils. what am i missing. nothing showing up on google.

**Comment by Daverball** [comment]
They moved it around, it's now in `webdriver_manager.core.os_manager`. Docs will need to be updated.
