### ISSUE TITLE
Automation Python - ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790.10

### ISSUE THREAD

**Issue by raylabres** [SergeyPirogov/webdriver_manager#568]
Hello! Please, I performed an automation using Python's Selenium and WebDriver-manager, but now it is returning "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790.10". So searching I found the site: ''https://googlechromelabs.github.io/chrome-for-testing/#stable" which gives me the list of available or unavailable, my current version, is not working because it is waiting for availability, how much how long does it take to stabilize or any ideas to maybe use the old version until this one is available?

**Comment by chrisdruta** [comment]
related to this issue I believe: https://github.com/SergeyPirogov/webdriver_manager/issues/566

**Comment by SSAdvisor** [comment]
Specify the driver_version manually when creating the driver is the current workaround but that isn't production worthy.

**Comment by raylabres** [comment]
So wait for the web driver to be available in the current chome version? It has forecast?

**Comment by alfablac** [comment]
@raylabres It won't work until your Google Chrome updates to a 'good' version:
https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json
I have the exact issue right now. mine updated from 115.0.5790.102 to .110 and since the latter doesn't have a reference it will crash.
That will work if you somehow find that chromedriver version and recreate it in .wdm cache folder .wdm/drivers/...

**Comment by raylabres** [comment]
Right, thanks! I'm starting with the following path: a "def" function in python to "try" with google chrome and an 'expetion' with microsoft edge, which at the moment we only use these browsers. Can you tell if Microsoft Edge is a problem too?

**Comment by alfablac** [comment]
I didn't experience that with Edge. It's literally a couple of Chrome versions that Google didn't add a chromedriver version, so wdm doesn't find the matching version to use. It might work if you force an update on Google Chrome, but I never did that haha

**Comment by raylabres** [comment]
Cool, I did it right, apparently it worked, in this case I just made a change by calling the Edge driver, and I changed 2 lines to create an installation service line and request to open the browser using edge, I'll just adjust, as much as Edge works one or another window or element needs to click the part, as it changes the layout. But let's wait for Google to make available the web driver, right?

**Comment by chermdev** [comment]
I had the same issue for v115.0.5790.110

For anyone who wants to fix this locally, I applied this as a temporal fix directly to the installed library.

What this does is filtering versions by the first 3 version numbers from the `browser version` and download the latest.

https://github.com/SergeyPirogov/webdriver_manager/blob/05ffbe94608d06be7a62ac9e3b3f3cc9b9540629/webdriver_manager/drivers/chrome.py#L67-L79

Use only the first 3 version numbers:

```python
def get_url_for_version_and_platform(self, browser_version, platform):
        url = "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
        response = self._http_client.get(url)
        data = response.json()
        versions = data["versions"]

        if version.parse(browser_version) >= version.parse("115"):
            short_version = ".".join(browser_version.split(".")[:3])
            compatible_versions = [v for v in versions if short_version in v["version"]]
            if compatible_versions:
                latest_version = compatible_versions[-1]
                log(f"WebDriver version {latest_version['version']} selected")
                downloads = latest_version["downloads"]["chromedriver"]
                for d in downloads:
                    if d["platform"] == platform:
                        return d["url"]
        else:
            for v in versions:
                if v["version"] == browser_version:
                    downloads = v["downloads"]["chromedriver"]
                    for d in downloads:
                        if d["platform"] == platform:
                            return d["url"]

        raise Exception(f"No such driver version {browser_version} for {platform}")
```

**Comment by chermdev** [comment]
I had the same issue for v115.0.5790.110. Some comments in the #566 have this issue.

This issue happens because Google changed his version policy:

> Google changed version policy. Explanation https://chromedriver.chromium.org/downloads/version-selection
> 
> For modern version 115 there is json with download links - https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json
>
> _Originally posted by @morgan9096 in https://github.com/SergeyPirogov/webdriver_manager/issues/566#issuecomment-1651846650_
            



For anyone who wants to fix this locally, I applied this as a temporal fix directly to the installed library.

What this does is filtering versions by the first 3 version numbers from the `browser version` and download the latest.

Current:
https://github.com/SergeyPirogov/webdriver_manager/blob/05ffbe94608d06be7a62ac9e3b3f3cc9b9540629/webdriver_manager/drivers/chrome.py#L67-L79

Using the first 3 version numbers for Chromedriver > v115:

```python
def get_url_for_version_and_platform(self, browser_version, platform):
        url = "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"
        response = self._http_client.get(url)
        data = response.json()
        versions = data["versions"]

        if version.parse(browser_version) >= version.parse("115"):
            short_version = ".".join(browser_version.split(".")[:3])
            compatible_versions = [v for v in versions if short_version in v["version"]]
            if compatible_versions:
                latest_version = compatible_versions[-1]
                log(f"WebDriver version {latest_version['version']} selected")
                downloads = latest_version["downloads"]["chromedriver"]
                for d in downloads:
                    if d["platform"] == platform:
                        return d["url"]
        else:
            for v in versions:
                if v["version"] == browser_version:
                    downloads = v["downloads"]["chromedriver"]
                    for d in downloads:
                        if d["platform"] == platform:
                            return d["url"]

        raise Exception(f"No such driver version {browser_version} for {platform}")
```

**Comment by SergeyPirogov** [comment]
Try v4.0.0
