### ISSUE TITLE
cache_valid_range option not working - chrome

### ISSUE THREAD

**Issue by vkkindia** [SergeyPirogov/webdriver_manager#571]
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager("114.0.5735.90", cache_valid_range=20).install()))

I got this error TypeError: __init__() got an unexpected keyword argument 'cache_valid_range'

**Comment by SergeyPirogov** [comment]
yes, because now you have to pass cache_manager=CacheManager()
