### ISSUE TITLE
Typo in the documentation on ChromeDriverManager parameter (vesrion vs driver_version)

### ISSUE THREAD

**Issue by superosku** [SergeyPirogov/webdriver_manager#572]
Seems that there is a typo on the documentation here:

https://github.com/SergeyPirogov/webdriver_manager/blob/master/README.md?plain=1#L277

```
ChromeDriverManager(version="2.26").install()
```

should probably be

```
ChromeDriverManager(driver_version="2.26").install()
```

as is in the source code:

https://github.com/SergeyPirogov/webdriver_manager/blob/master/webdriver_manager/chrome.py#L14C16-L14C16

**Comment by SergeyPirogov** [comment]
Yes, please open a PR
