### ISSUE TITLE
Opens in chrome instead of chromium

### ISSUE THREAD

**Issue by iyamk** [SergeyPirogov/webdriver_manager#577]
Code:
```

op = webdriver.ChromeOptions()
    op.add_argument('start-maximized')
    op.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36")
    op.add_experimental_option("excludeSwitches", ["enable-automation"])
    op.add_experimental_option('useAutomationExtension', False)
    driver = webdriver.Chrome(
        service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()),
        options=op
    )
stealth(driver,
        languages=["en-US", "en"],
        vendor="Google Inc.",
        platform="Win32",
        webgl_vendor="Intel Inc.",
        renderer="Intel Iris OpenGL Engine",
        fix_hairline=True,
)
driver.get('https://bot.sannysoft.com/')
```
But for some reason chrome starts up. I have Arch linux and have chromium and chrome installed, default browser is firefox.
And there is an error in the documentation, import type like this:
`from webdriver_manager.core.os_manager import ChromeType`

**Comment by SSAdvisor** [comment]
@iyamk ChromeType moved from utils. I am assuming you quoted the documentation. What you have is correct for the current version.

**Comment by iyamk** [comment]
> @iyamk ChromeType moved from utils. I am assuming you quoted the documentation. What you have is correct for the current version.

Why does chrome launch and not chromium? This is a big problem

**Comment by SergeyPirogov** [comment]
@iyamk because you have to mention which browser Selenium should start

```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
options = Options()
options.BinaryLocation = "/usr/bin/chromium-browser"
```
