### ISSUE TITLE
cannot find Chrome binary error.

### ISSUE THREAD

**Issue by dimaklepikov** [SergeyPirogov/webdriver_manager#578]
After updating to 4.0.0 version on Mac OS (arm64) , the following code throws an error:
```
# Manager
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService


def chrome(version=None):
    """Creates driver instance of Chrome"""

    path = ChromeDriverManager(driver_version=version).install()
    return webdriver.Chrome(
        service=ChromeService(executable_path=path)
    )


print(chrome())

### Ouutput:
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
```
**TEMPORARY SOLUTION:**
Passing a path to a Chrome browser binary itself works, but that's not a ChromeDriver instance. 
E.g: 
`path = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"`

What may cause this issue?

**Comment by ndepaola** [comment]
could this be related to this selenium bug? https://github.com/SeleniumHQ/selenium/issues/12381

**Comment by Whysman2** [comment]
If you're wondering why you're now seeing this error for ChromeDriverManager, it's because https://chromedriver.chromium.org/downloads only goes up to version 114 due to driver restructuring by the Chromium Team for the new [Chrome-for-Testing](https://googlechromelabs.github.io/chrome-for-testing/).

Webdriver-manager needs to be updated so it can read the new location for drivers.

**Comment by gregoriopellegrino** [comment]
Same error here. Any quick solution?

**Comment by fecaridade** [comment]
> 

I made a temporary solution in my code and managed to use it

driver = webdriver.Chrome(
            options=options,
            service=ChromeService(
                ChromeDriverManager(version="114.0.5735.90").install()
            ),
        )

passing the argument to "version" in ChromeDriverManager.

i'm using:

webdriver-manager==3.8.6
selenium==4.7.2

**Comment by vickvick3110** [comment]
I am currently using this, which works well on my Mac with the ARM M1 processor. Specifically, I am using Chrome version 115.


```
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service

option = webdriver.ChromeOptions()
option.add_argument("start-maximized")

driver = webdriver.Chrome(service=Service(ChromeDriverManager("114.0.5735.16").install()), options=option)
```

**Comment by cKurultayKalkan** [comment]
+1 Same here. Downgrade back to 3.9.1 solved the issue for now.

**Comment by SergeyPirogov** [comment]
You have to put chrome browser path using ChromeOptions, see example here https://github.com/SergeyPirogov/webdriver_manager/blob/18268c13fd692115b9a2097d55ae9fdb32254878/tests/test_chrome_driver.py#L54

**Comment by leomm20** [comment]
You just could do this:

```
self.driver = webdriver.Chrome(options=chrome_options,
                                           service=ChromeService(ChromeDriverManager(version="latest").install()))
```

It will take the last version of the repository

**Comment by jamesbcd** [comment]
> You have to put chrome browser path using ChromeOptions, see example here
> 
> https://github.com/SergeyPirogov/webdriver_manager/blob/18268c13fd692115b9a2097d55ae9fdb32254878/tests/test_chrome_driver.py#L54

@SergeyPirogov, is there an easy and reliable way to set the chrome browser path without an extra dependency like `pybrowsers`?
