### ISSUE TITLE
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

### ISSUE THREAD

**Issue by FattyMango** [SergeyPirogov/webdriver_manager#580]
### System:

- webdriver_manager == 4.0.0 (latest)
- Chrome driver == 115.0.5790.110 (latest)
- Windows 11 & 10

### Description:
webdriver_manager can't automatically pull the latest chrome driver and it raises this error 

`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790`

My code:
```
            chrome_options = Options()
            chrome_options.add_argument('--log-level=3')
            chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
            driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
            driver.get("https://www.youtube.com/")
```

Traceback:
  ```
File "c:\Users\malak\Desktop\Projects\Python\YoutubeController\src\YouTubeController\youtubecontroller.py", line 53, in __setup
    driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\driver.py", line 40, in get_version
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\driver.py", line 74, in get_latest_release_version
    validate_response(resp)
  File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\utils.py", line 80, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
```

**Comment by FattyMango** [comment]
I tried all of the suggested answers [here](https://stackoverflow.com/questions/74011776/valueerror-there-is-no-such-driver-by-url), but none worked.

**Comment by pgshow** [comment]
I encounter this error too.

**Comment by FattyMango** [comment]
### Update:

It does not work without specifying a version, but I still can't use the debuggerAddress, it enters an infinite loop and it doesn't end.

```
            chrome_options = Options()
            chrome_options.add_argument('--log-level=3')
            #chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222") <---- the problem
            driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
            driver.get("https://www.youtube.com/")
```

**Comment by faissaloux** [comment]
I've got same error `ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip`

**Comment by faissaloux** [comment]
Here is the json from where you can get the right driver https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json

**Comment by faissaloux** [comment]
Upgrade to v4, it works for me.

**Comment by FattyMango** [comment]
Well, v4 works, but as I mentioned I can't use `chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")`.

**Comment by bwomsm1** [comment]
Hi all,
I am still facing the problem against mac os (ventura) 
webdriver-manager                                 4.0.0
selenium                                          4.10.0


Any idea? 
I can confirm that the problem was fixed against Win OS. 

@SergeyPirogov

**Comment by bwomsm1** [comment]
@translation-robot I tried now with pip `selenium` versions `4.10.0`, `4.9.1` and `4.8.3` and the whole 3 failed.

**Comment by bwomsm1** [comment]
I see, but I can't go back to `3.141.0`
Hope to have a fix for that soon.

**Comment by SergeyPirogov** [comment]
> I see, but I can't go back to `3.141.0` Hope to have a fix for that soon.

It will work for 4.10.0 as well

**Comment by bwomsm1** [comment]
@SergeyPirogov thanks for your reply.
but what exactly should work? I can confirm that on Win it does working but not on Mac.

**Comment by bwomsm1** [comment]
@translation-robot thanks, I will try the workaround.
I just wonder, are you guys planning a fix? 
I can wait a while for the fix, it's just that I don't really like the `114.0.5735.90` hard coded thing.

**Comment by bwomsm1** [comment]
> This code works fin on windows, so the error is from selenium 4.10.0 on mac only, there is no error on windows. selenium==4.10.0 webdriver_manager==4.0.0 chrome 115.0.5790.110
> 
> # selenium 4 from selenium import webdriver from selenium.webdriver.chrome.service import Service from webdriver_manager.chrome import ChromeDriverManager
> 
> driver_path = ChromeDriverManager().install() print(f"Driver installed to : {driver_path}")
> 
> chrome_options = webdriver.ChromeOptions() # add_experimental_option fails so it is commented #chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
> 
> # Create service with driver path from ChromeDriverManager service = Service(driver_path)
> 
> driver = webdriver.Chrome(service=service, options=chrome_options)

I agree, I am asking regarding a solution for the mac part.

**Comment by bwomsm1** [comment]
> ### System:
> * webdriver_manager == 4.0.0 (latest)
> * Chrome driver == 115.0.5790.110 (latest)
> * Windows 11 & 10
> 
> ### Description:
> webdriver_manager can't automatically pull the latest chrome driver and it raises this error
> 
> `ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790`
> 
> My code:
> 
> ```
>             chrome_options = Options()
>             chrome_options.add_argument('--log-level=3')
>             chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
>             driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
>             driver.get("https://www.youtube.com/")
> ```
> 
> Traceback:
> 
> ```
> File "c:\Users\malak\Desktop\Projects\Python\YoutubeController\src\YouTubeController\youtubecontroller.py", line 53, in __setup
>   driver = webdriver.Chrome(ChromeDriverManager().install(),options=chrome_options,)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 32, in install
>   driver_path = self._get_driver_path(self.driver)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\manager.py", line 23, in _get_driver_path
>   driver_version = driver.get_version()
>                    ^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\driver.py", line 40, in get_version
>   return self.get_latest_release_version()
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\driver.py", line 74, in get_latest_release_version
>   validate_response(resp)
> File "C:\Users\malak\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\utils.py", line 80, in validate_response
>   raise ValueError("There is no such driver by url {}".format(resp.url))
> ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
> ```

There you go: https://github.com/SeleniumHQ/selenium/issues/12447

I used @FattyMango description :-) thx

**Comment by dongfangtianyu** [comment]
>Starting from M115, the release method of chrome river has undergone significant changes, with the original https://chromedriver.storage.googleapis.com/ The link is invalid.

Source: https://chromedriver.chromium.org/downloads/version-selection



Temporary solution 1:

Downgrading the browser version to 114 and below allows you to continue downloading chrome driver using the original method.



Temporary solution 2:

Manually select, download version 115 of chromedrievr from here, and unzip it to the PATH directory: https://googlechromelabs.github.io/chrome-for-testing/

**Comment by FattyMango** [comment]
thanks, @bwomsm1 for reporting the issue to Selenium and @translation-robot to address it.
it works now,
I degraded the versions of Selenium and webdriver_manager:

- webdriver-manager V3.5.3
- Selenium V4.1.2

and this is the final code:

```
            chrome_options = Options()
            chrome_options.add_argument('--log-level=3')
            chrome_options.add_experimental_option("debuggerAddress", "127.0.0.1:9222")
            driver = webdriver.Chrome(ChromeDriverManager(version="114.0.5735.90").install(),options=chrome_options,)

```

**Comment by Taewan-P** [comment]
Why is this marked as completed? Just setting the chromium version lower than 115 is a temporary fix. We should make it auto download the latest version with the latest URL for future versions.

**Comment by Taewan-P** [comment]
I managed to fix this issue by directly setting the new download url.

```python
service = ChromeService(executable_path=ChromeDriverManager(
    url='https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing'
).install())
```

**Comment by suprimex** [comment]
> ```python
> https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing
> ```

got 404. That’s an error. That’s all we know.

**Comment by Taewan-P** [comment]
You have to add the chrome version and the binary type + file name to download the actual file. Not just clicking the link.
The code I provided automatically does it for you.
