### ISSUE TITLE
 cannot import name 'get_browser_version_from_os' from 'webdriver_manager.core.utils'

### ISSUE THREAD

**Issue by joon612** [SergeyPirogov/webdriver_manager#585]
```
ImportError: cannot import name 'get_browser_version_from_os' from 'webdriver_manager.core.utils' (/usr/local/lib/python3.9/dist-packages/webdriver_manager/core/utils.py)
```
Platform:
Ubuntu 20 and Windows11

Python 3.9.13

Package version: 4.0.0

I used last one is available in v3.8.5.

**Comment by SergeyPirogov** [comment]
get_browser_version_from_os was moved to https://github.com/SergeyPirogov/webdriver_manager/blob/322e160f4ee342ae36ca1f5c49b8d9471f5a809c/webdriver_manager/core/os_manager.py#L67

**Comment by joon612** [comment]
Thanks! I really appreciate!
