### ISSUE TITLE
Fix WSL

### ISSUE THREAD

**Issue by aolko** [SergeyPirogov/webdriver_manager#59]
```
(venv) aolko@DESKTOP-?:/mnt/e/~py-proj/scrapr$ python3 app.py --chrome-auto
Initializing webdriver...

Checking for linux64 DESKTOP-?:2.46 in cache
There is no cached driver. Downloading new one...
Trying to download new driver from http://chromedriver.storage.googleapis.com/2.46/DESKTOP-?_linux64.zip
```
```
ValueError: There is no such driver DESKTOP-? with version 2.46 by http://chromedriver.storage.googleapis.com/2.46/DESKTOP-?_linux64.zip
```

maybe don't grab hostname/machine name?

**Comment by SergeyPirogov** [comment]
Not sure how it's possible. Can you show what outputs as hostname?

**Comment by aolko** [comment]
> Not sure how it's possible. Can you show what outputs as hostname?
`aolko@DESKTOP-5EORBDC:/mnt/e/~py-proj/scrapr$ hostname`
`DESKTOP-?` (redacted)

**Comment by SergeyPirogov** [comment]
Name resolution lines are listed below.

https://github.com/SergeyPirogov/webdriver_manager/blob/5c2d998e6c33e7a2127aeefd44ad1d454b15acc0/webdriver_manager/utils.py#L13-L31

Please try to execute thise in your environment to determine what it shows

**Comment by aolko** [comment]
```
aolko@DESKTOP-?:/mnt/d/temp$ python3 py-os-test.py
linux64
```

**Comment by SergeyPirogov** [comment]
So, everything should be ok

**Comment by aolko** [comment]
and yet it's not

**Comment by MarkBrook** [comment]
If it's still relevant, I believe you have an env variable called `NAME` that returns `DESKTOP-?`.
So, it's found and does not go to `default.ini` config.

```python
def __getattr__(self, item):
    return os.getenv(item.upper(), self.get(item))
```
