### ISSUE TITLE
chrome win64 driver for windows 

### ISSUE THREAD

**Issue by jhowe321** [SergeyPirogov/webdriver_manager#592]
If the ostype is win64, the type is changed to win32. This causes the chrome win32 driver to be downloaded instead of the available win64 driver.

**Comment by ferromint** [comment]
I an confirm this bug.

Replacing
```Python3
if "win" in os_type:
    return "win32"
```
with
```Python3
if os_type in ["win32", "win64"]:`
    return os_type
```
in [webdriver_manager/chrome.py](https://github.com/SergeyPirogov/webdriver_manager/blob/de0872ff7fb5eb141fdc32e991938f5ac494278e/webdriver_manager/chrome.py#L46) solves the issue.

Windows 10 22H2 64bit
Python 3.11 64bit
webdriver-manager 4.0.0

**Comment by VineetHBhat** [comment]
The re-downloading issue has already been fixed with Fix caching #582. A new release would help

**Comment by ferromint** [comment]
> [...] The re-downloading issue has already been fixed with Fix caching https://github.com/SergeyPirogov/webdriver_manager/pull/582 [....]

Yes, I already wrote about the fix and even put a link to the exact line of code in my [previous comment](https://github.com/SergeyPirogov/webdriver_manager/issues/592#issuecomment-1684914269).

> [...] A new release would help [...]

And exactly for the time period where this release does not exist, I wrote other interested users how to work around the bug by pointing them to the single missing return statement in the code so they can help themselves in the meantime.

**Comment by SergeyPirogov** [comment]
Fix

**Comment by MarcelWilson** [comment]
I'm confused.  Did this get fixed?  If so, which PR?
Looking at the master branch it would appear to still be an issue. 
https://github.com/SergeyPirogov/webdriver_manager/blob/178a390311e297f8aba9fc20234c7398b934ed5b/webdriver_manager/chrome.py#L46-L47
