### ISSUE TITLE
Running more than 3 threads causes permission issue

### ISSUE THREAD

**Issue by TomaszKarski** [SergeyPirogov/webdriver_manager#593]
I run Behave tests on wind32 and got the following error:
`WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions.`

 all started after upgrading the webdriver manager to 4.0.0. Before I could run 4 threads without issues. now it's only working with 3 threads

python==3.11
selenium==4.11.2
webdriver-manager==4.0.0

**Comment by Niuzitong** [comment]
I have the same issues

**Comment by jimmyQAQ** [comment]
same

**Comment by jimmyQAQ** [comment]
> Same issue, did you guys find a solution?

Nope, waiting for the next update lol

**Comment by Debanjan-B** [comment]
With Python **v3.10.10** and Selenium **v4.10.0** I 'm still able to spin off 4 instances. Maybe some regression issue with Selenium **v4.11.2**

**Comment by jimmyQAQ** [comment]
> With Python **v3.10.10** and Selenium **v4.10.0** I 'm still able to spin off 4 instances. Maybe some regression issue with Selenium **v4.11.2**

is your Chrome version 115.0.5790.171? or 115.0.5790.170

**Comment by TomaszKarski** [comment]
With the older version of the chromedriver and webdriver-manager it's working fine, (the issue is not related to the selenium version - I checked it).

So I assume that the issue is related:
- To the newest chromedriver `115.0.5790.171`
   OR
- To the webdriver-manager

**Comment by atlas-wong** [comment]
it seems there is some issue in multiple thread in chromedrive 115.0.5790.170 (share the same session)
and hence forbidden multi thread in 115.0.5790.171

**Comment by anirbanmajumder0** [comment]
I am having the same issue, any Updates?

**Comment by Andreito95** [comment]
oh i have the same exactly issue, this is running me crazy!
i work with at least 25 istances...

it tried to exclude webdriver-manager and try the new "selenium manager" directly from selenium for the driver creation but it uses so so much resources...

we need a fix from the best lib webdriver-manager

**Comment by SergeyPirogov** [comment]
It works only if you use pytest-xdist

**Comment by Andreito95** [comment]
What do you mean "works only if you use pytest-xdist" 
i don't want to parallel testing using one process, i have 25 python different separated processes

it always worked with older versions of "webdriver-manager", i've never had this winerror

if you think that "pytest-xdist" works how can we use it with webdriver-manager?

**Comment by TomaszKarski** [comment]
@SergeyPirogov  why did you complete this issue?
According to this: https://github.com/DUB1401/RemangaParser/issues/2
The issue is related to webdriver-manager... 

I don't use pytest but behave so this will not resolve my issue...

it's not even the solution to the issue

**Comment by SergeyPirogov** [comment]
The issue is that webdriver_manager saves binaries in the same folder. With pytest xdist a did a trick and it works fine. If you have any other way of parallel execution - it wont work

**Comment by taytanqbpass** [comment]
Why are you closing this issue if its not resolved? Can you explain how "works only if you use pytest-xdist" works? We have not encountered this issue in previous versions of webdriver-manager.

**Comment by gabriellopesdesouza2002** [comment]
When this error occurs, I have to close my vscode and run the tests again... But even when I create an executable (I work with automations using selenium) the same problem occurs if the user runs more than one .exe at the same time.
