### ISSUE TITLE
Set download and install path

### ISSUE THREAD

**Issue by WillianPestana** [SergeyPirogov/webdriver_manager#594]
Hey guys.

I would like to know if it is possible to define a location where the library downloads and install the webdriver when using:

**driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)**

Thank you in advance.

**Comment by chermdev** [comment]
you can pass a custom [DriverCacheManager](https://github.com/SergeyPirogov/webdriver_manager/blob/de0872ff7fb5eb141fdc32e991938f5ac494278e/webdriver_manager/core/driver_cache.py#L17) to change the root_path where the `.wdm` folder is created. All the files are downloaded inside this folder.

```python
from webdriver_manager.core.driver_cache import DriverCacheManager

cache_manager = DriverCacheManager(
    root_dir="your path"
)
driver_path = ChromeDriverManager(cache_manager=cache_manager).install()
```

example installing the drivers inside _*current working directory*_

```python
from pathlib import Path
from webdriver_manager.core.driver_cache import DriverCacheManager

cache_manager = DriverCacheManager(
    root_dir=Path.cwd()
)
driver_path = ChromeDriverManager(cache_manager=cache_manager).install()
```

this creates `.wdm` folder with the next files inside my project dir:
![image](https://github.com/SergeyPirogov/webdriver_manager/assets/46976866/aeaaf90a-caee-44d4-ba37-b71ff5f4f21b)

**Comment by SergeyPirogov** [comment]
See comment above
