### ISSUE TITLE
Threading Issue on arm64

### ISSUE THREAD

**Issue by SK-Pagma** [SergeyPirogov/webdriver_manager#598]
When I want to start my second instance of a driver via Thread, I get the following Traceback on Apple M1:

Traceback (most recent call last):
  File "-", line 224, in <module>
    browser2 = initialize()
  File "-", line 120, in initialize
    browser = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=option) #driver_version="114.0.5735.16"
  File "-/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "-/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "-/selenium/webdriver/common/service.py", line 109, in start
    self.assert_process_still_running()
  File "-/selenium/webdriver/common/service.py", line 122, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service -/.wdm/drivers/chromedriver/mac64/116.0.5845.96/chromedriver-mac-arm64/chromedriver unexpectedly exited. Status code was: -9

Same Code is working on windows tho.
python==3.11
selenium==4.11.2
webdriver-manager==4.0.0

(With selenium==4.10.0 and wdm==3.9.1 as well as driver_version="114.0.5735.16" it is still possible)

**Comment by starboi-63** [comment]
I'm also getting this issue on M1 Macs, but my code executes just fine on both Windows and Linux. I'm using `multiprocessing.pool.ThreadPool` with 10 threads. I only create one Selenium driver instance per thread and store it in `threading.local()` using this [utils file](https://github.com/starboi-63/growth-stock-screener/blob/mac-os-support/growth_stock_screener/screen/iterations/utils/concurrency.py) I wrote up. But Selenium loses connection with geckodriver somehow.

**Comment by SergeyPirogov** [comment]
If you don't use pytest xdist it won't work ok with more thatn 1 thread
