### ISSUE TITLE
ValueError: There is no such driver by url

### ISSUE THREAD

**Issue by georgekplivi** [SergeyPirogov/webdriver_manager#599]
Hi,
I am getting  ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/116.0.5845/chromedriver_linux64.zip error after updating my chrome to the latest version

**Comment by lettow-humain** [comment]
We observed the same on windows
`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip`

**Comment by SK-Pagma** [comment]
Did you upgrade your web driver-manager version to the latest?

**Comment by angheljf** [comment]
Updating to latest version of the library fixed my issue

**Comment by GaurangTandon** [comment]
Upgrading to latest version worked for me as well on Chrome 116 for macOS.

**Comment by lettow-humain** [comment]
Yes that solved it for us as well. Not sure why it suddenly broke though.
