### ISSUE TITLE
How to load version 114 of chrome

### ISSUE THREAD

**Issue by elearning-x** [SergeyPirogov/webdriver_manager#602]
Hello

I'm trying to load the latest version of Chrome but without success with the following commands.
```
driver = webdriver.Chrome(service=ChromeService(
                                ChromeDriverManager(url="https://chromedriver.storage.googleapis.com/index.html?path=114.0.5735.90/", 
                                                    latest_release_url="https://chromedriver.storage.googleapis.com/LATEST_RELEASE_114.0.5735").install()),
                                                    options=options)
```

if I try the following:
```
 driver = webdriver.Chrome(service=ChromeService(
                                ChromeDriverManager(driver_version="114.0.5735").install()), options=options)
```
it generates an error

`ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/114.0.5735/chromedriver_mac_arm64.zip`

Can I do it ?
What would be the correct command ?

Thanks a lot

**Comment by david-engelmann** [comment]
It was discussed on the initial work to support the new chrome endpoints about potentially continuing to support the shorter forms for versions such as "144" or "144.0.5735". I'll link to the commit where it was implemented but never merged incase its of interest to the maintainers or someone looking to patch for themselves - https://github.com/SergeyPirogov/webdriver_manager/pull/537/commits/6355e71e8c6e3dd5da373aaa691257ee95cf398e
