### ISSUE TITLE
There is no such driver by url

### ISSUE THREAD

**Issue by rain01** [SergeyPirogov/webdriver_manager#603]
Seems lots of confusion around driver versions now that chrome is switching to "chrome for testing".
I am still getting this error with the latest version in Ubuntu:
```
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/114.0.5735.198/chromedriver_linux64.zip
```

Code:
```
from selenium.webdriver.chrome.webdriver import WebDriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

driver = WebDriver(
    service=Service(ChromeDriverManager().install())
)
driver.get('http://localhost/')
```

Platform:
Ubuntu 22.04.2

Python 3.10.6

Package version: 4.0.0

**Comment by rain01** [comment]
I also tried:
```
pip uninstall webdriver_manager
pip install git+https://github.com/SergeyPirogov/webdriver_manager@master
```
This did not fix the issue.
And if I define `driver_version="114.0.5735.90"` then I get:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
But I am not sure this is related.

**Comment by david-engelmann** [comment]
> I also tried:
> 
> ```
> pip uninstall webdriver_manager
> pip install git+https://github.com/SergeyPirogov/webdriver_manager@master
> ```
> 
> This did not fix the issue. And if I define `driver_version="114.0.5735.90"` then I get:
> 
> ```
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
>   (unknown error: DevToolsActivePort file doesn't exist)
>   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
> ```
> 
> But I am not sure this is related.

@rain01 What version of chrome do you have installed? You should trying hard coding to that version

**Comment by rain01** [comment]
> @rain01 What version of chrome do you have installed? You should try hard coding to that version

I had version 114. Once I updated to latest it started working.
