### ISSUE TITLE
ChromeDriver only supports Chrome version 114

### ISSUE THREAD

**Issue by Louis-524** [SergeyPirogov/webdriver_manager#605]
When I use Pyinstaller to package my program and execute the exe, it executes the chromedriver version 114.0.5735.90

And I found from .wdm\drivers\chromedriver\win64 folder
The version downloaded by webdriver-manager is 114.0.5735.90,
But I use .py to execute version 116.0.5845.111

 File "selenium\webdriver\chrome\webdriver.py", line 76, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 157, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 252, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.111 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

I use python 3
webdriver. Chrome(ChromeDriverManager(). install())

Pyinstaller version 4.4
webdriver-manager version 4.0.0
Chrome version 116.0.5845.111 x64

**Comment by emptyshow1** [comment]
Me too.... 

webdriver-manager version 4.0.0
Chrome version 116.0.5845.111 x64

![image](https://github.com/SergeyPirogov/webdriver_manager/assets/31281229/5f93376f-355e-4a75-8221-1b94e5802aa6)

**Comment by peter-taylor-telus** [comment]
In the interim, latest stable chromedriver binaries can be obtained here:

https://googlechromelabs.github.io/chrome-for-testing/#stable

Download the zip archive and extract to the usual webdriver-manager folder on your workstation.

**Comment by abilash-c** [comment]
Why do I get this error only with pyinstaller but not when running the .py script? Could someone please help

**Comment by abilash-c** [comment]
> In the interim, latest stable chromedriver binaries can be obtained here:
> 
> https://googlechromelabs.github.io/chrome-for-testing/#stable
> 
> Download the zip archive and extract to the usual webdriver-manager folder on your workstation.

This didn't work. 
@Louis-524 Could you please tell how you solved this?
