### ISSUE TITLE
__get_metadata_key missing return value

### ISSUE THREAD

**Issue by sunday-will** [SergeyPirogov/webdriver_manager#606]
`    def __get_metadata_key(self, driver: Driver):
        if self._metadata_key:
            return self._metadata_key

        driver_version = self.get_cache_key_driver_version(driver)
        browser_version = driver.get_browser_version_from_os()
        browser_version = browser_version if browser_version else ""
        self._metadata_key = f"{self.get_os_type()}_{driver.get_name()}_{driver_version}" \
                             f"_for_{browser_version}"
`

**Comment by david-engelmann** [comment]
https://github.com/SergeyPirogov/webdriver_manager/issues/604

I had a similar issue yesterday. My issue occurred because of the ~ path. Make sure HOME is set correctly

**Comment by david-engelmann** [comment]
https://github.com/SergeyPirogov/webdriver_manager/issues/604

I believe I had a similar issue, last night.

**Comment by volodymyrm** [comment]
https://github.com/SergeyPirogov/webdriver_manager/blob/de0872ff7fb5eb141fdc32e991938f5ac494278e/webdriver_manager/core/driver_cache.py#L108

key value setting should be updated with condition for the case when __get_metadata(driver) returns None:
For example like this:
`key = self.__get_metadata_key(driver) if self.__get_metadata_key(driver) else self._metadata_key`

Otherwise it will be always None on the first run

**Comment by SergeyPirogov** [comment]
@volodymyrm check the code. There is a check for None

**Comment by MarcelWilson** [comment]
@volodymyrm  is correct. I'm seeing the same behavior.  

[`key`](https://github.com/SergeyPirogov/webdriver_manager/blob/6b7d03f38eb4c4fdf8a942b0b9fbc74afcc1dcd0/webdriver_manager/core/driver_cache.py#L108C3-L112) will always be None the first time `find_driver` is called.

```python
        key = self.__get_metadata_key(driver)
        if key not in metadata:
            log(f'There is no [{os_type}] {driver_name} "{driver_version}" for browser {browser_type} '
                f'"{browser_version}" in cache')
            return None
```
