### ISSUE TITLE
Can't execute the library because of Powershell provision only.

### ISSUE THREAD

**Issue by sandi-init** [SergeyPirogov/webdriver_manager#609]
I  am working for private organisation .In that company,they blocked the powershell access for all the employees.

Could you refactor it for also who is using cmd .

Which Line it is failing?

def determine_powershell(self):

you are trying to find the version of chrome using shell command. That's where the program is failing due to company policy.

**Comment by SergeyPirogov** [comment]
I don't know other ways to implement is
