### ISSUE TITLE
version 4.0.0 bug  for ChromeDriverManager().install()

### ISSUE THREAD

**Issue by tomatoKiller** [SergeyPirogov/webdriver_manager#615]
In the end of  DriverCacheManager.__get_metadata_key  method , lack of "return" statement, which will make "ChromeDriverManager().install()" method re-download webdriver every time when this method is called.

![image](https://github.com/SergeyPirogov/webdriver_manager/assets/6139588/603579ce-aeb1-4325-b27e-bc4bac9578fd)

**Comment by VineetHBhat** [comment]
Already fixed with Fix caching #582.
Could someone create a new release so that the fix is available via pypi

**Comment by SergeyPirogov** [comment]
Fixed in 4.0.1
