### ISSUE TITLE
Bug with metadata key inconsistent return value which breaks caching

### ISSUE THREAD

**Issue by cmin764** [SergeyPirogov/webdriver_manager#618]
With `webdriver-manager` **4.0.0**

Code from `webdriver_manager.core.driver_cache.DriverCacheManager` contains:
```python
    def __get_metadata_key(self, driver: Driver):
        if self._metadata_key:
            return self._metadata_key

        driver_version = self.get_cache_key_driver_version(driver)
        browser_version = driver.get_browser_version_from_os()
        browser_version = browser_version if browser_version else ""
        self._metadata_key = f"{self.get_os_type()}_{driver.get_name()}_{driver_version}" \
                             f"_for_{browser_version}"
```

And as you can see, the return is inconsistent when the key is built for the first time, therefore caching doesn't work when a new Python process starts and checks for an existing already downloaded webdriver matching the versions and system.

The function needs to also return the recently initialized `self._metadata_key` attribute at the end of the code block.

**Comment by SergeyPirogov** [comment]
It's fixed in 4.0.1
