### ISSUE TITLE
x86_64 erroneously downloaded on arm64

### ISSUE THREAD

**Issue by stuaxo** [SergeyPirogov/webdriver_manager#619]
I have a project on arm64 that uses webdriver_manager, unfortunately it's downloading the chromedriver for x86_64.

I'm running this in docker, where I install chromium and chromedriver, so I would be happy to use the system chromedriver[1], fact I don't even know if the corresponding version of the chromedriver to the chromium installed in ubuntu is easily available for download.

Version: 4.0.0
```
root@ca98eb61db26:/app# pip freeze | grep webdriver-manager
webdriver-manager==4.0.0
```

OS: Ubuntu 22.04, aarch64 (In Qemu / on Mac m2)

```
root@ca98eb61db26:/app# uname -m
aarch64
root@ca98eb61db26:/app# file /root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver
/root/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=42432337a91f9dc908c4ae8e6cf7daa31f730bee, stripped
```

```
$ /usr/bin/chromedriver --version
...
ChromeDriver 116.0.5845.110 (5128dafac6222fd3ac218660ab6dbf7ff260d768-refs/branch-heads/5845@{#1518})

$ /usr/bin/chromium-browser --version
Chromium 116.0.5845.110 snap
```

As a hack / workaround I generate a drivers.json to point at the correct chromedriver, is there an official way to do this ?

```sh
#!/bin/bash
# use-system-chromedriver

if [[ $(which chromedriver) == "" ]]; then
  echo "Chromedriver not found on the system." exit 1
fi

JSON="{\
  \"linux64_chromedriver_latest_for_\": {\
    \"timestamp\": \""$(date +%d/%m/%Y)"\",\
    \"binary_path\": \"/usr/bin/chromedriver\"\
  }\
}"

echo "$JSON" > ~/.wdm/drivers.json
```

Or oneliner, (for docker):
```sh
mkdir -p ~/.wdm; printf '{"linux64_chromedriver_latest_for_":{"timestamp":"%s","binary_path":"/usr/bin/chromedriver"}}\n' $(date "+%d/%m/%Y") > ~/.wdm/drivers.json
```

Originally I errorniously reported this here
https://github.com/bonigarcia/webdrivermanager/issues/1125

**Comment by borosilicate** [comment]
Hello @SergeyPirogov I had this issue as well on the Raspberry pi as well.

**Comment by The-Judge** [comment]
This is an 1:1 duplicate of #616
Please have this one closed.

**Comment by stuaxo** [comment]
Closing as it's a duplicate of #616
