### ISSUE TITLE
Add support for chromedriver version 115 and newer versions

### ISSUE THREAD

**Issue by arthas009** [SergeyPirogov/webdriver_manager#622]
Hi, chromedriver download source location is changed to "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing" for version 115 and later. 

I saw in the source code, api is taken from "https://chromedriver.storage.googleapis.com" statically. Currently webdrivermanager is not working for latest chrome browsers. Please add a fix for that or I can also be a contributor for this job. I have already managed the code in my local PC and everything is working for newest browsers.

![image](https://github.com/SergeyPirogov/webdriver_manager/assets/36654247/f1354cfc-246b-4af4-a156-097791e705c2)

It will be better to add a switching mechanisim for older and newer versions, user needs to be directed to right url download address automatiocally.

Also it will be better to fetch the current browser version instead of latest browser version by default. This will also help to decide which download url to go.  For example, I have browser version 116, webdrivermanager should look for it directly instead of starting to search from the latest driver.

**Comment by peter279k** [comment]
According to the [link](https://chromedriver.chromium.org/downloads), it seems that the later `115` version links are changed.

And the warning message is as follows:

```
If you are using Chrome version 115 or newer, please consult the Chrome for Testing availability dashboard. This page provides convenient JSON endpoints for specific ChromeDriver version downloading.
```

I think it can consider using/parsing the [version_downloads.json](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) file to extract the current Chrome driver version.

**Comment by arthas009** [comment]
I just saw a workaround merged to master branch which is parsin version_downloads.json or other similar json files from given link. It seems there is no a new release is taken. Code is ready but release is not here.

**Comment by JaminsonR** [comment]
I believe this issue got resolved in https://github.com/SergeyPirogov/webdriver_manager/issues/566

**Comment by Imafikus** [comment]
Any updates on this by any chance?

**Comment by arthas009** [comment]
They have fixed it but it won't work until new release, I am currently using a local fix for temporary usage by changing download source in code.

**Comment by peter279k** [comment]
At this moment, I downgrade the Google Chrome web browser and using the older Web driver Selenium version to do that.
