### ISSUE TITLE
__init__() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by motad333** [SergeyPirogov/webdriver_manager#626]
hi
i was using version 3.7.2 of webdriver_manager and there was on option `path`
ChromeDriverManager(path=BASE_DIR).install()
but in version 4.0.0 has error
__init__() got an unexpected keyword argument 'path'

**Comment by JokerYF** [comment]
driver_cache_manager = DriverCacheManager(root_dir=‘your project path’)
ChromeDriverManager(cache_manager=driver_cache_manager).install()

**Comment by motad333** [comment]
please update this in document
