### ISSUE TITLE
Did not download the latest version of chrome driver

### ISSUE THREAD

**Issue by workatecesisnathaniel** [SergeyPirogov/webdriver_manager#628]
There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938

**Comment by reydc** [comment]
Which py version are you using? pip-upgrading the package for Python3.8 works for me, and I had the same error for that release

**Comment by workatecesisnathaniel** [comment]
I have done the it and it was the chrome version it auto downloads version 114 as the latest version.Currently the latest version is 117.I think the link which it uses to download the latest chrome driver is wrong

**Comment by workatecesisnathaniel** [comment]
python version used is 3.8.10

**Comment by workatecesisnathaniel** [comment]
![image](https://github.com/SergeyPirogov/webdriver_manager/assets/119122586/337105fe-b074-419f-89c2-d649b0274dee)

**Comment by workatecesisnathaniel** [comment]
![image](https://github.com/SergeyPirogov/webdriver_manager/assets/119122586/ff89708a-2e5e-4597-a7b0-c059f915df47)

**Comment by workatecesisnathaniel** [comment]
pip install --upgrade webdriver_manager
