### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by raylabres** [SergeyPirogov/webdriver_manager#671]
Function executed: 
def define_browser(site, show_browser, name_browser="chrome"): if show_browser == False: if name_browser.lower() == "chrome": options = OptionChrome() options.add_argument('--headless') service = Service(ChromeDriverManager().install()) browser = webdriver.Chrome(service=service, options=options) else: options = OptionEdge() options.add_argument('--headless') service = Service(EdgeChromiumDriverManager() .install()) browser = webdriver.Edge(service=service, options=options) else: if browser_name.lower() == "chrome": service = Service(ChromeDriverManager().install()) browser = webdriver.Chrome(service=service)

else:
service = Service(EdgeChromiumDriverManager().install())
browser = webdriver.Edge(service=service)

browser.get(site)
browser.maximize_window()
sleep(2)
return browser

Error returned:
Traceback (most recent call last):
File "c:\Development\Functions.py", line 296, in <module>
browser= define_browser(site_url, True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "c:\Development\Functions.py", line 156, in define_browser
browser = webdriver.Chrome(service=service)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__ super().__init__( File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py" \selenium\webdriver\common\service.py", line 98, in start self._start_process(self._path) File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py", line 208, in _start_process self.process = subprocess.Popen(
 ^^^^^^^^^^^^^^^^ File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\AppData\Local\Programs\Python\Py thon312\Lib\subprocess.py", line 1538, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ OSError: [WinError 193] %1 is not an application Valid Win32

**Comment by ahmad-a-radwan07** [comment]
same issue here

**Comment by jfitzpatrick6** [comment]
I was able to resolve it by removing service = service.
`def initDriver():
    options = webdriver.ChromeOptions()
    options.add_experimental_option('excludeSwitches', ['enable-logging'])
    prefs = {'download.default_directory' : fulldownloadPath,
                "download.prompt_for_download": False, #To auto download the file
                "download.directory_upgrade": True,
                "plugins.always_open_pdf_externally": True #It will not show PDF directly in chrome
        }
    # have to keep this arguement, selenium will fail to locate
    # elements otherwise, defaults to 0x0
    options.add_argument('window-size=1920x1080')
    options.add_experimental_option('excludeSwitches', ['enable-logging',"enable-automation"])
    options.add_experimental_option('prefs', prefs)
    service = ChromeService(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=options)
    return driver`

**Comment by jfitzpatrick6** [comment]
I was able to resolve this by removing service = service. It appears the new update has removed the need for service.

[https://stackoverflow.com/questions/78793171/webdriver-error-when-using-selenium-error-oserror-winerror-193-1-is-not-a-v](url)

`driver = webdriver.Chrome(options=options)`

Though I'm using chrome. I've seen it mentioned on other issues.

**Comment by eduardorco** [comment]
Same here. Following @jfitzpatrick6 solution worked!

**Comment by jacsonrsasse** [comment]
Yep, same here. @jfitzpatrick6 solution worked for me too!

**Comment by raylabres** [comment]
Great! Here the solution, it worked!
