### ISSUE TITLE
Selenium Webdriver do not pass real chromedriver executable path

### ISSUE THREAD

**Issue by devsosin** [SergeyPirogov/webdriver_manager#680]
I working on docker container (python3.9-slim image) and always update packages as recent version
but selenium do not working on these days, i found the cause of error

here is my `get_driver()` method

![image](https://github.com/user-attachments/assets/68b8b914-4b86-4f6e-9edf-f842313ca618)

it uses a THIRD_PARTY_NOTICES.chromedriver ( i think it is added )

![image](https://github.com/user-attachments/assets/3e947371-9d65-4a73-b0dc-fbdffeb16c23)

so i change THIRD_PARTY_NOTICES.chromedriver to chromedriver.exe it working on windows OS 
(i think on UNIX-LIKE OS filename must be changed)

**Comment by optinsoft** [comment]
I have the same issue

**Comment by devsosin** [comment]
add content:

when i use new chrome Version: 128.0.6613.119-1,
i get continuously error log `disconnected: not connected to DevTools`


i fixed it just use another chrome driver version

check chrome version [link](https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable?id=202706&page=1)


```Dockerfile
# set chrome version 
ENV     CHROME_VERSION=127.0.6533.72-1

# install specific version
RUN     apt-get update && apt-get install -y wget && \
                wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb && \
                apt-get -y update && \
                apt-get install -y ./google-chrome-stable_${CHROME_VERSION}_amd64.deb;
```
