### ISSUE TITLE
Flatten module structure

### ISSUE THREAD

**Issue by Fraser-M-Hurley** [SergeyPirogov/webdriver_manager#71]
Hi,
I wanted to suggest flattening the file structure by moving the various driver types into a single file. This way when looking to import multiple driver types there is less code to be written. I'm happy to raise a PR for this but thought I'd quickly check whether there was a specific reason you had implemented it in this way?

**Comment by SergeyPirogov** [comment]
I am ok with this suggestion 👍

**Comment by SergeyPirogov** [comment]
@Fraser-M-Hurley please provide a pr
