### ISSUE TITLE
Release 1.8 fails with Chromium

### ISSUE THREAD

**Issue by href** [SergeyPirogov/webdriver_manager#73]
With the 1.8 release a version check is run using `google-chrome --version`. This fails if Chromium is installed instead of Google Chrome (as the `google-chrome` binary is missing).

In 1.7 Chromium works. As a work around one can link `chromium-browser` to `google-chrome`:

```bash
ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
```

So apart from this check, webdriver_manager seems to be perfectly fine with using Chromium instead of Google Chrome.

**Comment by SergeyPirogov** [comment]
@href Hi! Thank you for the issue. This is very narrow, will try to fix somehow

**Comment by Amy2017new** [comment]
I have encountered the same problem, what should I do?

**Comment by DaWe35** [comment]
@SergeyPirogov I think it was not fixed, same error fog me on Linux

**Comment by ElTav** [comment]
Also getting this issue on linux

**Comment by SergeyPirogov** [comment]
The latest version is 2.4.0. Please try it

**Comment by megancooper** [comment]
Tried version `2.4.0` but still encountering this issue. Is there a way to get around? Here's how I'm using this package with selenium:

```
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(
            ChromeDriverManager().install(),
            chrome_options=options)
```

**Comment by SergeyPirogov** [comment]
@megancooper try to use Chromium Driver

**Comment by megancooper** [comment]
@SergeyPirogov Apologies, maybe I misunderstood, but changing the `chrome_type` parameter in the constructor seems to produce a similar error (for chromium)

```
Could not get version for Chrome with this command: chromium --version
```

Is it true that this package should install chromium or chrome when unavailable? It looks like the problem is happening because chromium/google chrome are initially not in my docker container.

**Comment by SergeyPirogov** [comment]
No, you have to install browser by your own

**Comment by megancooper** [comment]
Ah ok, thanks 👍

**Comment by matabares** [comment]
But, why this bug is closed?.

It must be open.

**Comment by SergeyPirogov** [comment]
@matabares Why?

**Comment by rgreg** [comment]
Still, the issue is there?

**Comment by SergeyPirogov** [comment]
Please try the latest version and check

**Comment by nxbx** [comment]
Same issue.
webdriver_manager was installing from pip

Name: webdriver-manager
Version: 3.2.1

Trying to run in a virtual environment in flask app on Ubuntu 18.04 VPS.

**Comment by wblondel** [comment]
> 
> 
> Same issue.
> webdriver_manager was installing from pip
> 
> Name: webdriver-manager
> Version: 3.2.1
> 
> Trying to run in a virtual environment in flask app on Ubuntu 18.04 VPS.

Do you have Chrome installed on your VPS ?

**Comment by nxbx** [comment]
> > Same issue.
> > webdriver_manager was installing from pip
> > Name: webdriver-manager
> > Version: 3.2.1
> > Trying to run in a virtual environment in flask app on Ubuntu 18.04 VPS.
> 
> Do you have Chrome installed on your VPS ?

Yes.

google-chrome --version

Google Chrome 83.0.4103.116

**Comment by MathieuDeBaets** [comment]
@SergeyPirogov This is still an issue for version 3.2.2 it seems.. Any updates?

**Comment by AIGeneratedUsername** [comment]
The same issue. Do I need to install Chrome manually? 

I use **py3-pinterest** package which fails because of the webdriver_manager's error.

**Comment by mpaloni** [comment]
Got the same error.
Running on ubuntu 20.04

Python 3.8.2 (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import webdriver_manager
>>> webdriver_manager.__version__
'3.1.0'
>>> import selenium;
>>> selenium.__version__
'3.141.0'

As described above 
`Create a soft link to the chromedriver (to allow discover it automatically). E.g. sudo ln -s /Downloads/chromedriver /usr/bin/google-chrome`
fixed the issue

**Comment by alphanumericaltycoon** [comment]
Same issue

**Comment by aleksandr-kotlyar** [comment]
> Same issue

What version of webdriver_manager? Cause you write in closed topic to 1.8 version. Latest is 3.4.2
I have made a PR in 2020 https://github.com/SergeyPirogov/webdriver_manager/pull/97 - which solved problem for Chromium on Alpine-linux in Docker. I did it for myself and tested it. So i am sure that was supported at that time on v 2.4.0
![image](https://user-images.githubusercontent.com/17043964/127970180-6634c256-1a02-442b-9886-60449cb23a7b.png)

Please open new issue if it doesn't work now and provide more details. And may be somebody will get an attention to it and fix it (if it doesn't work now).

**Comment by TyrGo** [comment]
Same issue too

**Comment by aleksandr-kotlyar** [comment]
@endlessmeal @TyrGo please open new issue with details

1. python version
2. webdriver-manager version
3. OS version
4. the way how did you install the browser
5. command how do you check browser's version
6. example of code which fails

Thank you! This is an issue for 1.8 version, now the latest is 3.5.1 and 3.5.2 is coming soon with some new fixes - see [CHANGELOG.md](https://github.com/SergeyPirogov/webdriver_manager/blob/master/CHANGELOG.md#352)

**Comment by yrwi** [comment]
```
# coding: utf-8

from selenium import webdriver
from selenium.webdriver.chrome.options import Options

from selenium.webdriver.chrome import ChromeDriverManager
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.utils import ChromeType

options = Options()
options.BinaryLocation = "/snap/chromium/current/usr/lib/chromium-browser/chrome"

webdriver.Chrome(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install(),options=options)
```

**Comment by yrwi** [comment]
> from selenium.webdriver.common.keys import Keys
> from webdriver_manager.chrome import ChromeDriverManager
> 
> driver = webdriver.Chrome(
>             ChromeDriverManager().install(),
>             chrome_options=options)

hey could You check that:
```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.utils import ChromeType
service = ChromeService(executable_path = ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install())

driver = webdriver.Chrome(service=service)
driver.get("http://www.python.org")
driver.close()
```
I think most people were not using service here.

my log:

> python3 ./selenium_basic_chromium.py 
> /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> 
> 
> ====== WebDriver manager ======
> Current chromium version is 99.0.4844
> Get LATEST chromedriver version for 99.0.4844 chromium
> Driver [/home/yrwi/.wdm/drivers/chromedriver/linux64/99.0.4844.51/chromedriver] found in cache
>
