### ISSUE TITLE
NotADirectoryError on EC2 running amazon linux

### ISSUE THREAD

**Issue by chlind** [SergeyPirogov/webdriver_manager#77]
geckodriver is downloaded automatically and the path is correct. But I'm getting NotADirectoryError on '/home/ec2-user/.wdm/geckodriver/v0.25.0/linux64/geckodriver'.
But after checking, I'm sure '/home/ec2-user/.wdm/geckodriver/v0.25.0/linux64/geckodriver'
is a file and executable (-rwxr-xr-x).

Calling this form python 3.7.4:
driver = webdriver.Firefox(GeckoDriverManager().install(),firefox_options=fireFoxOptions)

Result in:
Checking for linux64 geckodriver:v0.25.0 in cache
Driver found in /home/ec2-user/.wdm/geckodriver/v0.25.0/linux64/geckodriver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 147, in __init__
    firefox_profile = FirefoxProfile(firefox_profile)
  File "/home/ec2-user/.pyenv/versions/3.7.4/lib/python3.7/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 78, in __init__
    ignore=shutil.ignore_patterns("parent.lock", "lock", ".parentlock"))
  File "/home/ec2-user/.pyenv/versions/3.7.4/lib/python3.7/shutil.py", line 318, in copytree
    names = os.listdir(src)
NotADirectoryError: [Errno 20] Not a directory: '/home/ec2-user/.wdm/geckodriver/v0.25.0/linux64/geckodriver'

**Comment by ArunaBalasubramanian** [comment]
@chlind I encountered the same error on Windows OS as well. But then, realized it is the driver instantiation mistake.

```
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())
```

Please explicitly provide the positional argument name `executable_path` as it is not the first argument on the firefox driver __init__ method. Otherwise, it considers it as a firefox profile and tries to copy the directory contents to a new location throwing error since .exe is not a directory.

```
def __init__(self, firefox_profile=None, firefox_binary=None,
                 timeout=30, capabilities=None, proxy=None,
                 executable_path="geckodriver", options=None,
                 service_log_path="geckodriver.log", firefox_options=None,
                 service_args=None, desired_capabilities=None, log_path=None,
                 keep_alive=True): ```
