### ISSUE TITLE
Edge driver binary is download as a zip file instead of .exe

### ISSUE THREAD

**Issue by ArunaBalasubramanian** [SergeyPirogov/webdriver_manager#78]
The edge driver binary is being downloaded in a zip format instead of .exe

![image](https://user-images.githubusercontent.com/24669266/66487244-9c1d4200-eac9-11e9-9df5-c3cfd0fa494f.png)

Digging into the code base, the below snippet causes the issue. The Microsoft API no longer provides the header response 'content-disposition', so, this logic needs re-visiting.

```
def _get_filename_from_response(self, response, driver):
        try:
            return re.findall("filename=(.+)",
                              response.headers["content-disposition"])[0]
        except IndexError:
            return "{}.zip".format(driver.name)
        except KeyError:
            return driver.name + ".exe"
```

Since, the cache look up is unable to find the binary (.exe) file in the ${USER_HOME}/.wdm, it downloads the driver each and every time ruining the purpose of cache.

**Comment by SergeyPirogov** [comment]
@ArunaBalasubramanian would be nice to see pull request for this

**Comment by ArunaBalasubramanian** [comment]
targeting #79 - Merged into master
