### ISSUE TITLE
chrome_win64

### ISSUE THREAD

**Issue by fess77** [SergeyPirogov/webdriver_manager#8]
When used on win64 PC it tries to download win64 version of chromedriver that just doesn't exists)

We've fixed on our side by adding
`
        if os_type == "win64":
            os_type = "win32"`
to chrome.py.

Definitely should be fixed in main rep as well)

**Comment by SergeyPirogov** [comment]
@fess77 could you please make a pull request with this fix?

**Comment by fess77** [comment]
done

**Comment by SergeyPirogov** [comment]
fixed by https://github.com/SergeyPirogov/webdriver_manager/commit/62c82127bdd3ca0b7245e5223a006820d9b9b82e
