### ISSUE TITLE
Option to silent "checking" message

### ISSUE THREAD

**Issue by chlind** [SergeyPirogov/webdriver_manager#85]
Is there anyway I can silent the checking message? i.e.:
Checking for linux64 chromedriver:76.0.3809.126 in cache
Driver found in [path]/chromedriver

It floods my log.

Thanks!

**Comment by SergeyPirogov** [comment]
Not implemented yet

**Comment by aleksandr-kotlyar** [comment]
@SergeyPirogov need this feature? I can try to implement.

**Comment by SergeyPirogov** [comment]
Would be nice to have it

**Comment by aleksandr-kotlyar** [comment]
I see the solution like: 
all logs of `webdriver_manager` will have `DEBUG` lvl, so users of the lib will be able to configure the level of logs in their applications.

**Comment by SergeyPirogov** [comment]
@aleksandr-kotlyar will you be able to implement this?

**Comment by aleksandr-kotlyar** [comment]
@SergeyPirogov Yes. I think i do. 
I am on my way to solve it. Currently i'm working on solution. Today i created logger method with parameter `logging.%LEVEL%` and changed utils.console() from using pprint to logger

The last thing left is to find the way to pass variable through command-line to `console(text, level)` method in `webdriver_manager`. I am researching this.

**Comment by greysonevins** [comment]
quick solution would be to wrap the manager in this https://stackoverflow.com/a/45669280
Helped me

**Comment by SergeyPirogov** [comment]
I think it would be better to make it configurable. Example logging.mode=debug or info

**Comment by greysonevins** [comment]
@SergeyPirogov agreed but in the mean time. This is a quick solution.

I think I can probably fix this, do you want met to?

**Comment by SergeyPirogov** [comment]
@greysonevins Would be great

**Comment by greysonevins** [comment]
With my PR: https://github.com/SergeyPirogov/webdriver_manager/pull/105

You can do this for no logging
```
from webdriver_manager.firefox import GeckoDriverManager
GeckoDriverManager(DEBUG_LOGGING=False).install()
```
or
```python
GeckoDriverManager().install()


```
