### ISSUE TITLE
Unable to install webdriver-manager using jython setup.py install command, gives  zip_safe flag not set; analyzing archive contents...

### ISSUE THREAD

**Issue by krishnagkashyap** [SergeyPirogov/webdriver_manager#86]
The following steps can be used to reproduce the issue,

1. clone git repo
2. run jython setup.py install

O/P
======
[2019-11-19 13:39.52]  /cygdrive/c/gii/webdriver_manager-master
[kgurupra.KGURUPRA-IN] ➤ jython setup.py install
running install
running bdist_egg
running egg_info
creating webdriver_manager.egg-info
writing dependency_links to webdriver_manager.egg-info\dependency_links.txt
writing top-level names to webdriver_manager.egg-info\top_level.txt
writing webdriver_manager.egg-info\PKG-INFO
writing requirements to webdriver_manager.egg-info\requires.txt
writing manifest file 'webdriver_manager.egg-info\SOURCES.txt'
reading manifest file 'webdriver_manager.egg-info\SOURCES.txt'
writing manifest file 'webdriver_manager.egg-info\SOURCES.txt'
installing library code to build\bdist.java1.8.0_221\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\webdriver_manager
copying webdriver_manager\archive.py -> build\lib\webdriver_manager
copying webdriver_manager\chrome.py -> build\lib\webdriver_manager
copying webdriver_manager\driver.py -> build\lib\webdriver_manager
copying webdriver_manager\driver_cache.py -> build\lib\webdriver_manager
copying webdriver_manager\firefox.py -> build\lib\webdriver_manager
copying webdriver_manager\manager.py -> build\lib\webdriver_manager
copying webdriver_manager\microsoft.py -> build\lib\webdriver_manager
copying webdriver_manager\opera.py -> build\lib\webdriver_manager
copying webdriver_manager\utils.py -> build\lib\webdriver_manager
copying webdriver_manager\__init__.py -> build\lib\webdriver_manager
creating build\bdist.java1.8.0_221
creating build\bdist.java1.8.0_221\egg
creating build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\archive.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\chrome.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\driver.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\driver_cache.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\firefox.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\manager.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\microsoft.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\opera.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\utils.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
copying build\lib\webdriver_manager\__init__.py -> build\bdist.java1.8.0_221\egg\webdriver_manager
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\archive.py to archive$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\chrome.py to chrome$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\driver.py to driver$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\driver_cache.py to driver_cache$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\firefox.py to firefox$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\manager.py to manager$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\microsoft.py to microsoft$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\opera.py to opera$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\utils.py to utils$py.class
byte-compiling build\bdist.java1.8.0_221\egg\webdriver_manager\__init__.py to __init__$py.class
creating build\bdist.java1.8.0_221\egg\EGG-INFO
copying webdriver_manager.egg-info\PKG-INFO -> build\bdist.java1.8.0_221\egg\EGG-INFO
copying webdriver_manager.egg-info\SOURCES.txt -> build\bdist.java1.8.0_221\egg\EGG-INFO
copying webdriver_manager.egg-info\dependency_links.txt -> build\bdist.java1.8.0_221\egg\EGG-INFO
copying webdriver_manager.egg-info\requires.txt -> build\bdist.java1.8.0_221\egg\EGG-INFO
copying webdriver_manager.egg-info\top_level.txt -> build\bdist.java1.8.0_221\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
Unable to analyze compiled code on this platform.
Please ask the author to include a 'zip_safe' setting (either True or False) in the package's setup.py
creating dist
creating 'dist\webdriver_manager-2.3.0-py2.7.egg' and adding 'build\bdist.java1.8.0_221\egg' to it
removing 'build\bdist.java1.8.0_221\egg' (and everything under it)
Processing webdriver_manager-2.3.0-py2.7.egg
creating c:\jython2.7.1\lib\site-packages\webdriver_manager-2.3.0-py2.7.egg
Extracting webdriver_manager-2.3.0-py2.7.egg to c:\jython2.7.1\lib\site-packages
Adding webdriver-manager 2.3.0 to easy-install.pth file

Installed c:\jython2.7.1\lib\site-packages\webdriver_manager-2.3.0-py2.7.egg
Processing dependencies for webdriver-manager==2.3.0
Searching for crayons
Reading https://pypi.python.org/simple/crayons/
Downloading https://files.pythonhosted.org/packages/ec/c9/8ade2831bfa5448f7e5b42f417bffe1269423893b435af556eb582356187/crayons-0.3.0.tar.gz#sha256=50e5fa729d313e2c607ae8bf7b53bb487652e10bd8e7a1e08c4bc8bf62755ffc
Best match: crayons 0.3.0
Processing crayons-0.3.0.tar.gz
Writing C:\Users\kgurupra\Documents\MobaXterm\slash\tmp\easy_install-zrw8js\crayons-0.3.0\setup.cfg
Running crayons-0.3.0\setup.py -q bdist_egg --dist-dir C:\Users\kgurupra\Documents\MobaXterm\slash\tmp\easy_install-zrw8js\crayons-0.3.0\egg-dist-tmp-qhk6fk
zip_safe flag not set; analyzing archive contents...
Unable to analyze compiled code on this platform.
Please ask the author to include a 'zip_safe' setting (either True or False) in the package's setup.py
creating c:\jython2.7.1\lib\site-packages\crayons-0.3.0-py2.7.egg
Extracting crayons-0.3.0-py2.7.egg to c:\jython2.7.1\lib\site-packages
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    setuptools.setup(
  File "C:\jython2.7.1\Lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\jython2.7.1\Lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\jython2.7.1\Lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\jython2.7.1\Lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 741, in process_distribution
    distros = WorkingSet([]).resolve(
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 741, in process_distribution
    distros = WorkingSet([]).resolve(
  File "C:\jython2.7.1\Lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "C:\jython2.7.1\Lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "C:\jython2.7.1\Lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
    return installer(requirement)
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 669, in easy_install
    rmtree(tmpdir)
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 2227, in rmtree
    return shutil.rmtree(path, ignore_errors, onerror)
  File "C:\jython2.7.1\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\jython2.7.1\Lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\jython2.7.1\Lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\jython2.7.1\Lib\site-packages\setuptools\command\easy_install.py", line 1677, in auto_chmod
    six.reraise(et, (ev[0], ev[1] + (" %s %s" % (func, arg))))
IndexError: index out of range: 1
                                                                                                                                                                                       ✘
──────────────────────────────────────────────────────────────────────────────

**Comment by SergeyPirogov** [comment]
Stale
