### ISSUE TITLE
FirefoxDriver - API rate limit exceeded for xx.xx

### ISSUE THREAD

**Issue by piotrkochan** [SergeyPirogov/webdriver_manager#87]
The `self._latest_release_url` does not contains GH_TOKEN

```
    def get_latest_release_version(self):
        # type: () -> str
        resp = requests.get(self._latest_release_url)
```

```
resp = <Response [403]>

    def validate_response(resp):
        if resp.status_code == 404:
            raise ValueError("There is no such driver by url {}".format(resp.url))
        elif resp.status_code != 200:
>           raise ValueError(resp.json())
E           ValueError: {'message': "API rate limit exceeded for xx.xx.xx.xx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}

myenv/lib/python3.7/site-packages/webdriver_manager/utils.py:42: ValueError
```

**Comment by SergeyPirogov** [comment]
@piotrkochan Would be nice to have PR for this

**Comment by aleksandr-kotlyar** [comment]
@piotrkochan Really found a bug.
I see that Geckodriver() takes `self. _latest_release_url` from Driver(), not from GeckoDriver() property.

It's easy to fix. But. I want to up the theme: why to format url so much, when it's so easy to throw Auth header to request?

**Comment by aleksandr-kotlyar** [comment]
Seems TravisCI for webdriver_manager doesn't contain GH_TOKEN too, or if it's encrypted, it's cutted off (see https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions )
 @SergeyPirogov,
- could you check please in main project Travis-CI, does GH_TOKEN still exist and not expired?
- if GH_TOKEN exists, but encrypted, could you check the article above, may-be we should add that workaround?
