### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by mosvath** [SergeyPirogov/webdriver_manager#88]
Guys,
Is it possible to use it behind a proxy server?
Thanks,
Mark

**Comment by SergeyPirogov** [comment]
What do you mean? You want to download drivers using proxy?

**Comment by mosvath** [comment]
Yes, exactly. I don't have direct internet access at my company. But if I
could set the proxy url, user, password, that would be great

**Comment by SergeyPirogov** [comment]
WD Manager download driver using requests. If it's possible to set proxy for requests it's will be possible to cover your needs 

https://github.com/SergeyPirogov/webdriver_manager/blob/e4d816d1e41592fe8239469c26603d9e66f0a4ed/webdriver_manager/driver.py#L139

**Comment by inCloset** [comment]
@mosvath by any chance were you able to get it to work on your company's proxy at your end?
Connection is timing out for me when I simply execute ChromeDriverManager().install() as an argument in the webdriver.Chrome()

**Comment by mosvath** [comment]
Unfortunately I couldn't. However my company added the google download site
on extranet and I could use it without proxy.

**Comment by inCloset** [comment]
@mosvath thanks for the response. 

@SergeyPirogov you wouldn’t happen to know the required steps for someone behind a proxy as simply specifying ChromeDriverManager.install() doesn’t work. The java version of web driver manager has proxy instance that you can call and pass proxy info to.

**Comment by s-weigand** [comment]
As per the [docs of requests](https://2.python-requests.org/en/master/user/advanced/#proxies), this should be achievable w/o any code modification in `webdriver_manager`, by setting the environment variables `HTTP_PROXY` and/or `HTTPS_PROXY`.
Using [pytest-env](https://github.com/MobileDynasty/pytest-env) or [tox](https://tox.readthedocs.io/en/latest/), this wouldn't even need access the machine running the tests.
@mosvath @inCloset if you could confirm that this works, it would be nice to add it to the docs.

**Comment by inCloset** [comment]
Followed the recommended steps by specifying the proxy info using request.session or just request and then using the get method and passing in my argument. So 
s=request.Session()
s.proxies = {“http”:”proxy info”,
“https”:”proxy info”}
s.get(webdriver.Chrome(ChromeDriverManager().install))

This should certainly work, no?

**Comment by s-weigand** [comment]
@inCloset I don't think this will work and most likely it will throw an error.
`webdriver_manager` uses `requests` internally, to download the proper drivers, so you can access it directly.
But `requests` looks for the envoriment variables `HTTP_PROXY` and `HTTPS_PROXY` and uses their values.
If you use `webdriver_manager` only with tests, you can set those enviroment variables with [pytest-env](https://github.com/MobileDynasty/pytest-env) or [tox](https://tox.readthedocs.io/en/latest/).

If you want to use them in general, you can use the following for a linux system:
```bash
export HTTP_PROXY=http://user:pass@host:port
export HTTPS_PROXY=http://user:pass@host:port
```

**Comment by inCloset** [comment]
That makes sense. I will give that a shot. I have pytest installed, but for some reason I cannot find pytest.ini file. New to Mac.

**Comment by s-weigand** [comment]
The `pytest.ini` file you need to create yourself, since it is used to overwrite the default settings of `pytest`.
Also don't forget to install `pytest-env`, before running the tests 😉

**Comment by inCloset** [comment]
Ah appreciate your time and response. Allow me to give this a shot. I will respond on my outcome.

**Comment by inCloset** [comment]
It worked!!. Thanks for your walkthrough this. Much appreciated.

**Comment by mosvath** [comment]
Yes, it works in corporate environment using PROXY.

import os
os.environ["HTTP_PROXY"] = "http://10.14.96.250:8080"
os.environ["HTTPS_PROXY"] = "http://10.14.96.250:8080"
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--window-size=1920,1920')
driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)

**Comment by SergeyPirogov** [comment]
Nice, need to add it to the readme
