### ISSUE TITLE
AWS Lambda Python Error - "Could not get version for Chrome with this command: google-chrome --version"

### ISSUE THREAD

**Issue by luvtomar** [SergeyPirogov/webdriver_manager#90]
I'm trying to deploy a python web scraper with webdriver_manager on AWS Lambda. The scraper works fine on my laptop and within my main python 3.7 folder. However, when I zip the webdriver manager files, my lambda function, and all other necessary packages and files, and upload to Lambda, I get the following error - "Could not get version for Chrome with this command: google-chrome --version" - when the program tries to execute webdriver.Chrome(...) command. Here is the code I used:

`chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-extensions')
chrome_options.add_argument('--ignore-certificate-errors')
browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), chrome_options=chrome_options)`

**Comment by aleksandr-kotlyar** [comment]
Hello @luvtomar! Thank you for reporting. 

First of all, do you have google-chrome installed on your AWS Lambda? What's in output if you call  command `google-chrome --version` before execution of your test scripts?

**Comment by SergeyPirogov** [comment]
Stale

**Comment by darrenfishell** [comment]
@luvtomar I'm having the same issue. Did you ever find any solution to getting your scraper deployed with Lambda?

**Comment by SergeyPirogov** [comment]
That’s because wd manager executes google-chrome —version in order to get chrome version and download appropriate driver for it. Try to set driver version explicitly via DriverManager constructor parameter named verison
