### ISSUE TITLE
Chrome Alpine (Chromium)

### ISSUE THREAD

**Issue by aleksandr-kotlyar** [SergeyPirogov/webdriver_manager#93]
### Problem
If use current version `webdriver_manager 2.3.0` with `Apline linux` distributions - it can't find chrome browser in path, because there is no `google-chrome` distib at `alpine` repository.

Here is the code:
```python
import logging
from webdriver_manager import utils
def test_chrome_version():
    logging.info(utils.chrome_version())
```
Here is the stacktrace:
```console
_____________________________ test_chrome_version ______________________________
src/test/test_wdm.py:16: in test_chrome_version
    logging.info(utils.chrome_version())
/usr/local/lib/python3.7/site-packages/webdriver_manager/utils.py:98: in chrome_version
    .format(cmd)
E   ValueError: Could not get version for Chrome with this command: google-chrome --version
```
Here is [Dockerfile python:3.7-alpine + chrome:3.11-alpine](https://gist.github.com/aleksandr-kotlyar/0bfb7888cbe413b8f06cfaa8066d2e3c)

### Solution
I think we need to add checker if linux uses chromium or google-chrome browser. 
I suggest two vartiants:
#### First
That we can add check if OS.ID is Alpine, we can try to extract id of distribution like here, but python-like:
```bash
$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
$ source /etc/os-release && echo "$ID"
alpine
```

#### Second
Add second try to execute `cmd='chromium --version'` if `os_name() == OSType.LINUX`:
```python
# webdriver_manager/utils.py
def chrome_version():
    pattern = r'\d+\.\d+\.\d+'
    cmd_mapping = {
        OSType.LINUX: 'google-chrome --version',
        OSType.MAC: r'/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version',
        OSType.WIN: r'reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version'
    }

    cmd = cmd_mapping[os_name()]
    stdout = os.popen(cmd).read()
    version = re.search(pattern, stdout)
    if not version:
        if os_name() == OSType.LINUX:
            cmd = 'chromium-browser --version'
            try:
                stdout = os.popen(cmd).read()
                version = re.search(pattern, stdout)
                assert version
                return version.group(0)
            except AssertionError:
                raise ValueError('Could not get version for Chrome with this command: {}'.format(cmd))
        raise ValueError('Could not get version for Chrome with this command: {}'.format(cmd))
    return version.group(0)
```
I can make a PR, but want to discuss first, which solution is better.
@SergeyPirogov what do you think, which solution is better? Or maybe we should wait if someone can suggest the best one?

**Comment by SergeyPirogov** [comment]
Just need to create chromium wd manager and use IT

**Comment by aleksandr-kotlyar** [comment]
@SergeyPirogov understood. Will try to create some of chromium wd manager in next few hours. If there will be no PR - then i stucked.
